### ISSUE TITLE
Installing graspologic on M1

### ISSUE THREAD

**Issue by adikondepudi** [microsoft/graspologic#1007]
I'm trying to install graspologic on an M1 computer and I'm running into all sorts of errors. Installing by simply doing ```conda install graspy``` yields the error of 'No module named 'sklearn.mixture.gaussian_mixture''. This, when looking at a prior issue, seems to be related to the fact that graspologic doesn't support python 3.9 (at the time the issue was made. However, as of the time this issue was made, graspologic supports python 3.9. However, I still get the issue that I don't have the gaussian_mixture module (even though if I use the module through another python script, it works fine). 

Even creating a conda environment using a intel version of miniconda, running the terminal using rosetta so it forces all the packages to be osx-64 (intel), and forcing the python version to be 3.7, I still get the error 'No module named 'sklearn.mixture.gaussian_mixture'. 

If anyone has any guidance on how I can install graspologic on osx-arm64, it would be much appreciated.

**Comment by bdpedigo** [comment]
`graspy` is actually another package which is no longer supported. the recommended install for graspologic is via `pip install graspologic`. please let me know if that solves your issue?
