### ISSUE TITLE
[BUG]  Following the first tutorial on the documentation, first example fails due to networkx

### ISSUE THREAD

**Issue by aad1tya** [microsoft/graspologic#1020]
## Expected Behavior
```
import numpy as np
from graspologic.datasets import load_drosophila_right
from graspologic.plot import heatmap
from graspologic.utils import binarize, symmetrize
%matplotlib inline

adj, labels = load_drosophila_right(return_labels=True)
adj = binarize(adj)
_ = heatmap(adj,
        inner_hier_labels=labels,
        title='Drosophila right MB',
        font_scale=1.5,
```

This above code should run as documented [here](https://microsoft.github.io/graspologic/latest/tutorials/models/models.html).

## Actual Behavior

AttributeError: module 'networkx' has no attribute 'OrderedGraph'

## Full Traceback
```AttributeError: module 'networkx' has no attribute 'OrderedGraph'
AttributeError                            Traceback (most recent call last)
Cell In[2], line 3
      1 import numpy as np
      2 from graspologic.datasets import load_drosophila_right
----> 3 from graspologic.plot import heatmap
      4 from graspologic.utils import binarize, symmetrize
      5 get_ipython().run_line_magic('matplotlib', 'inline')

File ~/Documents/github-contribs/graspologic-test/lib64/python3.9/site-packages/graspologic/__init__.py:13
     11 import graspologic.nominate
     12 import graspologic.partition
---> 13 import graspologic.pipeline
     14 import graspologic.plot
     15 import graspologic.preprocessing

File ~/Documents/github-contribs/graspologic-test/lib64/python3.9/site-packages/graspologic/pipeline/__init__.py:21
      1 """
      2 The ``pipeline`` module includes a collection of higher level API abstractions from
      3 the functionality exposed elsewhere in ``graspologic``. The classes, functions, and
   (...)
     16 
     17 """
     18 # Copyright (c) Microsoft Corporation.
     19 # Licensed under the MIT license.
...
    143 
    144     """
    145     check_argument(dimensions >= 1, "dimensions must be positive")

AttributeError: module 'networkx' has no attribute 'OrderedGraph'

```

## Your Environment
Linux-6.1.6-200.fc37.x86_64-x86_64-with-glibc2.36
Python 3.9.16 (main, Dec  7 2022, 00:00:00) 
[GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
* graspologic version: v2.0.1

## Additional Details
I think this is happening because when doing "pip install graspologic", it installs networkx version 3.0 which doesn't have OrderedGraphs.
I will update after testing the same on networkx version < 3.0

**Comment by aad1tya** [comment]
Yep, installing networkx==2.8.8 solves this issue. But by default, graspologic installs networkx==3.0.

**Comment by bdpedigo** [comment]
hi @aad1tya, yes this is a known issue (see https://github.com/microsoft/graspologic/issues/1015)

we've "fixed" it, but just need to do a new release, hopefully soon.

if you'd like the most up to date (but sometimes untested) version of graspologic you can do 

`pip install graspologic --pre`

but downgrading networkx is also a solution as you suggest
