### ISSUE TITLE
[Question] coefficient magnitude, GCT

### ISSUE THREAD

**Issue by jamesdalg** [microsoft/graspologic#1052]
Hello! I attended your course at JSM in August and I'm wondering if there is something within the graspologic package that will give a measure of effect size in addition to a p-value for the connectivity between groups (e.g. an omega coefficient in an ERGM). I saw the group connection test in your package and it seems to be the closest to what I'm trying to do, but it would be helpful to have a measure of the magnitude of the association. To explain, my matrices that I'm turning into graphs are valued and I am trying to find something that gives a sense for the effect size of how the connection between blocks changes between two conditions.

Best,
James Dalgleish

**Comment by bdpedigo** [comment]
Hi @jamesdalg - you can find a `"stats"` field in the `misc` dictionary returned by `group_connection_test`, the exact meaning of which will depend on the exact test you asked for with `method`. https://microsoft.github.io/graspologic/latest/reference/reference/inference.html#graspologic.inference.group_connection_test

perhaps that's what you want?

**Comment by jamesdalg** [comment]
I think that's exactly it!! Great. Thanks!

**Comment by jamesdalg** [comment]
What I noticed is that I can't use the SBM on valued edges. Is there some model that allows for edge weights?
```
    192 graph = import_graph(graph)
    194 if not is_unweighted(graph):
--> 195     raise NotImplementedError(
    196         "Graph model is currently only implemented for unweighted graphs."
    197     )
    199 if y is None:
    200     self._estimate_assignments(graph)

NotImplementedError: Graph model is currently only implemented for unweighted graphs.
```

**Comment by bdpedigo** [comment]
conceptually, sure. one can put a distribution on the weights in a given block, say. obviously we don't have such a thing implemented.

if you did that, you'd just have to decide how you want to compare the two distributions in two different graphs, say. this paper talks about some possible options https://arxiv.org/pdf/2011.14990.pdf

**Comment by jamesdalg** [comment]
Sounds great! I'll look into it.
