### ISSUE TITLE
[Question] Is Windows 11 OS supported?

### ISSUE THREAD

**Issue by KaifAhmad1** [microsoft/graspologic#1058]
Can anyone confirm whether this package is fully compatible with the Windows 11 operating system? We need to ensure that all functionalities work seamlessly on this platform to provide our users with a smooth experience.

**Comment by bdpedigo** [comment]
our CI tests on `windows-latest` which I believe is now Windows Server 2022. i don't have a windows 11 machine to test further, but I haven't heard of any issues.
