### ISSUE TITLE
see if other graph searches are faster than conversion to networkx for LCC check

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#112]
https://scikit-learn.org/stable/modules/generated/sklearn.utils.graph_shortest_path.graph_shortest_path.html#sklearn.utils.graph_shortest_path.graph_shortest_path

I am guessing the speedup from not switching datatypes completely pays off

**Comment by bdpedigo** [comment]
https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csgraph.connected_components.html

**Comment by bdpedigo** [comment]
https://github.com/scikit-learn/scikit-learn/blob/7b136e9/sklearn/manifold/spectral_embedding_.py#L340

looks like sklearn version calls the scipy one if sparse and has a custom thingy for dense. Could be useful for us

**Comment by bdpedigo** [comment]
@kareef928 may also be of interest (semi related to #485)

**Comment by kareef928** [comment]
Sure, I think I need a bit of guidance to understand what I am actually doing

**Comment by bdpedigo** [comment]
for sure! we would have to talk about it. long story short this function gets called for all of our embeddings and right now the way that we do it is super slow.

**Comment by kareef928** [comment]
DoD:

- Implement the other graph searching methods provided above for LCC check

- Run simulation to determine which graph search is the fastest using different settings of graphs

- Push the fastest graph search method

**Comment by bdpedigo** [comment]
IMO this one is top priority for making things faster cause this affects LDT also.

**Comment by kareef928** [comment]
Ok, I still need to iron out some details with this issue so we can talk about that on Friday

**Comment by kareef928** [comment]
I would also be fine giving this issue to someone else if they need an issue to work on
