### ISSUE TITLE
Look at differences in U and V when matrix is almost symmetric

### ISSUE THREAD

**Issue by j1c** [microsoft/graspologic#114]
## Expected Behavior
Graspy should be robust to almost symmetric matrices. That is when given an input `X` and  elements in `X-X.T` is within some tolerance, treat it as a symmetric matrix. 

Still should investigate the differences in `U @ np.diag(D**0.5)` and `V @ np.diag(D**0.5)` when input is almost symmetric. 

Almost symmetric is defined as `max(X-X.T) < 1e-15`.

**Comment by bdpedigo** [comment]
also this 
https://github.com/scikit-learn/scikit-learn/blob/7389dba/sklearn/utils/validation.py#L848
