### ISSUE TITLE
other graph two-sample testing approaches worth considering

### ISSUE THREAD

**Issue by jovo** [microsoft/graspologic#118]
1. Practical Methods for Graph Two-Sample Testing
2. HYPOTHESIS TESTING FOR NETWORK DATA IN FUNCTIONAL NEUROIMAGING

**Comment by j1c** [comment]
1. https://arxiv.org/abs/1811.12752 - interesting and simple for tests for two populations. Tho not sure how they claim their method for the case `m=1` is better given this plot... Seems like Minh wins in almost all cases. `Boot-ASE` is Minh. Not sure what the two columns mean too...

![screen shot 2019-02-19 at 12 06 43 am](https://user-images.githubusercontent.com/5142539/52991394-8b08af00-33da-11e9-9fba-aa6fd2960b87.png)
