### ISSUE TITLE
implement CASC

### ISSUE THREAD

**Issue by jovo** [microsoft/graspologic#134]
https://academic.oup.com/biomet/article/104/2/361/3074977

here is the R package: 
https://github.com/norbertbin/SpecClustPack

@rflperry

**Comment by bdpedigo** [comment]
also this maybe https://link.springer.com/article/10.1007%2Fs00180-019-00909-8

**Comment by bdpedigo** [comment]
In #289

**Comment by loftusa** [comment]
possibly interested in this for sprint 2

**Comment by dtborders** [comment]
also possibly interested for sprint 2

**Comment by loftusa** [comment]
Taking this.

DoD:
- recreate figure 1 in [casc](https://academic.oup.com/biomet/article/104/2/361/3074977)
- tests (open to suggestions/changes)
- implementation plan + implementation
- tutorial notebook PRd into documentation
