### ISSUE TITLE
[1701.08140] Network classification with applications to brain connectomics

### ISSUE THREAD

**Issue by jovo** [microsoft/graspologic#150]
is another signal subgraph detection method:
https://arxiv.org/abs/1701.08140
let's add this too.

**Comment by jovo** [comment]
R code here: https://github.com/jesusdaniel/graphclass

**Comment by caseypw** [comment]
@jovo @j1c @bdpedigo 
#### I will address this for Sprint 1 this semester.
-------------------------------------------------------
I will 
- Convert these four files, located [here](https://github.com/jesusdaniel/graphclass), from R to a Python file with sklearn api:
  - graphclass.R
  - Logistic_group_lasso_ridge.R
  - FISTA_line_search_ridge.R
  - ADMM_group_lasso.R
- I will then make a PR to merge file(s) into Graspy

**Comment by bdpedigo** [comment]
@caseypw can you list any figures or experiments or comparisons to existing code you will run in order to show it is correct?

**Comment by caseypw** [comment]
After porting all of the code, I will recreate figure 5 on page 20 to show the code works
