### ISSUE TITLE
Create a dataloader for MASE

### ISSUE THREAD

**Issue by rflperry** [microsoft/graspologic#228]
The MASE fit function currently requires a list of arrays or graphs to be passed in. This requires all such graphs or arrays to be loaded into RAM which is problematic for large datasets. But MASE computes ASE on each input separately and would be able to run on less RAM by loading inputs one at a time.

**Comment by bdpedigo** [comment]
@rflperry have you had a usecase for this?

**Comment by rflperry** [comment]
I think this came up when I was running meditation data through MASE? Cortical vertex resolution fmri data meant 228 correlations matrices of 18715x18715 which is prohibitive to compute (~600 GB by my 8byte float estimate). I implemented a [`partial_fit`](https://github.com/mvlearn/mvlearn/blob/master/mvlearn/embed/gcca.py#L209) function in GCCA although GCCA didn't need it for the data as it never needs to estimate the full correlation matrix.

**Comment by loftusa** [comment]
allow a generator to be passed in?

**Comment by j1c** [comment]
This is a bit tricky since we have to ensure that all of input graphs have same # of vertices and ordered correctly. 

@rflperry If you can think of a neat solution, im all for it. But in the meantime, I say get a bigger computer.

**Comment by bdpedigo** [comment]
Trying to close out issues that I think we don't have a strong desire to do/use case/person who is passionate about doing it

I motion to close this issue for now, and if someone runs into this issue again, can cross that bridge when we come to it? 

Lmk if anyone disagrees (which is fine)

**Comment by rflperry** [comment]
Yeah fine with closing.
