### ISSUE TITLE
Add tutorial for MASE

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#244]

**Comment by pauladkisson** [comment]
I am interested in this one!

**Comment by pauladkisson** [comment]
Deliverables for MASE tutorial:

1. Problem Statement — why MASE
2. How does MASE work in general
3. How is MASE implemented specifically in GraSpy
4. At least 1 example using MASE with generative models
5. At least 1 example using MASE with a  real-world network
6. At least 1 example of specifying each MASE parameter (Note, this should be included in (4) and (5) ).

**Comment by bdpedigo** [comment]
> How is MASE implemented specifically in GraSpy

This is less important in a tutorial. It is great to have, but may want it to be part of a separate "advanced tutorial" or an appendix to the main tutorial

**Comment by pauladkisson** [comment]
Hmm, well I wasn't planning on going into too much detail.  Just like a 1-2 sentence summary.

**Comment by pauladkisson** [comment]
Also, is there any reason why the class called MultipleASE in Graspologic rather than MASE (as it is in the literature)?
