### ISSUE TITLE
Add checklist to PR template 

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#276]
Example PR: https://github.com/scikit-image/scikit-image/pull/3983

**Comment by saadhaxxan** [comment]
Hello, @bdpedigo I can add a checklist to the PR template can you tell me where is the PR template located in the repo or I create completely from start?

**Comment by bdpedigo** [comment]
hi @saadhaxxan, that's great! the PR template is [here](https://github.com/microsoft/graspologic/blob/dev/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by saadhaxxan** [comment]
@bdpedigo I have added and Checklist and created a pull request for that 👍👍

**Comment by bdpedigo** [comment]
thanks for the PR @saadhaxxan. It may be a little bit until we get to reviewing that PR (we are redoing lots of things about contributor guidelines right now) but we will definitely have a look
