### ISSUE TITLE
Ensure Python 3.8 compliance, update docs and tests to reflect that

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#277]

**Comment by dfrancisco1998** [comment]
Id like to be on this subproject!

**Comment by dfrancisco1998** [comment]
How would you want me to demonstrate DoD? As of right now I have jupyter notebooks with the tutorials runnins on python 3.8.5. For the other folders (without tutorials already made) would you recommend I just make some examples which would utilize each part?

**Comment by dfrancisco1998** [comment]
Or should I run all the tests(in the repo) in a python 3.8 environment? Hoe would I provide evidence?

**Comment by bdpedigo** [comment]
All tests need to pass and tutorials need to build in a python 3.8 environment. DoD is that when you add 3.8 as an environment for our automated build process, all checks pass.

**Comment by j1c** [comment]
Part of doing this is to fix an issue with `rdpg` in `graspy.simulations` not working properly when changed to 3.8. Tests passing means to figure out why the `rdpg` doesn't return expected array.

**Comment by dfrancisco1998** [comment]
So should I only be working with trying to get this work with python 3.7? I am a little confused about this workflow atm. Also @j1c I have been able to run all the tests with python 3.8.5 on my machine for the graspy simulations tests (as seen in my prelim PR docs in dfrancisco1998-tests directory). So I think that part is good. I have been getting two errors though, which seem to indicate an issue with file not found in the /tests/match/ tests as well as an error  zero-size array to reduction operation minimum which has no identity for the test_plot.py testing gridplot. I even get an error when I run through the tutorial for plotting with python 3.8.5. I have been trying to fix these two issues this past weekend, but I am running out of ideas.

**Comment by bdpedigo** [comment]
> So should I only be working with trying to get this work with python 3.7? 
no, I don't follow.

in general, best way to get help is to post on this issue with exactly what errors you are getting (and when, e.g. the details of your environment), exactly what you have tried to get unstuck, and then send that out to the team asking for help.

**Comment by dfrancisco1998** [comment]
These are the versions of the tools I  am using: 
python                    3.8.5  
scikit-learn              0.23.2                  
scipy                     1.5.0            
seaborn                   0.10.1
pandas                    1.1.1 
numpy                     1.19.1
pytest                    6.0.1                  
pytest-cov                2.10.1                

All these errors were run with the pytest version above as well but typing py.test tests 

While running the files in the tests directory I had gotten two errors. In test_plot.py, there was an issue with the gridplot() which was noticed because the test_gridplot_outputs() failed with "ValueError: zero-size array to reduction operation minimum which has no identity". 
I had tried tracing through the code and working on doing each part separately in a jupyter notebook and there was nothing that was empty(X list had two graphs in it). It may be something with the dataframes, but my tracing has  lead me to believe that is not the case. 
The other error was in /tests/match/ where I got file not found errors for lipa20a and chr12c in the test_barycenter_SGM(self) function. I had tried to access these files in a notebook and it seemed to work. I then tried to change the slashes as well as use an updated path and turn the string into a path object but nothing helped. So I am stuck here as well.

**Comment by bdpedigo** [comment]
@dfrancisco1998 
- whats ur matplotlib version? see #402, may be the same issue for the gridplot thing. 
- for the second one, traceback would me more helpful than a description. maybe @asaadeldin11 can help since it is GM related?

**Comment by dfrancisco1998** [comment]
@bdpedigo  and @asaadeldin11 here is the tracebook from the py.test run for second problem : 
dfran@DESKTOP-3FUUKF1 MINGW64 ~/OneDrive/Documents/Hopkins/Hopkins_senior/Neurodata/branch_graspy/graspy/tests (dfrancisco1998)
$ py.test match/
============================= test session starts =============================
platform win32 -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: C:\Users\dfran\OneDrive\Documents\Hopkins\Hopkins_senior\Neurodata\branch_graspy\graspy, configfile: pytest.ini
plugins: cov-2.10.1
collected 4 items

match\test_match.py .FF.                                                 [100%]

================================== FAILURES ===================================
_________________________ TestGMP.test_barycenter_SGM _________________________

self = <test_match.TestGMP object at 0x0000014439B24FD0>

    def test_barycenter_SGM(self):
>       A, B = self._get_AB("lipa20a")

match\test_match.py:73:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_match.TestGMP object at 0x0000014439B24FD0>, qap_prob = 'lipa20a'

    def _get_AB(self, qap_prob):
>       with open("tests/match/qapdata/" + qap_prob + ".dat") as f:
E       FileNotFoundError: [Errno 2] No such file or directory: 'tests/match/qapdata/lipa20a.dat'

match\test_match.py:61: FileNotFoundError
____________________________ TestGMP.test_rand_SGM ____________________________

self = <test_match.TestGMP object at 0x0000014439B24430>

    def test_rand_SGM(self):
>       A, B = self._get_AB("chr12c")

match\test_match.py:124:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_match.TestGMP object at 0x0000014439B24430>, qap_prob = 'chr12c'

    def _get_AB(self, qap_prob):
>       with open("tests/match/qapdata/" + qap_prob + ".dat") as f:
E       FileNotFoundError: [Errno 2] No such file or directory: 'tests/match/qapdata/chr12c.dat'

match\test_match.py:61: FileNotFoundError
============================== warnings summary ===============================
c:\users\dfran\miniconda3\envs\ndd\lib\site-packages\win32\lib\pywintypes.py:2
  c:\users\dfran\miniconda3\envs\ndd\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp, sys, os

-- Docs: https://docs.pytest.org/en/stable/warnings.html

----------- coverage: platform win32, python 3.8.5-final-0 -----------
Name                                                                                                                       Stmts   Miss  Cover
----------------------------------------------------------------------------------------------------------------------------------------------
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\__init__.py                                15      0   100%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\cluster\__init__.py                         4      0   100%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\cluster\autogmm.py                        256    235     8%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\cluster\base.py                             7      0   100%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\cluster\gclust.py                          94     85    10%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\cluster\kclust.py                          40     33    18%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\datasets\__init__.py                        2      0   100%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\datasets\base.py                           26     22    15%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\embed\__init__.py                           7      0   100%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\embed\ase.py                               19     13    32%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\embed\base.py                              55     38    31%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\embed\lse.py                               17     11    35%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\embed\mase.py                              44     34    23%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\embed\mds.py                               68     57    16%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\embed\omni.py                              29     20    31%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\embed\svd.py                              106     99     7%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\inference\__init__.py                       3      0   100%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\inference\base.py                          18      8    56%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\inference\latent_distribution_test.py     139    115    17%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\inference\latent_position_test.py          86     74    14%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\match\__init__.py                           3      0   100%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\match\gmp.py                              136     78    43%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\match\skp.py                               58     10    83%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\models\__init__.py                          5      0   100%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\models\base.py                             87     65    25%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\models\er.py                               27     16    41%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\models\rdpg.py                             47     38    19%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\models\sbm.py                             162    142    12%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\pipeline\__init__.py                        2      0   100%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\pipeline\mug2vec.py                        36     27    25%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\plot\__init__.py                            4      0   100%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\plot\plot.py                              392    365     7%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\simulations\__init__.py                     3      0   100%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\simulations\rdpg_corr.py                   26     23    12%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\simulations\simulations.py                257    247     4%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\simulations\simulations_corr.py            98     89     9%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\subgraph\__init__.py                        1      0   100%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\subgraph\sg.py                             85     79     7%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\utils\__init__.py                           2      0   100%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\utils\ptr.py                               44     40     9%
C:\Users\dfran\Miniconda3\envs\ndd\Lib\site-packages\graspy-0.3.0-py3.8.egg\graspy\utils\utils.py                            212    189    11%
----------------------------------------------------------------------------------------------------------------------------------------------
TOTAL                                                                                                                       2722   2252    17%

=========================== short test summary info ===========================
FAILED match\test_match.py::TestGMP::test_barycenter_SGM - FileNotFoundError:...
FAILED match\test_match.py::TestGMP::test_rand_SGM - FileNotFoundError: [Errn...
=================== 2 failed, 2 passed, 1 warning in 25.66s ===================
(ndd)

**Comment by dfrancisco1998** [comment]
@bdpedigo my matplotlib version is 3.3.1 . So maybe I should downgrade to 3.1.1 since due to #402 has that version working now?

**Comment by bdpedigo** [comment]
see #455
