### ISSUE TITLE
Recursive clustering/hierarchical SBM

### ISSUE THREAD

**Issue by tathey1** [microsoft/graspologic#299]
Would like code to do the following: 
- class that supports recursively splitting the data with some clustering function and some criteria for when to split/not split. Can start with just GMM, but may want to write the code in such a way that it could generalize to other methods (there is nothing magic about GMM here). 
- class that supports fitting a hierarchical stochastic block model (HSBM). This is intimately linked to the above, but would also include dealing with the graph itself as the clustering repeats, and possibly dealing with metadata (or at least makes it easy to relate the multi-level labels to the graph metadata). One tricky thing here is that the original HSBM paper re-embeds at each stage, in practice I have also found that not re-embedding can work well. Ideally code will support both.

**Comment by tathey1** [comment]
changes being addressed in https://github.com/neurodata/graspy/tree/pgmm

**Comment by bdpedigo** [comment]
Also have a rough implementation [here](https://github.com/neurodata/maggot_models/blob/master/src/cluster/divisive.py) using [anytree](https://anytree.readthedocs.io/en/latest/) to keep track of the splits, which I found I needed for my implementation. Work in progress for sure though.

**Comment by bdpedigo** [comment]
very related to #156, merging that issue into this one

**Comment by bdpedigo** [comment]
long script that essentially fits an HSBM and does this recursive clustering (in addition to other stuff) 
https://github.com/neurodata/maggot_models/blob/dev/notebooks/137.7-BDP-omni-clust.py

some bad code that does the backend of the recursive clustering and keeps track of metadata
https://github.com/neurodata/maggot_models/blob/9f24b3239bb0cc426c8556b124c75a612b9af34f/src/cluster/spectral.py#L367

**Comment by bdpedigo** [comment]
@tathey1 are you okay if I clear you as assignee? Otherwise, lmk if you still wanna do this?

**Comment by bdpedigo** [comment]
@tliu68 this should be you?

**Comment by tliu68** [comment]
I'd like to take this one.
