### ISSUE TITLE
implement vertex nomination via SGM

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#309]

**Comment by bdpedigo** [comment]
https://arxiv.org/pdf/1705.00674.pdf

**Comment by bdpedigo** [comment]
@asaadeldin11 maybe will do this for NDD

**Comment by bdpedigo** [comment]
@bdpedigo  reminder to ask carey if anyone uses this

**Comment by spencer-loggia** [comment]
Interested in this as well!

**Comment by dtborders** [comment]
Also interested!

**Comment by dtborders** [comment]
Workflow plan
1. Implement Soft seeded graph matching (a simpler version of VN match)
2. Implement VNmatch

Dod:
Reproduce experiments demonstrated in Figure 2 and 3 to ensure that the algorithm can work on simulated data. 
Reproduce figures 4 and 5 from the paper to ensure the vertex matching Alg is working correctly. 
Test Algorithm on some form of real data neural data (unsure what data would be best to use).
