### ISSUE TITLE
Implement Padded SGM algorithm

### ISSUE THREAD

**Issue by SHAAAAN** [microsoft/graspologic#316]
## functionality
Input Graphs G1 and G2 with respective vertex sets {1,...,n_1} and {1,...,n_2} and with respective adjacency matrices A and B, and suppose n_1<n_2, use the SGM function to the padded A and B, then return the restriction of permutation matrix to the vertices of G1.

The output can be compared with Figure 3 in paper seeded graph matching: https://arxiv.org/pdf/1209.0367.pdf.

**Comment by bdpedigo** [comment]
@SHAAAAN if you still have code/experiments for this in any form, would you mind just linking them here?

**Comment by SHAAAAN** [comment]
Sure. Here is what I have done so far. 
https://github.com/SHAAAAN/MyGraspy/blob/master/codes/padding.ipynb  
I met some problems when I tried to merge it with the original SGM algo. Hope this is useful for other talented people~

**Comment by bdpedigo** [comment]
Thanks so much Shan! Hope all is well for you

**Comment by asaadeldin11** [comment]
I have some code for this so I can take this. Would be a relatively quick fix once QAP is in scipy.
