### ISSUE TITLE
Add multi-scale significance tests for populations of graphs

### ISSUE THREAD

**Issue by v715** [microsoft/graspologic#330]
it might be nice to have statistical methods for analyzing populations connectomes implemented in graspy. 

multi-scale algorithms could be used to find significantly different edges, vertices, and communities in populations of connectomes from different phenotypes.

is this something you guys would be interested in?

**Comment by bdpedigo** [comment]
Sure! Seems like it would be worth having, and having an open-source implementation prior to publication could be cool for you/others. 

If you'd like to proceed, I would just recommend mapping out the API and structure of the code and discussing with us prior to spending a ton of time on the implementation, just so you don't waste any effort. Let me know if you have plans you want to chat about.

**Comment by v715** [comment]
sounds good! what do you think of this:

# Main contribution
- add three files to the `inference` submodule: `edge_test.py`, `vertex_test.py`, and `block_test.py`

## Test structure
- for each scale, make a class (i.e. `BlockTest`) that handles all testing
- endow each class with a function `self.test()` that returns a p-value for every edge, vertex, or block

specifics for each test are below:

### EdgeTest
1. initialize `EdgeTest` with a list of $n$ graphs and a list of $n$ corresponding class labels
2. if graphs are weighed, test using [kruskal wallis (KW)](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kruskal.html)
3. if graphs are unweighted, **not sure what to do**. 
3a. we could run KW again
3b. we could also use MGC here
3c. NIST also provides some options (see [here](https://www.itl.nist.gov/div898/handbook/prc/section4/prc46.htm#Example)), but these result in multiple comparisons per edge and that'll just nuke the power of this test
3d. did connectomics D&D ever reach a conclusion on this point?
4. there is also the option of letting the user pick the test they want to use... i don't like it because handling many different APIs might get messy. what do you think?
5. regardless of which test we go with, have `EdgeTest.test()` return a p-value for each edge!

### VertexTest
1. initialize `VertexTest` with a list of $n$ graphs and a list of $n$ corresponding class labels
2. allow the user to optionally do any graph preprocessing available in `graspy` (i.e. ptr, diagonal augmentation, centering). note that diagonal augmentation and centering are not yet implemented, so i will add those to the `utils` submodule
3. embed the graphs using `omni` (@v715 figure out what to do if graphs are directed)
4. for each vertex, test for significant differences using statsmodels' MANOVA and have `VertexTest().test` return a p-value for each vertex

### BlockTest
1. initialize `BlockTest` with a list of $n$ graphs and a list of $n$ corresponding class labels, and an _a priori_ block label
2. two tests are going to be implemented here
2a. univariate test: for each block, calculate the average edge weight for each group, use MGC to test for differences across groups
2b. multivariate test: for each block, vectorize the block, use MGC to test for differences across groups
3. for both tests, have `EdgeTest.test()` return a p-value for each block

## Other nice things to have
- add a function that plots ranked p-values + bonferroni correction
- add the autism mouse data set so people have a k-sample connectome data set to play with
- add tutorial notebooks demonstrating the use of each of these functions on the autism mouse data

**Comment by j1c** [comment]
Looks fine. One major thing is that classes are never initialized with data, but just parameters. the `.test()` function should take the data as inputs (should this be called `.fit()`?). Regarding `3d`, I would say chi-squared test, but currently, the paper specifically deals with 2 sample case. Although I should think about adding the >2 sample cases for the paper. 

Couple of things Im not sure about:
- adding statsmodels to be a dependency..
- besides time considerations, why can't we just use `mgc` as our test of choice for everything?

**Comment by v715** [comment]
word, will pass data to a `fit()` function instead!

also I have no problem using MGC for everything, it's just not the way I did things in my manuscript. but for a first pass, it's fine by me!

shall i make 3 seperate PRs (one for each significance test) or would you prefer a single PR?

**Comment by v715** [comment]
Since there's already a base class in the `inference` submodule, im planning to make a new submodule called `connectomics`. lmk if you'd rather i do something different

**Comment by bdpedigo** [comment]
Is anything about the method specific to connectomes? seems it would work for general graph data.

**Comment by v715** [comment]
no you're right, this will work for any population of vertex-matched graphs! 

what if I create two submodules within `inference`, one for independence testing and one for graph comparisons?

**Comment by bdpedigo** [comment]
What do you mean for the independence testing stuff?

I think just another file or set of files in the current module is fine. I
don't know what you want to call it. Maybe just something related to
k-sample?

**Comment by v715** [comment]
sorry by independence stuff, i meant the latent distribution and position tests

sure, i’ll put all the files in the inference module and call the base class base_ksample. thanks for all the input!
On Apr 18, 2020, 8:08 PM -0400, Benjamin Pedigo <notifications@github.com>, wrote:

What do you mean for the independence testing stuff?

I think just another file or set of files in the current module is fine. I
don't know what you want to call it. Maybe just something related to
k-sample?

**Comment by bdpedigo** [comment]
Sure, if you think of a better name I'm happy to hear it too!
