### ISSUE TITLE
Add `n_iter_` attribute after fit to GraphMatch

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#342]
https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html

Sklearn estimators often have `n_iter_` to indicate how many iterations were needed to converge or stop, would be helpful to know whether graph matching is converging because of epsilon or max_iter

**Comment by dtborders** [comment]
Ill take this one!

**Comment by dtborders** [comment]
@bdpedigo should we close this?

**Comment by bdpedigo** [comment]
yes i'll close, thank you

FYI if you do `Fixes #342 ` as opposed to `Fixes issue #342` in the PR description, it will close automatically when PR is merged next time
