### ISSUE TITLE
similarity augmented graph matching

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#347]

**Comment by bdpedigo** [comment]
IGraphMatch can accept an n x n similarity matrix on the nodes 
https://github.com/dpmcsuss/iGraphMatch/blob/52870fc16e03291776c644cc3c4ad461183805ab/R/graph_match_methods.R#L61

**Comment by bdpedigo** [comment]
not sure if this is the same as #346

**Comment by bdpedigo** [comment]
@asaadeldin11 i have you down for this cause you have code for it, but I also have you assigned a bunch of other issues. if you want someone else to take your code and make it an actual PR w/ tests and docs and such for NDD, just lmk

**Comment by bdpedigo** [comment]
> @asaadeldin11 i have you down for this cause you have code for it, but I also have you assigned a bunch of other issues. if you want someone else to take your code and make it an actual PR w/ tests and docs and such for NDD, just lmk

bump @asaadeldin11

**Comment by asaadeldin11** [comment]
This is next on my to do list after #542 is merged
