### ISSUE TITLE
merge GraphMatch into scipy and refactor GraphMatch to use it

### ISSUE THREAD

**Issue by jovo** [microsoft/graspologic#348]

**Comment by bdpedigo** [comment]
@asaadeldin11 want to rip out the guts from `GraphMatch` when your scipy PR is merged/released? or wanna have someone in NDD work on this?

**Comment by asaadeldin11** [comment]
Yeah I can take care of this once it's merged. It'll probably also be a good idea to update the version of scipy required for graspy once we do this.
