### ISSUE TITLE
Add `n_features_in_` for scikit-learn compliance 

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#352]
`FutureWarning: As of scikit-learn 0.23, estimators should expose a n_features_in_ attribute, unless the 'no_validation' tag is True. This attribute should be equal to the number of features passed to the fit method. An error will be raised from version 0.25 when calling check_estimator().`

**Comment by bdpedigo** [comment]
need to look at everything we claim passes `check_estimator()`

**Comment by zeou1** [comment]
I can do this one then.

**Comment by zeou1** [comment]
Hi I am wondering how do I locate places where I need to add the 'n_features_in_'

**Comment by bdpedigo** [comment]
for now, just the stuff [here](https://github.com/neurodata/graspy/blob/master/tests/test_sklearn.py)
