### ISSUE TITLE
compare ZG(2) to minka

### ISSUE THREAD

**Issue by jovo** [microsoft/graspologic#360]
to select the number of components in PCA, sklearn uses this: 
https://papers.nips.cc/paper/1853-automatic-choice-of-dimensionality-for-pca.pdf

but graspy uses this: https://www.sciencedirect.com/science/article/abs/pii/S0167947305002343

compare the two via simulations and see which is better, and if either of us should switch

**Comment by jovo** [comment]
this says ZG(1) is sucky: https://hal.archives-ouvertes.fr/hal-01484099/document

this has a bunch of simulated settings possibly worth considering: https://reader.elsevier.com/reader/sd/pii/S0167947311004099?token=22CA3714EEC6A4B5FCC3DFD1759E133AACFB4CDC5F2CD66BC6CADE67B8DAB5B263ED7EEB6639E7C2C68B69DCEEB820A1

**Comment by bdpedigo** [comment]
@asaadeldin11  some context if you end up looking at this

**Comment by bdpedigo** [comment]
anotha one https://github.com/arvkevi/kneed

**Comment by bdpedigo** [comment]
considering this again as an NDD task...

**Comment by jovo** [comment]
totally for it!

On Fri, Oct 16, 2020 at 2:23 PM Benjamin Pedigo <notifications@github.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
> considering this again as an NDD task...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fgraspologic%2Fissues%2F360%23issuecomment-710371830&data=04%7C01%7Cjovo%40jhu.edu%7C6f6eefe308af48083d7208d87200856a%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637384693842234584%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=b2mC%2BaX5kAQt2VHktdk9%2BISkAqL6hwKvcSVflHyGXhM%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4RJNE3RZ3YM6ZRHWJTSLCFQNANCNFSM4NPJZ4EA&data=04%7C01%7Cjovo%40jhu.edu%7C6f6eefe308af48083d7208d87200856a%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637384693842234584%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ok1YtSz44vBppB5Y6OYgoJvfj1dVUQOSVfC%2FIsZGL0U%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time.
How can I do better? <https://forms.gle/iEad8byD89eTPdYx6>

**Comment by dfrancisco1998** [comment]
I am interested!

**Comment by pauladkisson** [comment]
I am also interested in this one.

**Comment by rflperry** [comment]
Check out the code in this package https://github.com/idc9/ya_pca/tree/master/ya_pca/rank_selection. We've worked with the developer on mvlearn, but it's PCA and lots of different rank selection methods including Minka. They're compared in this [notebook](https://github.com/idc9/ya_pca/blob/master/docs/example_notebooks/PCA%20rank%20selection%20methods.ipynb) but it's a bit rough.

**Comment by jovo** [comment]
it occurs to me that scipy should have one of these, which ever is 'best'
i'd guess ZG(2), but Minka is possible (or one of the others, i guess)

**Comment by bdpedigo** [comment]
notebook looks pretty helpful tho?

**Comment by rflperry** [comment]
Iain and I had talked about the benefit of a `rank_selection` module or something that made it easy to use any of them (or the 'best' few) in any function that had a rank selections step.

**Comment by bdpedigo** [comment]
> Iain and I had talked about the benefit of a `rank_selection` module or something that made it easy to use any of them (or the 'best' few) in any function that had a rank selections step.

Sounds like a great idea, seems like mvlearn + graspologic could both use. And whatever's best, as jovo says, would want to push into scipy/sklearn as appropriate. 

Is https://github.com/arvkevi/kneed in the notebook?

**Comment by bdpedigo** [comment]
also just a note - looks like the ZG code was based on graspy but is not using the Carey trick (basically only check the first log2 singular values) so I would expect results different from ours on real data

**Comment by jovo** [comment]
right, only we will have those tricks.

ronan - seems like mvlearn will care too, maybe you/them might do the
experiment good to get something in scipy, which seems is where it should
go?

**Comment by asaadeldin11** [comment]
@dfrancisco1998 would you be interested in doing this instead of #579 ?

This is more overdue, so I think we'd like to get it done first.

**Comment by rflperry** [comment]
I was intrigued by this but had some other things to wrap up first, certainly can help out until I have more time.

**Comment by rflperry** [comment]
Note, sklearn's [PCA](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html) uses minka as an automatic selection.

**Comment by dfrancisco1998** [comment]
Some old work experiment from last sem https://github.com/dfrancisco1998/ndd_stuff/tree/master/sprint2 . 
I am rereading the above papers and developing an experiment design, not complete yet.
