### ISSUE TITLE
create an align module

### ISSUE THREAD

**Issue by alyakin314** [microsoft/graspologic#367]
create an align module, which should include at least the following:

- [x] sign flips (currently used in the latent distribution test)
- [x] regular procrustes
- [ ] modified matched procrustes (currently used in the latent position test)
- [x] unmatched ('seedless') procrustes (currently in R code in Agterberg's github and in python on my old brunch)-

**Comment by bdpedigo** [comment]
thanks @alyakin314  this sounds great. let me know if you want to talk about how to structure all of this, I haven't thought about it too much.

**Comment by alyakin314** [comment]
@bdpedigo do you have any opinion on the api? should these be functions or classes? i feel that for all of these the reusability potential is similar to the inference - the only reason to fit the object again is to avoid re-instantiating parameters.

i see a couple ways we can pursue this:
1. classes that have a fit_transform(X, Y) which return X', Y' (in all of our applications so far, one of these is equivalent to starting ones). then we also have attributes/methods that return the (usually orthogonal) matrix Q s.t. X' = XQ, if there is such.
2.  classes that have a fit_predict(X, Y), which returns Q. the user then has to do X'=QX. this would be problematic if we ever had an align thing that transforms something nonlinearly.
3. functions which return X', Y' (and potentially something else)
4. functions which return Q (and potentially something else

- my implementation of the seedless procrustes is currently 2 (see: https://github.com/neurodata/graspy/blob/nonpar-fix/graspy/align/seedless_procrustes.py ). 
- scipy's procrustes is 3 with some additional disparity thing returned (see: https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.procrustes.html ). 
- sign flips function in nonpar code is 3
-  lastly, agterberg's implementation in R is 4. as it returns Q, R and the value of the objective (see: https://github.com/jagterberg/nonparGraphTesting/blob/master/R/optimal_transport.R)

they don't have to be all the same in theory, but since some of them can be used in the same context - it'd be nice if they are. i'd say seedless procrustes makes the most sense to be a class, because it has so many other things attached to it, in addition to X' and Y' ( Q, R, value of the objective), and it probably has more reasons to be such than inference, but i am not convinced yet that it needs to be.

thoughts?

**Comment by alyakin314** [comment]
also, we don't really transform the graphs with modified matched procrustes in the latent position test. we compute the statistic as if they were transformed such. i certainly can implement these, but how necessary are they?

**Comment by bdpedigo** [comment]
> also, we don't really transform the graphs with modified matched procrustes in the latent position test. we compute the statistic as if they were transformed with such. i certainly can implement these, but how useful is it?

Not sure what you mean, are you talking about here https://github.com/neurodata/graspy/blob/0f4441ddc8dc09840147fed0f33f7c6be2dedb30/graspy/inference/latent_position_test.py#L143

**Comment by bdpedigo** [comment]
> @bdpedigo do you have any opinion on the api? should these be functions or classes? i feel that for all of these the reusability potential is similar to the inference - the only reason to fit the object again is to avoid re-instantiating parameters.
> 
> i see a couple ways we can pursue this:
> 
> 1. classes that have a fit_transform(X, Y) which return X', Y' (in all of our applications so far, one of these is equivalent to starting ones). then we also have attributes/methods that return the (usually orthogonal) matrix Q s.t. X' = XQ, if there is such.
> 2. classes that have a fit_predict(X, Y), which returns Q. the user then has to do X'=QX. this would be problematic if we ever had an align thing that transforms something nonlinearly.
> 3. functions which return X', Y' (and potentially something else)
> 4. functions which return Q (and potentially something else
> 
> * my implementation of the seedless procrustes is currently 2 (see: https://github.com/neurodata/graspy/blob/nonpar-fix/graspy/align/seedless_procrustes.py ).
> * scipy's procrustes is 3 with some additional disparity thing returned (see: https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.procrustes.html ).
> * sign flips function in nonpar code is 3
> * lastly, agterberg's implementation in R is 4. as it returns Q, R and the value of the objective (see: https://github.com/jagterberg/nonparGraphTesting/blob/master/R/optimal_transport.R)
> 
> they don't have to be all the same in theory, but since some of them can be used in the same context - it'd be nice if they are. i'd say seedless procrustes makes the most sense to be a class, because it has so many other things attached to it, in addition to X' and Y' ( Q, R, value of the objective), and it probably has more reasons to be such than inference, but i am not convinced yet that it needs to be.
> 
> thoughts?

Here I am torn. I think 3. would be a common use case, but I definitely want to be able to get out Q. This is probably what makes sense 90% of the time for most uses revolving around graspy. 

On the other hand, the reason I thought it would make sense to have this align module in the first place is sorta because I kept wanting to use these tools like an object - for instance, I was learning a transformation from a subset of matched vertices, and then I was using that transformation on the rest of the data. So it felt like the `.fit` `.transform` framework would have made a lot of sense there

**Comment by alyakin314** [comment]
i'm kind of curious to know more about a specific case you're talking about. so, if i understand correctly: you have embeddings $X$, $Y_1$, $Y_2$, ... and you have a priori knowledge that all $Y_i$ have the same orientation (how? omni?). then you first align $X$ and $Y_1$ to learn a transformation $Q$ (say it's linear), and obtain $Y_1' = Y_1 Q$. but then reuse it as $Y_i' = Y_i' Q$? how often do you have a setting of this sort? if often - then i'd say it is a strong argument against 3, unless we also return an object of things (so 3+4 combined), and the function call would look like: `X_prime, Y_prime, dict_of_Q_objective_etc = seedless_procrustes(X, Y)` which is roughly similar to how scipy procrustes works, but to me this just looks messy.

i wasn't considering this sort of usage before. this fact, and the conversation in slack, make me lean towards having it as 1: a class with a fit and transform and an option to retrieve P or Q, objective function, etc. whenever possible. this is going to be my null, until/unless someone convinces me otherwise.

**Comment by alyakin314** [comment]
> > also, we don't really transform the graphs with modified matched procrustes in the latent position test. we compute the statistic as if they were transformed with such. i certainly can implement these, but how useful is it?
> 
> Not sure what you mean, are you talking about here
> 
> https://github.com/neurodata/graspy/blob/0f4441ddc8dc09840147fed0f33f7c6be2dedb30/graspy/inference/latent_position_test.py#L143

yes, i mean this. we compute norms, as if there was such transformation, but we don't actually ever compute X_prime / Y_prime.

**Comment by bdpedigo** [comment]
> > > also, we don't really transform the graphs with modified matched procrustes in the latent position test. we compute the statistic as if they were transformed with such. i certainly can implement these, but how useful is it?
> > 
> > 
> > Not sure what you mean, are you talking about here
> > https://github.com/neurodata/graspy/blob/0f4441ddc8dc09840147fed0f33f7c6be2dedb30/graspy/inference/latent_position_test.py#L143
> 
> yes, i mean this. we compute norms, as if there was such transformation, but we don't actually ever compute X_prime / Y_prime.

If by compute you mean compute for the user to see i agree. They are computed, we just throw them away after

**Comment by bdpedigo** [comment]
> i'm kind of curious to know more about a specific case you're talking about. so, if i understand correctly: you have embeddings $X$, $Y_1$, $Y_2$, ... and you have a priori knowledge that all $Y_i$ have the same orientation (how? omni?). then you first align $X$ and $Y_1$ to learn a transformation $Q$ (say it's linear), and obtain $Y_1' = Y_1 Q$. but then reuse it as $Y_i' = Y_i' Q$? how often do you have a setting of this sort? if often - then i'd say it is a strong argument against 3, unless we also return an object of things (so 3+4 combined), and the function call would look like: `X_prime, Y_prime, dict_of_Q_objective_etc = seedless_procrustes(X, Y)` which is roughly similar to how scipy procrustes works, but to me this just looks messy.
> 
> i wasn't considering this sort of usage before. this fact, and the conversation in slack, make me lean towards having it as 1: a class with a fit and transform and an option to retrieve P or Q, objective function, etc. whenever possible. this is going to be my null, until/unless someone convinces me otherwise.

The use case is I have X and Y, and say for the first k rows X and Y are matched (known pairs) but for the rest they are not. So call the k x d matched portions of those matrices X' and Y'. I want to be able to learn an orthogonal matrix Q from X' and Y', say (with abuse of notation)

``procrustes.fit(X', Y')``

and then I want to get out my aligned, full version of Y by doing

``Y_transformed = procrustes.transform(Y)``

I am in favor of classes. These are literally transformers. Can learn a transformation on whatever data and then apply it to whatever data (including the train data) just like PCA, for instance. If that's all you want, `fit_transform` is your friend. if not, then not. Seems like the perfect use case for the estimator API to me. Any disagreements or are we on the same page?

**Comment by bdpedigo** [comment]
perhaps my example there is not the most common use case, but same deal for PCA, the most common use case is one data matrix and you fit and apply the same transformation. I don't think that's an undue burden on the user.

**Comment by alyakin314** [comment]
> > i'm kind of curious to know more about a specific case you're talking about. so, if i understand correctly: you have embeddings $X$, $Y_1$, $Y_2$, ... and you have a priori knowledge that all $Y_i$ have the same orientation (how? omni?). then you first align $X$ and $Y_1$ to learn a transformation $Q$ (say it's linear), and obtain $Y_1' = Y_1 Q$. but then reuse it as $Y_i' = Y_i' Q$? how often do you have a setting of this sort? if often - then i'd say it is a strong argument against 3, unless we also return an object of things (so 3+4 combined), and the function call would look like: `X_prime, Y_prime, dict_of_Q_objective_etc = seedless_procrustes(X, Y)` which is roughly similar to how scipy procrustes works, but to me this just looks messy.
> > i wasn't considering this sort of usage before. this fact, and the conversation in slack, make me lean towards having it as 1: a class with a fit and transform and an option to retrieve P or Q, objective function, etc. whenever possible. this is going to be my null, until/unless someone convinces me otherwise.
> 
> The use case is I have X and Y, and say for the first k rows X and Y are matched (known pairs) but for the rest they are not. So call the k x d matched portions of those matrices X' and Y'. I want to be able to learn an orthogonal matrix Q from X' and Y', say (with abuse of notation)
> 
> `procrustes.fit(X', Y')`
> 
> and then I want to get out my aligned, full version of Y by doing
> 
> `Y_transformed = procrustes.transform(Y)`
> 
> I am in favor of classes. These are literally transformers. Can learn a transformation on whatever data and then apply it to whatever data (including the train data) just like PCA, for instance. If that's all you want, `fit_transform` is your friend. if not, then not. Seems like the perfect use case for the estimator API to me. Any disagreements or are we on the same page?

okay, so I agree in general agree with this approach. let's settle on this.

here is one question: currently all of our existig transformers are fit to two sets of data, but only actually transform one of them (in your example Y). it is possible to imagine some that would transform both. a simple example would be a sign flip, if it is done in carey's form, where everything is brought to first orthant. furthermore, the methods used in semipar in theory can match Y to X, but it probably makes more sense, if, say the diagonal-rotation, instead projects both embeddings onto a sphere.

i've been thinking about what's the most sensible API to handle this, and most options seem weird. i don't want the API between the transformers that mess with one to be incompatible with ones that mess with both.

here is the best i came up with so far: make X the one which is always transformed (the opposite from scipy's procrustes), and have Y optional. so if only one is transformed, this is legal:

```
procrustes.fit(X', Y')
X_transformed = procrustes.transform(X, Y=None) 
```
but so is:
```
procrustes.fit(X', Y')
X_transformed, Y_transformed = procrustes.transform(X, Y=Y) 
```
even though `Y_transformed == Y` is true.

but when both are transformed, one either has to do this:
```
procrustes.fit(X', Y')
X_transformed, Y_transformed = procrustes.transform(X, Y) 
```
or we allow to only pass X, but throw a warning? or no warning? or, I can even make X and Y both optional (but obviously break if neither is provided). 

fit_transform always returns both of 'em to be universally consistent.

anyway, the reason why i think X is the one always transformed is so that it can be passed positionally.
