### ISSUE TITLE
fix AutoGMM to only run agglomerative clustering once

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#371]
agglomerative part is deterministic, doesn't need to run every value of k

**Comment by bdpedigo** [comment]
@asaadeldin11 we should talk about this, I think it's probably necessary for #306

**Comment by bdpedigo** [comment]
going to assign you for now @asaadeldin11 just because i think this is necessary for #306 so I don't want anyone else to take it. but let's talk at some point

**Comment by tliu68** [comment]
I'm interested in taking this one.

**Comment by bdpedigo** [comment]
high level pseudocode 
- run agglomerative with all options for the smallest `n_components`
   - from this we can also extract labels for the non-smallest `n_components` because of the hierarchical nature of `Agglomerative` (@tliu68 called this `_hierarchical_labels()` in her code)
- make a list of params combining GM and Agg - so gm params cross agglomerative params/models
- dispatch (possibly in parallel) to a bunch of GaussianMixtures (slightly modified with the regularization increasing stuff) and fit them initialized by Agg/kmeans
