### ISSUE TITLE
Latent{Distribution, Position}Test should be a function

### ISSUE THREAD

**Issue by alyakin314** [microsoft/graspologic#375]
splitting out from #370, since making the tests into functions is a separate issue from allowing 0 as number of permutations.

**Comment by alyakin314** [comment]
one thing to consider is whether the nonpar should eat graphs or embeddings (or either?). i occasionally find myself in the need of having to use it on the latter, and my workaround has been to go into source code and comment out the embedding, which is suboptiomal at best.

**Comment by bdpedigo** [comment]
@alyakin314 a few comments: 
- talked to MSR engineers today, don't think we should wait for progress with merging to do this. We can set whatever API makes the most sense on our own, and then pass it off to whatever repo (possibly with a few cosmetic changes, but likely not much)
- I agree that these algos should be able to eat embeddings. Another option would be to allow a user to pass in an `embed_kws` dict but I hesitate to do that till we have a good use case for that. 
- Possible APIs: 
    1. classes, like they are now
    2. functions that return some kind of result object
    3. functions that return pval, tstat, and dictionary of anything else. 
My current preference, though I could be convinced otherwise, is to go with 3. I think this matches API of other tests better, I haven't been able to think of a use case where one needs to take the test object, modify it, and call another method. And there's not that much data to keep track of. It would also alleviate issues we talked about in #380 which would take more restructuring to fit if we keep as a class. 

Lmk your thoughts, I see this as one of the main tasks we can get done on our own while we wait for the merger into Microsoft to really happen

**Comment by bdpedigo** [comment]
w.r.t. bullet point 2, I don't want that to hold anything up as far as the API goes. Can always add that in later no matter what we choose

**Comment by alyakin314** [comment]
- the nonpar test paper has << 100 citations, so it would be uneasy to pass it off to another repo any time soon. furthremore, we import hyppo, which imports joblib and other things, so we are significantly higher level than that allowed of scipy, and maybe even sklearn. this is just something to keep in mind.
- Youngser said that he'd also prefer using embeddings to be an option, by the way. i agree that hypothetically allowing to parametrize every step of the embedding and passing them as kwargs achieves the same job, but that just feels like an overcomplication stemmed from holding onto how we implemented it originally and keeping it consistent with lpt. i probably wouldn't even mind if eating embeddings would be the only option, because anything we include to embed can be done in a couple of other calls. on the other hand, people less familiar with graphs might want to get away with just a single function call if they have little idea of what's going on.
- notes on possible API's: 
  - im strongly leaning towards it being a function, but not settled on the return type.
  - if by return object you mean a custom thing with methods (so that we would end up with the same thing we usually call `ldt`, but instead of a user explicitly instantiating it, it would be done internally), i strongly oppose it. whereas, if by return object you mean a dict-like thing, then the named tuples that you hate so much actually cover your bullet points 2 and 3, because you can both assign them as `p_value, stat, _ = `, or extract as `object['p_value']`.
  - i am not yet fully sold that we should always return all three. 
  - also, something i want to mention is - i highly discourage anyone to use the statistic obtained from nonpar for anything, other than comparing it with statistics generated from the permutation of the same sample. so obtaining the p-value or plotting the null and the sample stat is okay, but using it for clustering, graph matching, etc. is most likely wrong. that's especially important if the backend test is done via exact equivalence, but really, it is almost always true that comparing the stats between two pairs of graphs is apples to oranges.
  - i wanted to ask you something regarding this: i believe you once sent a python package that had a lot of hypothesis tests implemented in it to slack, many of those tests are transferred from R. i've been trying to find it either via google or slack search and have failed so far. you won't happen to remember what it's called?

**Comment by bdpedigo** [comment]
> * the nonpar test paper has << 100 citations, so it would be uneasy to pass it off to another repo any time soon. furthremore, we import hyppo, which imports joblib and other things, so we are significantly higher level than that allowed of scipy, and maybe even sklearn. this is just something to keep in mind.

I don't think we plan on exporting the inference stuff, this is the most graspy specific thing about the whole package IMO

> * Youngser said that he'd also prefer using embeddings to be an option, by the way. i agree that hypothetically allowing to parametrize every step of the embedding and passing them as kwargs achieves the same job, but that just feels like an overcomplication stemmed from holding onto how we implemented it originally and keeping it consistent with lpt. i probably wouldn't even mind if eating embeddings would be the only option, because anything we include to embed can be done in a couple of other calls. on the other hand, people less familiar with graphs might want to get away with just a single function call if they have little idea of what's going on.

Agree and agree. kwargs maybe someday, it is more complicated for sure. the one caveat is it probably makes more sense to go that route for the LPT because that test is doing repeated embedding calls, probably makes sense for all of them to use the same parameters. For LDT i have no issue with embeddings being passed.  

> * notes on possible API's:
>   
>   * im strongly leaning towards it being a function, but not settled on the return type.
>   * if by return object you mean a custom thing with methods (so that we would end up with the same thing we usually call `ldt`, but instead of a user explicitly instantiating it, it would be done internally), i strongly oppose it. whereas, if by return object you mean a dict-like thing, then the named tuples that you hate so much actually cover your bullet points 2 and 3, because you can both assign them as `p_value, stat, _ = `, or extract as `object['p_value']`.

I am ok with dict like thing, or tuple, including named tuples. What I meant was that some stuff in scipy returns a `result` object like this https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html not for stats specifically as far as I know. But this kind of thing is what I meant by returning a custom object, which I'm not a fan of. 

>   * i am not yet fully sold on the fact that we should always return all three.

thoughts on this scheme https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.multiscale_graphcorr.html

>   * also, something i want to mention is - i highly discourage anyone to use the statistic obtained from nonpar for anything, other than comparing it with statistics generated from the permutation of the same sample. so obtaining the p-value or plotting the null and the sample stat is okay, but using it for clustering, graph matching, etc. is most likely wrong. that's especially important if the backend test is done via exact equivalence, but really, it is almost always true that comparing the stats between two pairs of graphs is apples to oranges.

fair enough, maybe worth talking about in the docs someday

>   * i wanted to ask you something regarding this: i believe you once sent a python package that had a lot of hypothesis tests implemented in it to slack, many of those tests are transferred from R. i've been trying to find it either via google or slack search and have failed so far. you won't happen to remember what it's called?

I believe you mean this https://pingouin-stats.org/ i had to do some digging too. easy name to forget, lol

**Comment by alyakin314** [comment]
> > * the nonpar test paper has << 100 citations, so it would be uneasy to pass it off to another repo any time soon. furthremore, we import hyppo, which imports joblib and other things, so we are significantly higher level than that allowed of scipy, and maybe even sklearn. this is just something to keep in mind.
> 
> I don't think we plan on exporting the inference stuff, this is the most graspy specific thing about the whole package IMO

agreed.

> > * Youngser said that he'd also prefer using embeddings to be an option, by the way. i agree that hypothetically allowing to parametrize every step of the embedding and passing them as kwargs achieves the same job, but that just feels like an overcomplication stemmed from holding onto how we implemented it originally and keeping it consistent with lpt. i probably wouldn't even mind if eating embeddings would be the only option, because anything we include to embed can be done in a couple of other calls. on the other hand, people less familiar with graphs might want to get away with just a single function call if they have little idea of what's going on.
> 
> Agree and agree. kwargs maybe someday, it is more complicated for sure. the one caveat is it probably makes more sense to go that route for the LPT because that test is doing repeated embedding calls, probably makes sense for all of them to use the same parameters. For LDT i have no issue with embeddings being passed.

could you elaborate on repeated embedding calls? i found a total of 1:
https://github.com/neurodata/graspy/blob/0f4441ddc8dc09840147fed0f33f7c6be2dedb30/graspy/inference/latent_position_test.py#L206

> > * notes on possible API's:
> >   
> >   * im strongly leaning towards it being a function, but not settled on the return type.
> >   * if by return object you mean a custom thing with methods (so that we would end up with the same thing we usually call `ldt`, but instead of a user explicitly instantiating it, it would be done internally), i strongly oppose it. whereas, if by return object you mean a dict-like thing, then the named tuples that you hate so much actually cover your bullet points 2 and 3, because you can both assign them as `p_value, stat, _ = `, or extract as `object['p_value']`.
> 
> I am ok with dict like thing, or tuple, including named tuples. What I meant was that some stuff in scipy returns a `result` object like this https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html not for stats specifically as far as I know. But this kind of thing is what I meant by returning a custom object, which I'm not a fan of.

yeah, not a fan of this either. feels like a clunky intermediate between a dict and an sklearn object.

> > * i am not yet fully sold on the fact that we should always return all three.
> 
> thoughts on this scheme https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.multiscale_graphcorr.html

will address this in a little bit.

> > * also, something i want to mention is - i highly discourage anyone to use the statistic obtained from nonpar for anything, other than comparing it with statistics generated from the permutation of the same sample. so obtaining the p-value or plotting the null and the sample stat is okay, but using it for clustering, graph matching, etc. is most likely wrong. that's especially important if the backend test is done via exact equivalence, but really, it is almost always true that comparing the stats between two pairs of graphs is apples to oranges.
> 
> fair enough, maybe worth talking about in the docs someday

sure.

> > * i wanted to ask you something regarding this: i believe you once sent a python package that had a lot of hypothesis tests implemented in it to slack, many of those tests are transferred from R. i've been trying to find it either via google or slack search and have failed so far. you won't happen to remember what it's called?
> 
> I believe you mean this https://pingouin-stats.org/ i had to do some digging too. easy name to forget, lol

yeah, this one. thanks a lot; should be easier to find given how many things they have implemented.

**Comment by alyakin314** [comment]
**scipy:**
statistic + p_value
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_1samp.html#scipy.stats.ttest_1samp
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html#scipy.stats.ttest_ind
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind_from_stats.html#scipy.stats.ttest_ind_from_stats
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_rel.html#scipy.stats.ttest_rel
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chisquare.html#scipy.stats.chisquare
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.power_divergence.html#scipy.stats.power_divergence
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kstest.html#scipy.stats.kstest
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_1samp.html#scipy.stats.ks_1samp
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_2samp.html#scipy.stats.ks_2samp
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.epps_singleton_2samp.html#scipy.stats.epps_singleton_2samp
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mannwhitneyu.html#scipy.stats.mannwhitneyu
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ranksums.html#scipy.stats.ranksums
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wilcoxon.html#scipy.stats.wilcoxon
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kruskal.html#scipy.stats.kruskal
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.friedmanchisquare.html#scipy.stats.friedmanchisquare
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.brunnermunzel.html#scipy.stats.brunnermunzel
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.combine_pvalues.html#scipy.stats.combine_pvalues (not a test tho)
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.jarque_bera.html#scipy.stats.jarque_bera
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ansari.html#scipy.stats.ansari
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.bartlett.html#scipy.stats.bartlett
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.levene.html#scipy.stats.levene
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.shapiro.html#scipy.stats.shapiro
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fligner.html#scipy.stats.fligner
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mood.html#scipy.stats.mood
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.skewtest.html#scipy.stats.skewtest
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kurtosistest.html#scipy.stats.kurtosistest
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.normaltest.html#scipy.stats.normaltest
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html#scipy.stats.pearsonr
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.spearmanr.html#scipy.stats.spearmanr
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pointbiserialr.html#scipy.stats.pointbiserialr
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kendalltau.html#scipy.stats.kendalltau
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.weightedtau.html#scipy.stats.weightedtau
32/38

only p-value:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.binom_test.html#scipy.stats.binom_test
1/38

stat+p_value+something else:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.median_test.html#scipy.stats.median_test
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.linregress.html#scipy.stats.linregress (but it's not really a test)
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.multiscale_graphcorr.html#scipy.stats.multiscale_graphcorr
3/38

something weird:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.anderson.html#scipy.stats.anderson
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.anderson_ksamp.html#scipy.stats.anderson_ksamp
2/38

**statsmodels:** (may have missed a couple here)
statistic+p_value:
https://www.statsmodels.org/stable/generated/statsmodels.stats.stattools.omni_normtest.html#statsmodels.stats.stattools.omni_normtest
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.compare_cox.html#statsmodels.stats.diagnostic.compare_cox (unless provided an argument, and then returns something else)
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.compare_j.html#statsmodels.stats.diagnostic.compare_j (unless provided an argument, and then returns something else)
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.linear_harvey_collier.html#statsmodels.stats.diagnostic.linear_harvey_collier
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.linear_rainbow.html#statsmodels.stats.diagnostic.linear_rainbow
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.normal_ad.html#statsmodels.stats.diagnostic.normal_ad
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.kstest_exponential.html#statsmodels.stats.diagnostic.kstest_exponential
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.kstest_fit.html#statsmodels.stats.diagnostic.kstest_fit
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.kstest_normal.html#statsmodels.stats.diagnostic.kstest_normal
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.lilliefors.html#statsmodels.stats.diagnostic.lilliefors
https://www.statsmodels.org/stable/generated/statsmodels.sandbox.stats.runs.mcnemar.html#statsmodels.sandbox.stats.runs.mcnemar
https://www.statsmodels.org/stable/generated/statsmodels.sandbox.stats.runs.runstest_1samp.html#statsmodels.sandbox.stats.runs.runstest_1samp
https://www.statsmodels.org/stable/generated/statsmodels.sandbox.stats.runs.runstest_2samp.html#statsmodels.sandbox.stats.runs.runstest_2samp
https://www.statsmodels.org/stable/generated/statsmodels.sandbox.stats.runs.cochrans_q.html#statsmodels.sandbox.stats.runs.cochrans_q
https://www.statsmodels.org/stable/generated/statsmodels.stats.descriptivestats.sign_test.html (docs says it only returns p-value, but i ran it before and it gives the stat)
15 / 28

statistic+critical_value:
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.breaks_hansen.html#statsmodels.stats.diagnostic.breaks_hansen
1 / 28

statistic+p-value+something else:
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.acorr_ljungbox.html#statsmodels.stats.diagnostic.acorr_ljungbox
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.acorr_lm.html#statsmodels.stats.diagnostic.acorr_lm
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.breaks_cusumolsresid.html#statsmodels.stats.diagnostic.breaks_cusumolsresid
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.het_arch.html#statsmodels.stats.diagnostic.het_arch
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.het_breuschpagan.html#statsmodels.stats.diagnostic.het_breuschpagan (specifically statistic+p_value for one test, and statistic+p_value for another test)
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.het_goldfeldquandt.html#statsmodels.stats.diagnostic.het_goldfeldquandt
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.het_white.html#statsmodels.stats.diagnostic.het_white  (specifically statistic+p_value for one test, and statistic+p_value for another test)
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.spec_white.html#statsmodels.stats.diagnostic.spec_white (stat+pvalue+dof)
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.linear_lm.html#statsmodels.stats.diagnostic.linear_lm (specifically statistic+p_value for one test, and results tuple for another test)
https://www.statsmodels.org/stable/generated/statsmodels.sandbox.stats.runs.symmetry_bowker.html#statsmodels.sandbox.stats.runs.symmetry_bowker (stat+pvalue+dof)
https://www.statsmodels.org/stable/generated/statsmodels.sandbox.stats.runs.median_test_ksample.html#statsmodels.sandbox.stats.runs.median_test_ksample (huh?)
11 / 28

something weird:
https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.linear_reset.html#statsmodels.stats.diagnostic.linear_reset
1 / 28

afore mentioned pinguin always returns a dataframe. not a fan. prob needs not any further discussion.

**Comment by alyakin314** [comment]
i've looked through scipy and statsmodels, as you see above. most tests only return statistic+p_value, but they don't really have much else to return , to be fair. maybe degrees of freedom, but not returning that is a small loss compared to having interchangeable syntax. unlike us, where having an access to the null distribution seems important. 

a couple of statsmodel things have variable output, and none of scipy. for some reason, i expected this to be more prevalent, probably because i've seen this approach in sorting or something like that. i guess people share Dwayne's concerns about variable output lengths.

with this in mind, i now do not mind having it as

`stat, p_value, dict_of_things = latent_distribution_test(X, Y, **kwargs)`

what goes into dict_of_things other than the null distirbution? d_hat? matrix Q if alignment was performed? what else?

**Comment by bdpedigo** [comment]
> could you elaborate on repeated embedding calls? i found a total of 1:

this one is in a for loop 
https://github.com/neurodata/graspy/blob/0f4441ddc8dc09840147fed0f33f7c6be2dedb30/graspy/inference/latent_position_test.py#L137

**Comment by bdpedigo** [comment]
> what goes into dict_of_things other than the null distirbution? d_hat? matrix Q if alignment was performed? what else?

number of fitted components, since that could have been `None` from the user? 

Can't think of anything else off of the top of my head.

**Comment by bdpedigo** [comment]
i have no objection to 
`stat, p_value, dict_of_things = latent_distribution_test(X, Y, **kwargs)`

**Comment by alyakin314** [comment]
> > what goes into dict_of_things other than the null distirbution? d_hat? matrix Q if alignment was performed? what else?
> 
> number of fitted components, since that could have been `None` from the user?
> 
> Can't think of anything else off of the top of my head.

this is what i mean by d_hat

**Comment by alyakin314** [comment]
possibly embeddings themselves? why not?

**Comment by alyakin314** [comment]
> > could you elaborate on repeated embedding calls? i found a total of 1:
> 
> this one is in a for loop
> https://github.com/neurodata/graspy/blob/0f4441ddc8dc09840147fed0f33f7c6be2dedb30/graspy/inference/latent_position_test.py#L137

u're very much right. don't know how i missed that boi. i'll think about it.

**Comment by alyakin314** [comment]
> i have no objection to
> `stat, p_value, dict_of_things = latent_distribution_test(X, Y, **kwargs)`

neither do i, so let's settle on this.

**Comment by alyakin314** [comment]
@bdpedigo i actually don't mind delegating this to ndd.

**Comment by bdpedigo** [comment]
@kareef928 wanna do this?

**Comment by kareef928** [comment]
Sure, might need some guidance to figure out what exactly I'm doing.

**Comment by alyakin314** [comment]
> Sure, might need some guidance to figure out what exactly I'm doing.

Allow me to try to summarize concisely, and if that doesn’t make sense - we can talk more (or you can discuss with Ben).

Currently, both LDT and LPT are classes, like in sklearn. They use fit and predict. But in practice, they are most commonly just used once (in fact, in some cases they might break if reused). And none of their internal attributes are really accessed either. So we want to change the API from
```
ldt = LatenentDistributionTest(**kwargs)
p_value = ldt.fit_predict(X, Y)
```
to

`p_value, test_statistic, dict_of_other_things = latent_distribution_test(X, Y, **kwargs)`

all internals would stay the same, they just have to be refactored majorly because they’d happen linearly as a function, rather than in init, then fit, then predict. Does that clarify things?

**Comment by kareef928** [comment]
That makes sense, I think it'll be feasible.

**Comment by kareef928** [comment]
Dod: latent_position_test, latent_distribution_test functions will be made. Documentation, tests, and tutorials for the latent position test and latent distribution test will be modified to address them being changed from a class to a function. To demonstrate the effectiveness of the implementation of the latent_position test_function, I will run the latent_position_test function in conjunction with the current implementation of the latent position test as a class. I will run both the function and the class by generating two graphs that are generated from the same latent position and on two graphs not generated from the same latent position, and demonstrate that similar p-values are obtained in both cases for both tests. The same applies for the latent distribution test, except the null distribution and test statistic will also be plotted along with the p-value, and these should be roughly the same in both cases for both tests.

**Comment by bdpedigo** [comment]
@kareef928 the above sounds great but would you mind making the above bullet points so it is easier to parse?
