### ISSUE TITLE
Merge pair/scatterplot with GMM ellipse plotting code 

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#382]
I have code to plot the ellipses from GMM on top of the data here
https://github.com/neurodata/maggot_models/blob/dev/notebooks/179.1-BDP-mb-clustering.py
for a 2-d scatterplot
Somewhere I also have it for pairplots. Would like this feature in graspy for viz purposes.

**Comment by dfrancisco1998** [comment]
I am interested!

**Comment by dfrancisco1998** [comment]
@bdpedigo in the comment above you say that code to plot ellipses on 2d data for pairplots somewhere. Could I have that link?

**Comment by dfrancisco1998** [comment]
DoD: produce a visualization of scatter plot and pairplot from graspy with the ellipsis (from GMM model) overlaid.   
I did not find any papers that have produced a pairplot with a GMM ellipse on it, so I will have to use the tutorial as my basis
I will do the same and base success off of being able to plot ellipse on a graph from the graspy tutorials

**Comment by bdpedigo** [comment]
https://github.com/neurodata/maggot_models/blob/a6ffe01110dd319b7763d4ba2e8c5fe3039357e7/notebooks/179.0-BDP-mb-clustering.py#L63

**Comment by bdpedigo** [comment]
`make_ellipses` is stolen/adapted from sklearn docs, you can look for that online

**Comment by dfrancisco1998** [comment]
Replacement DoD: inputs will be X (an array of data where each col corresponds to a feature), feature labels, a list of desired feature focus(so as to all high dimensional data still be graphed but not overwhelm the user), then create a pair plot and over graphs with scatter aspects plot ellipse. Output graph object.

**Comment by bdpedigo** [comment]
need more detail. this also has to take in a GMM object, for example? will we be able to specify colors for the points/ellipses? stuff like that

**Comment by bdpedigo** [comment]
note: would be cool if pairplot reduces to scatterplot where # dimensions = 2

**Comment by dfrancisco1998** [comment]
def pairplot_with_gmm_ellipse(
    X,
    gmm, 
    gmm_labels = True, 
    specific_features = None, 
    labels=None,
    col_names=None,
    title=None,
    legend_name=None,
    height=2.5,
    context="talk",
    font_scale=1,
    palette="Set1",
    alpha=0.7
):

- Creates a grid of scatterplots and histograms such that the on diagonal plots are histograms and the off-diagonal plots are scatterplots with gmm estimates ellipses. 
- The data on the scatterplot on the x-axis is given by the column of the outputted pair plot and the y-axis is given the row of the pair plot. 
- This will allow the user to view 2D relationships between all features(given by columns in original X) or only features of interest(by inputting a specific features list). 
- There will be a subsequent ellipse plotted on all scatterplots using a gmm classification. 
- Whether the coordinates are labeled as the what the gmm classifies them or as the user inputs will be based on whether gmm_labels(default is true) or whether labels is passed
-- if the user does not input labels then the default is to label points in scatter plot as gmm labels them
- Along the diagonal, there will be kernel density estimates(KDEs). Similar to the scatterplots, the KDEs will either plot the different KDE curves for each category within each feature categorized by labels or gmm_labels (depending on which one is passed in)
- By default, if X is 2 dimensions then only a scatterplot with gmm estimated ellipses will be drawn and point labeling similar to that above
