### ISSUE TITLE
Merge hierarchical clustering plotting code

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#383]
I have janky code to make figures like the one below showing a recursive clustering, with the option to color by some metadata or feature 
https://github.com/neurodata/maggot_models/blob/dev/src/visualization/dendrogram.py

@tliu68 may also have updated/modified versions of the above. 

Would like to have this as a function in Graspy, may be able to eat some specific form of hierarchical labeling, or, an HGMM model once we have #299

**Comment by tliu68** [comment]
I'm interested in taking this one.

**Comment by bdpedigo** [comment]
@tliu68 lmk if you do/don't plan on doing this still, either is fine with me! Just want someone in NDD to do it if you don't want to is all.
