### ISSUE TITLE
Merge new matrix plotting code

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#387]
I have been using code here
https://github.com/neurodata/maggot_models/blob/master/src/visualization/matrix.py
for plotting matrices and sorting by various metadata in various ways. 

May also want to merge this with seaborn clustermap functionality - a lot of what I have was pulled from there, in fact, but I'm unsure what makes the most sense in terms of implementation. 

Regardless, would like the following few features: 
- sorting a matrix rows and/or columns by categorical labels 
- sorting the categories themselves by some metadata 
- sorting items within categories by some metadata 
- coloring the borders of a matrix plot by some metadata 
- (possibly) showing a clustering of the rows or columns, like seaborn clustermap

**Comment by zeou1** [comment]
I'm interested in working on this

**Comment by zeou1** [comment]
@bdpedigo I an reading through the code from maggot_models. What do you suggest are some parts I should focus on? Thanks!

**Comment by bdpedigo** [comment]
the file that was linked in this issue.

here is a short demo i made. https://nbviewer.jupyter.org/github/neurodata/maggot_models/blob/dev/docs/matrix_plot_demp.ipynb 
I cant give you the data for that so you wont be able to run it, but you could make a fake adjacency matrix (numpy array) and pandas dataframe of metadata

**Comment by zeou1** [comment]
I've been trying to run the code from the Jupiter notebook, but it seems that the current code won't allow me to run it without "class_order" parameter. If I add a "class_order" parameter to the first plot code, I would encounter an error with pandas in the sort_meta function with the line "class_size = meta.groupby(sc).size()". However, the error should have nothing to do with my change tho.

**Comment by bdpedigo** [comment]
make sure you are using the code from the dev branch, that is the must current

i can't really help you debug with the information provided. 

regardless, i think the main point is for you to start getting a sense of the kinds of features that we want (I'd start a list of DODs for this issue, basically). Then we can talk about implementation (note: i pointed you to the code because it is a current working draft that works for me and does many of the functions I want. Don't necessarily need to follow that implementation)

**Comment by bdpedigo** [comment]
i'd also recommend getting familiar with [heatmap](https://seaborn.pydata.org/generated/seaborn.heatmap.html) and [clustermap](https://seaborn.pydata.org/generated/seaborn.clustermap.html)

much of what I wrote was wrapping those functions (heatmap) and some of the internal code is inspired by/stolen from clustermap

**Comment by zeou1** [comment]
DoD: Integrate the sorting categories, sorting items within a category, and sorting matrix rows/columns features into the current visualization methods. Create a new function to color the border of the plot according to the metadata. Create a new function to implement the Seaborn clustermap feature. Write documentations and tutorial notebooks.

**Comment by bdpedigo** [comment]
- add tests for all functionality
