### ISSUE TITLE
add option to concatenate directed embeddings before outputting

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#397]

**Comment by spencer-loggia** [comment]
I can take this one!

**Comment by spencer-loggia** [comment]
This can be handled in a variety of ways, so I'm hoping for some clarification on what's best.
For now, I am adding an optional `concat` parameter to `BaseEmbed.reduce_dim_`, which if true causes `latent_left` to be concatenated to `latent_right` along axis 0 for asymmetric adjacency matrices. The issue with this is that then the label of `latent_left` doesn't really reflect what's in that variable, but I think the other option is to add a concatenated matrix parameter. Let me know what would be better / if I'm think about this correctly!

**Comment by bdpedigo** [comment]
- you are correct that this probably makes the most sense in `BaseEmbed`
- we want to concatenate along axis 1, actually, to get a `(n, 2 * n_components)`shaped array out
- i hadn't thought much about the `latent_left` `latent_right` variables. I'd say for now, don't actually change any of the class attributes. just change what would be returned by `fit_transform`. @j1c let me know if you disagree, I just wanted to have some way of doing this because I so often do `np.concatenate((X, Y), axis=1)` and also because this is what topologic does by default so I'd like to as least have it in as an option going forward.

**Comment by j1c** [comment]
> * you are correct that this probably makes the most sense in `BaseEmbed`
> * we want to concatenate along axis 1, actually, to get a `(n, 2 * n_components)`shaped array out
> * i hadn't thought much about the `latent_left` `latent_right` variables. I'd say for now, don't actually change any of the class attributes. just change what would be returned by `fit_transform`. @j1c let me know if you disagree, I just wanted to have some way of doing this because I so often do `np.concatenate((X, Y), axis=1)` and also because this is what topologic does by default so I'd like to as least have it in as an option going forward.

Makes sense. Maybe set to True by default?

**Comment by spencer-loggia** [comment]
If set to true by default it will break a few lines of code in the current Embedding tutorials (and perhaps other code I don't know about yet). I can try to do it and resolve any issues if you want though.

**Comment by bdpedigo** [comment]
- im leaning towards `False` by default so we don't mess with any current behavior/tutorials for now, can always change later if we want
- @j1c thoughts on this being an argument to `fit_transform` vs `__init__`? (see #433). i guess my default was `__init__` just for sklearn consistency.

**Comment by j1c** [comment]
> * im leaning towards `False` by default so we don't mess with any current behavior/tutorials for now, can always change later if we want
> * @j1c thoughts on this being an argument to `fit_transform` vs `__init__`? (see #433). i guess my default was `__init__` just for sklearn consistency.

* Makes sense. We can do False by default
* Yea I was thinking part of `__init__`

**Comment by spencer-loggia** [comment]
Ok - I'll move the `concat` arg to init, the reason I had it in `fit_transform` was so that the behavior would be immediately clear in any code.

**Comment by alyakin314** [comment]
> If set to true by default it will break a few lines of code in the current Embedding tutorials (and perhaps other code I don't know about yet). I can do it and find / resolve any issues if you want though.

just fyi, it's used in Latent Distribution Test, and when the input is directed it catches it by identifying a tuple and concatenating "manually", so that's another place you'd have to change that.
