### ISSUE TITLE
Update setup.py to place upper bound on matplotlib

### ISSUE THREAD

**Issue by j1c** [microsoft/graspologic#423]
Add the same upper bound in `setup.py` (https://github.com/neurodata/graspy/blob/master/setup.py#L20) as in `requirements.txt` (https://github.com/neurodata/graspy/blob/master/requirements.txt#L6).

**Comment by loftusa** [comment]
I wonder whether it would be better to just write some code to directly send the lines in `requirements.txt` to `install_requires`. I think I came across some reason not to do that at some point, but I remember it seemed like a dumb reason to me at the time.

**Comment by j1c** [comment]
Keep them separate, and dont map them. `requirements.txt` can have comments.

**Comment by dwaynepryce** [comment]
An example of how we did this in topologic: https://github.com/microsoft/topologic/blob/dev/setup.py#L42-L59 and https://github.com/microsoft/topologic/blob/dev/requirements.txt

Basically, the required dependencies are in setup.py, and any extras you might need for, say, developing (or even if we wanted a full blown optional dependency chain for some reason)

This way you aren't as apt to make normal human mistakes like normal humans do

**Comment by bdpedigo** [comment]
closing as I think this is all in https://github.com/microsoft/graspologic/blob/dev/setup.cfg
