### ISSUE TITLE
limit max python version to 3.7

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#424]
from this discussion: https://github.com/neurodata/graspy/pull/421#issuecomment-686798821_

**Comment by bdpedigo** [comment]
may not end up being 3.7 specifically (see #277) but is probably a good idea generally

**Comment by loftusa** [comment]
> may not end up being 3.7 specifically (see #277) but is probably a good idea generally

Ok cool, see the fix in #421. We have to keep updating micro version numbers to change the upper bound with that way of implementing though

**Comment by dwaynepryce** [comment]
I'm not convinced we want this - sure, it's good to know that we only test up to a certain point, but it may very well work fine.

Maybe better is to warn the user on install that we've only tested 3.6 and 3.7 and anything past that is buyer beware

**Comment by bdpedigo** [comment]
@dwaynepryce we know of some weird behavior in 3.8 and are trying to fix it (see #446) so hopefully this'll be a moot point. 

But, made me nervous having people run stuff willy-nilly if we haven't tested it, personally.

**Comment by dwaynepryce** [comment]
Agreed, but it's not our job to prohibit people, it's to enable them.  Our only responsibility are to the combinations of target environments we say we support - so eventually, Linux, MacOS, and Windows with python versions 3.6-3.8 on all of them.

Then those of us willing to fly by the seat of our pants with 3.9 onward can get an early look at how things behave without having to explicitly go into the code base and change some things.  

If we say "we're only committing to this set of OS + Python version", then others can risk it if they so see fit.  I don't see that as a bad thing, it's just not something we're actively supporting.  And we also get the benefit of getting bug reports from people using 3.9b or 3.10a or something and that's valuable too!

**Comment by bdpedigo** [comment]
i was more worried about the "silent bugs" where something in 3.8/3.9 doesn't work quite right but that behavior isn't obvious. Since I've had a few user just blindly pip install without looking at Readme which states what is explicitly supported, but I guess that's on them.

Im okay with closing this and just aggressively testing 3.8+ going forward

**Comment by bdpedigo** [comment]
closing as I think this is unnecessary now? @dwaynepryce or anyone else feel free to open again if I am wrong but I think we're testing on 3.8 and things are fine...
