### ISSUE TITLE
fix doc rendering in inference module reference

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#429]
A few render failures/issues: 
- [x] "parameters" under `fit_predict` for LPT renders weird
- [x] `input_graph` under `n_components` in LDT should be in ticks
- [x] `size_correction` under `pooled` in LDT should be in ticks
- [x] "returns" under `fit_predict` for LDT renders weird

**Comment by alyakin314** [comment]
- [x] size_correction should have a space before :
