### ISSUE TITLE
Standardize Documentation Variable/Function Reference Formatting

### ISSUE THREAD

**Issue by pauladkisson** [microsoft/graspologic#441]
## Expected Behavior
The variables and functions referenced in the documentation should be enclosed in \` \` in order to distinguish them from normal text. For example, ``variable_1``

## Actual Behavior
Sometimes variables are referenced correctly.  Other times they are displayed with math type.  Other times still they are simply written in plain text.

## Template Code: Erdos-Renyi Model Tutorial
Both er_np and er_nm functions provide ways to sample weights for all edges that were sampled via a probability distribution function. In order to sample with weights, we provide a probability distribution function with corresponding keyword arguments for the distribution function.

**Comment by bdpedigo** [comment]
@pauladkisson it gets tricky, the sometimes we really do want to write out the math, and sometimes we want to write the variable... may be hard to tell the distinction at times, for instance, the example above. see what I mean?

**Comment by pauladkisson** [comment]
Ahhhh, I see what you mean.  ER(n, p) here is referring to the random graph model itself rather than the function in our code...
That definitely could get tricky.  I could just leave it be.

**Comment by bdpedigo** [comment]
I am sure in many places we are still not consistent, though, so don't want to discourage you from taking this on. But just warning that if we do, might need to discuss where the difference is intentional or not

**Comment by pauladkisson** [comment]
Yeah, like later in the same tutorial it says:

Both er_np and er_nm functions provide ways to sample weights for all edges that were sampled via a probability distribution function. In order to sample with weights, we provide a probability distribution function with corresponding keyword arguments for the distribution function.

And those function names should be in \`\` right?

eg.
Both ``er_np`` and ``er_nm`` functions provide ways to sample weights for all edges that were sampled via a probability distribution function. In order to sample with weights, we provide a probability distribution function with corresponding keyword arguments for the distribution function.

**Comment by bdpedigo** [comment]
correct
