### ISSUE TITLE
Graspologic versioning

### ISSUE THREAD

**Issue by dwaynepryce** [microsoft/graspologic#453]
Graspy and topologic have divergent systems regarding materialization of the version number prior to publication.

Topologic publishes dev versions (e.g. 0.1.0dev123456789) to [PyPI](https://pypi.org/) on each merge to a dev branch so that they can be tested (and documentation verified) prior to a full release.  This is done automatically based on the [semver](https://semver.org/) provided in a file and the merge to the develop branch.

Upon merge into main, the `dev123456789` is dropped and an actual `0.1.0` version is published to pypi.org.

From what I can tell, Graspy's version is updated manually, and I actually am not sure how publish occurs - @bdpedigo, can you shed some light on the current process?

Regardless, it's not a bad idea to publish our pre-releases as long as they're clearly defined as pre-releases, and we also want to minimize the manual steps required in favor of CICD just to minimize the human element (namely, the human element of forgetting to do something).

**Comment by bdpedigo** [comment]
i am happy to have the topologic way, that seems really nice

For graspy we were setting versions manually, tagging a release, and that would get pushed to PyPI by travis I believe - right @j1c ?

**Comment by j1c** [comment]
> i am happy to have the topologic way, that seems really nice
> 
> For graspy we were setting versions manually, tagging a release, and that would get pushed to PyPI by travis I believe - right @j1c ?

Yup this is all correct. I am also happy to do it the topologic way.

**Comment by dwaynepryce** [comment]
I know there was an Azure Devops action to help with version numbers but I still don't know it's going to give us the flexibility we want.  I'll look into it again to see if it gives us enough, maybe we can simplify the topologic stuff.

The main thing I want to achieve is:
- you should have a reasonable version if you're using a python interpreter in the project root directory (i.e. you just cloned it, created a venv, installed deps, and now are working inside of it - __version__ should be accurate for you too)
- you should have a reasonable version if you run your own `pip install .` from the root dir (note this executes setup.py)
- you should have a version that is clearly prerelease from `dev` being published to pypi
- you should have a version that is clearly a "real" release from `main` being published to pypi

Topologic currently has all of those, and it hits all possible (I think!) use cases

**Comment by dwaynepryce** [comment]
This is completed in PR #467.  I would also submit that there could be enhancements.
