### ISSUE TITLE
Build pipeline for graspologic

### ISSUE THREAD

**Issue by dwaynepryce** [microsoft/graspologic#455]
We need to build a new build pipeline for graspologic.

In general I prefer github actions, but Microsoft has some internal tools around dependency management/vetting/etc that are really useful, so it makes sense to build it for an Azure DevOps Pipeline.  This pipeline will have a yaml file checked into Github but the actual build for it will take place in a private Devops instance without public visibility into the runs.  

Things to ensure we do upon build:
- Run unit tests
- Run unit test coverage
- Run mypy 
- Run flake8 or black - we should have a discussion on what black offers (I'm unfamiliar with it)
- Run sphinx with warnings set to fail the build

If those all succeed and it's a merge to dev, we also want to publish to pypi as a pre-release.

If those all succeed and it's a merge to main, we want to publish to pypi as a final release.  Maybe we can also figure out how to update our semver bugfix revision up one on a merge to main and submit it as an auto-created PR so we can accept that into dev asap with minimal human intervention.  Doing it via PR vs. trying to do it automatically means we can override the next version from a bugfix version to a minor release if we see the need.

Some niceties that can probably be broken out into a different process: it would be *awesome* if we could execute all of our tutorial jupyter notebooks and verify they work on each build.  It would likewise be awesome if we could store this output .ipynb file somewhere for pretty rendering of some sort, especially if we can make use of the built-in Github viewer (so we don't have to manage any of our own servers for it).

**Comment by bdpedigo** [comment]
> it would be awesome if we could execute all of our tutorial jupyter notebooks and verify they work on each build.

sphinx/netlify currently does this for us (as long as the notebooks don't have run cells in them prior to committing)

>  It would likewise be awesome if we could store this output .ipynb file somewhere for pretty rendering of some sort, especially if we can make use of the built-in Github viewer (so we don't have to manage any of our own servers for it).

i don't know if the above puts the static markdown/html anywhere. I do know how to do that from command line, locally, im sure that process could be automated. also unsure if this is necessary given the above?

**Comment by bdpedigo** [comment]
i find the github viewer is hit or miss (at times it looks great and is convenient, for larger notebooks it can puke)

**Comment by j1c** [comment]
> * Run flake8 or black - we should have a discussion on what black offers (I'm unfamiliar with it)

flake8 is a linter and just shows you where there are style issues. I dont think it autoformats anything. Black, on the other hand, is an autoformatter and automatically format files to conform to PEP8. See [here](https://black.readthedocs.io/en/stable/the_black_code_style.html). These two things can co-exist, but flake8 is _almost_ redundant if we use black.

> * Run sphinx with warnings set to fail the build

> Some niceties that can probably be broken out into a different process: it would be awesome if we could execute all of our tutorial jupyter notebooks and verify they work on each build. It would likewise be awesome if we could store this output .ipynb file somewhere for pretty rendering of some sort, especially if we can make use of the built-in Github viewer (so we don't have to manage any of our own servers for it).

Yes. The nbsphinx extension for sphinx will run and store outputs for notebooks. I see that the topologic just points to the folder in github with notebooks but doesn't appear to rerun them every build. I think it would be better to serve it on the documentation site like graspy did rather than having to deal with github rendering notebooks. Like @bdpedigo said, its a hit or miss when using github. Do you have an idea on where/how to host the documentation website?
 
Another potential step: we use codecov, which I personally think is very useful when writing code to see which parts are covered by my tests. I advocate for this addition in the pipeline (some sort of coverage testing. doesn't have to be codecov).

**Comment by dwaynepryce** [comment]
> flake8 is a linter and just shows you where there are style issues. I dont think it autoformats anything. Black, on the other hand, is an autoformatter and automatically format files to conform to PEP8. See here. These two things can co-exist, but flake8 is almost redundant if we use black.

That's fair, but in some ways it's nice to just use flake8 to bomb if there is a style issue and then the user can use black or whatever they want to do the formatting.

I'm only "pro" flake8 because I already know there are no downstream dependencies of it that are GPLv3, and I haven't done that diligence toward black yet.  I'll do that soon though - I'm totally open to it, just want to make sure we keep legal happy.

> Another potential step: we use codecov, which I personally think is very useful when writing code to see which parts are covered by my tests. I advocate for this addition in the pipeline (some sort of coverage testing. doesn't have to be codecov).

Fair, I'll edit my top issue to include code coverage too

**Comment by dwaynepryce** [comment]
I also want to make sure we run our tests on all of the OSes and versions of Python we support.  Getting #277 and #430 in is a super high priority for us because we use basically 3.8 only.  A few of us have even started using 3.9b so... yeah.  I'm going to push to be aggressive on supporting the latest pythons from 3.6 up!

**Comment by dwaynepryce** [comment]
in #468 @bdpedigo brought up the benefits of running the various steps (black, pytest, codecoverage, etc) separately so it's easy to see what failed.

This is a super valuable thing, but I think even in a single build pipeline we get each step printing in github's PR view.  I'm going to attach a screenshot of what it's doing for graspologic-native (still private until I figure out how to sign builds with MSFT's keys, but showing you this won't be a problem):

<img width="917" alt="Screen Shot 2020-09-17 at 9 39 04 AM" src="https://user-images.githubusercontent.com/899411/93500984-ac3cc480-f8c9-11ea-9b59-2c03cf47f123.png">

So in this screenshot each thing is a separate task.  So basically what I'll do when I create the build is force the build to fan-out with multiple executors for the things that are platform/version independent (black and sphinx and... maybe coverage?), then pytest we should def. run on the matrix of Python3.6-3.8 and macOS, Linux, Windows.  I think that should work well enough, right?

**Comment by bdpedigo** [comment]
sounds perfect to me

**Comment by dwaynepryce** [comment]
Closed by PR #471
