### ISSUE TITLE
Merge topologic partitioning

### ISSUE THREAD

**Issue by dwaynepryce** [microsoft/graspologic#457]
Topologic has a non-embedding based network partitioning API footprint we will want to port into graspologic.

The current API makes extensive use of the `python-louvain` library for community detection (which itself is an implementation of the Louvain community global partitioning algorithm).  It also contains a `component modularity`function that returns a map of each community's "portion" of the modularity value and a `modularity` function that sums these values for a total modularity value.

Special care should be taken when merging this to leave room for the `graspologic-native` Rust->Python implementation of the Leiden enhancements to the Louvain community global partitioning algorithm.

**Comment by bdpedigo** [comment]
merged by #578 (as far as i know)
