### ISSUE TITLE
Merge topologic `io` package

### ISSUE THREAD

**Issue by dwaynepryce** [microsoft/graspologic#458]
The topologic `io` package is an overengineered mess (submitter's note: I wrote it, I can describe it thus without hurting any feelings).

We need an io package (or some equivalent) to cover a number of cases:
- Load an edge list, either as directed or undirected
  - In the trivial case, there is precisely one entry in the file denoting the relationship between node `a` and node `b` with a single weight.
  - In the non trivial case, we have a pair of scenarios to contemplate: 
    - Does the last entry in the file between node `a` and node `b` mean it is the most accurate, and thus the weight takes precedence over any preceding weight?  We often load logs that tell you the current "weight" as the relationship is made, which means last should absolutely win.
     - If not, should the weights be summed on each new entry? We often load logs that have no weight at all, and the number of entries is our proxy for a weight.
- Load a bipartite graph (presume two entries with identity defined in column `a` as having a relationship together if they share another a value from a column `b`)

We also want to re-identify graphs from their string representations of nodes to an unsigned int and a dictionary of string -> int mapping.  This can help us drastically consolidate the memory footprint of our graph when loading them into a networkx graph, though this would make sense to be a separate enhancement/feature request as well.  In some ways it would be nice to have this at load time as well as just be able to convert an existing networkx graph, which is why I bring it up now.

**Comment by bdpedigo** [comment]
@dwaynepryce I'm trying to clean up issues, is this done? I thought we had finished with all "merge topologic into graspologic" things so please correct me if wrong!
