### ISSUE TITLE
Merge node2vec in

### ISSUE THREAD

**Issue by dwaynepryce** [microsoft/graspologic#460]
topologic contains node2vec embedding code we want to merge in.  In addition our default parameters are a bit wonky; we've had a request from Jonathan Larson to change the default settings to:

- window_size should be 2 instead of 10
- iterations should be 3 by default
- walk_length is usually set to 30

**Comment by bdpedigo** [comment]
Note: yesterday, we discussed refactoring/renaming the current `BaseEmbed` -> `BaseSpectralEmbed` (or something along those lines).

Maybe it even inherits from a new `BaseEmbed` that does really simple things or is just abstract. But not really sure how much can be shared between spectral and n2v
