### ISSUE TITLE
Only set required dependencies in setup.py

### ISSUE THREAD

**Issue by dwaynepryce** [microsoft/graspologic#466]
Keeping track of your dependencies in both setup.py and requirements.txt is error prone.  Luckily we have control over that by being able to specify our dependencies for graspologic in setup.py, as well as an extras we may need for development/documentation/whatever purposes in a separate extended section.

requirements.txt can then directly reference this by using the `-e .[devtools]` directive (presuming our extended section's label is 'devtools', that is).

**Comment by loftusa** [comment]
discussion in #423 and #421 maybe relevant here
