### ISSUE TITLE
Proposal: have black run prior to pytest in CI

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#468]
- People often forget to run black
- tests can take 15-20 mins sometimes
- only after this wait, black will run and fail
- then people realize, then they push blacked files
- then they have to wait another 15-20 for the tests again
- could have black run and then if it fails, stop pytest run on Travis or whatever CI we end up using

**Comment by bdpedigo** [comment]
@j1c @dwaynepryce any thoughts?

**Comment by dwaynepryce** [comment]
Ugh.  Meant to explicitly close in favor of #455 - we'll make sure black, sphinx, (eventually) mypy, and pytest all run in CI prior to PR being mergeable.  This gives the contributor quick feedback over what they need to do prior to a PR being in an acceptable state.

**Comment by bdpedigo** [comment]
regardless my question was 1.  just about the order in which checks get run and 2. (less importantly) whether to continue building if some of the check fail (my guess is we do want them to continue but just asking)

**Comment by bdpedigo** [comment]
actually a better solution altogether would be to have style/flake8/black be a separate check? since then right on the PR you could see if style=bad code=good?

**Comment by dwaynepryce** [comment]
That's a good note - let's move this conversation into #455 since that's where I'm going to be thinking about this (soon - like today soon)
