### ISSUE TITLE
Documentation Questions: release.rst

### ISSUE THREAD

**Issue by dwaynepryce** [microsoft/graspologic#478]
I'm updating all the naming stuff now (at least in a first pass), and I'm taking note of some of the places where the graspy approach differs from the topologic approach.  I am registering issues at each of these places so we can have a conversation about what our actual approach should be going forward and how best to execute a merger.

In this specific placeholder issue, I'm wanting to talk about the release.rst file and the sub releases files for each minor release.

**Comment by bdpedigo** [comment]
closing in favor of #721
