### ISSUE TITLE
Refactor LCC check and n_features_ attribute setting to BaseEmbed

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#485]
ASE/LSE fit have some redundant code that could be in base

see #462

**Comment by zeou1** [comment]
This might be a dumb question, but wouldn't the fit method in ASE/LSE overridden the fit method in base, and how would we implement an abstract method in base?

**Comment by bdpedigo** [comment]
it is possible to have a fit in base and call it using `super().method()`. idea would be to use that to take care of some of the redundant parts

**Comment by kareef928** [comment]
I'd be interested in this issue

**Comment by kareef928** [comment]
DoD:

- Put code that exists in ASE and LSE in Base

- Ensure correct functionality by running a simulation comparing the original ASE/LSE to the revised ASE/LSE and ensure that similar pairplots are generated

**Comment by bdpedigo** [comment]
great start kareef. over the week or two, need to specify what code there is that is redundant in this way.

**Comment by bdpedigo** [comment]
kareef can you remind me, is this an issue that should be assigned to you?

**Comment by kareef928** [comment]
@bdpedigo yup, I plan on working on this issue after finishing #112
