### ISSUE TITLE
Black should alphabetize imports

### ISSUE THREAD

**Issue by daxpryce** [microsoft/graspologic#490]
I assert `black` should alphabetize imports, especially like:

```python
from .foo import (
    baz,
    bar,
    sandwich,
    fingers,
)
```

Should be ordered as:

```python
from .foo import (
    bar,
    baz,
    fingers,
    sandwich
)
```

If it can't I'll get flake8 pulled in as well and have it balk at these too, even if it can't do the reordering for us like black can.

**Comment by loftusa** [comment]
https://pycqa.github.io/isort/docs/major_releases/introducing_isort_5/
maybe a solution too, has a `black` compatible mode

**Comment by alyakin314** [comment]
are we talking about imports within the same line or multiline imports as well? e.g. should
```
import numpy as np
from graspologic.inference import LatentDistributionTest
from graspologic.embed import AdjacencySpectralEmbed, LaplacianSpectralEmbed
```
become

```
from graspologic.embed import AdjacencySpectralEmbed, LaplacianSpectralEmbed
from graspologic.inference import LatentDistributionTest
import numpy as np
```
because personally i am more of a fan of imports that look like christmas tree and go from general (numpy as np, pandas as pd, etc.) to specific (from graspologic.embed import AdjacencySpectralEmbed, LaplacianSpectralEmbed). but that's just my 2 cents.

**Comment by loftusa** [comment]
> are we talking about imports within the same line or multiline imports as well? e.g. should
> 
> ```
> import numpy as np
> from graspologic.inference import LatentDistributionTest
> from graspologic.embed import AdjacencySpectralEmbed, LaplacianSpectralEmbed
> ```
> 
> become
> 
> ```
> from graspologic.embed import AdjacencySpectralEmbed, LaplacianSpectralEmbed
> from graspologic.inference import LatentDistributionTest
> import numpy as np
> ```
> 
> because personally i am more of a fan of imports that look like christmas tree and go from general (numpy as np, pandas as pd, etc.) to specific (from graspologic.embed import AdjacencySpectralEmbed, LaplacianSpectralEmbed). but that's just my 2 cents.

+1 on this, i'd like to see something that respects empty newlines when sorting imports
e.g.,
```
import numpy as np
from graspologic.inference import LatentDistributionTest
from graspologic.embed import AdjacencySpectralEmbed, LaplacianSpectralEmbed
```
becomes
```
from graspologic.embed import AdjacencySpectralEmbed, LaplacianSpectralEmbed
from graspologic.inference import LatentDistributionTest
import numpy as np
```
but
```
import numpy as np

from graspologic.inference import LatentDistributionTest
from graspologic.embed import AdjacencySpectralEmbed, LaplacianSpectralEmbed
```
would treat the numpy import and graspologic imports as separate groups and only sort within-group.

**Comment by alyakin314** [comment]
@loftusa yes, that me likes too.

**Comment by dwaynepryce** [comment]
> because personally i am more of a fan of imports that look like christmas tree and go from general (numpy as np, pandas as pd, etc.) to specific (from graspologic.embed import AdjacencySpectralEmbed, LaplacianSpectralEmbed). but that's just my 2 cents.

I agree, but if I pick either all alphabetization or no alphabetization I'm going to pick the former.  Still I'd rather figure out if we can make your suggestion the way we go.  I know IntelliJ will organize in that way - it'll put all your external dependencies from libraries at the top, organized alphabetically, and then your own package structure will come next - organized alphabetically.

**Comment by bdpedigo** [comment]
VS code also does this with the `sort imports` command and I love it. I believe it uses this under the hood https://pycqa.github.io/isort/

**Comment by bdpedigo** [comment]
oh i see that is same link as @loftusa

**Comment by daxpryce** [comment]
This has been added by requiring isort balking if it doesn't like the order
