### ISSUE TITLE
How to cite graspologic?

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#497]
We currently recommend citing the graspy paper, which now has a different name from the package itself, which could end up being confusing. 

Thoughts on what people should cite going forward?

**Comment by bdpedigo** [comment]
@jovo @j1c

**Comment by j1c** [comment]
publish graspologic in mloss? :)

**Comment by bdpedigo** [comment]
yeah, or JOSS. Not super opposed, we have added a decent amount of new stuff and major contributors 😄 

I wonder if we can get away with it though? but tbh having the package and paper have different names right now actually does feel like a problem.

in the meantime i wonder if it is better to point folks to the old paper or some Zenodo DOI...

**Comment by jovo** [comment]
i think citing the paper is fine.
we should have a zenodo doi too, which we can link.
names change, it is no big deal, we should document on website that this
used to be graspy.

when we add a bunch more new stuff, we can consider writing another paper

On Fri, Oct 2, 2020 at 9:52 AM Benjamin Pedigo <notifications@github.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
> yeah, or JOSS. Not opposed, we have added a decent amount of new stuff and
> major contributors 😄
>
> I wonder if we can get away with it though? but tbh having the package and
> paper have different names right now actually does feel like a problem.
>
> in the meantime i wonder if it is better to point folks to the old paper
> or some Zenodo DOI...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fgraspologic%2Fissues%2F497%23issuecomment-702746326&data=02%7C01%7Cjovo%40jhu.edu%7Cbba1326c00de48f399c608d866da66bb%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637372435493569105&sdata=XtFUomAJUOFyWewLoL%2F%2FOslQFtkZRmfgadwEaweM4Mk%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4SUUWXLRF62Y7XFIP3SIXLI3ANCNFSM4R4Y7S2Q&data=02%7C01%7Cjovo%40jhu.edu%7Cbba1326c00de48f399c608d866da66bb%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637372435493579100&sdata=mM1z6ryrUCIIj9m5UYozIlK0L8kZhmHnCSFNgUb%2F1Us%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time.
How can I do better? <https://forms.gle/iEad8byD89eTPdYx6>
