### ISSUE TITLE
Move mug2vec to embed module

### ISSUE THREAD

**Issue by j1c** [microsoft/graspologic#502]
- [ ] Move this file [`/graspologic/pipeline/mug2vec.py`](https://github.com/microsoft/graspologic/blob/dev/graspologic/pipeline/mug2vec.py) to [`/graspologic/embed/`](https://github.com/microsoft/graspologic/tree/dev/graspologic/embed)
- [ ] Change this from `..embed` to `.embed` once file is moved.
https://github.com/microsoft/graspologic/blob/13577bf3009a6367a385408c252728fab66320fb/graspologic/pipeline/mug2vec.py#L7
- [ ] Remove `/graspologic/pipeline/` folder entirely
- [ ] Add `mug2vec` to imports in the [`/graspologic/embed/__init__.py`](https://github.com/microsoft/graspologic/blob/dev/graspologic/embed/__init__.py) file
- [ ] Change imports from the test file  `graspologic.pipeline` to `graspologic.embed`
https://github.com/microsoft/graspologic/blob/13577bf3009a6367a385408c252728fab66320fb/tests/pipeline/test_mug2vec.py#L9
- [ ] Add the line `.. autoclass:: mug2vec` to the [`/graspologic/docs/reference/embed.rst`](https://github.com/microsoft/graspologic/blob/dev/docs/reference/embed.rst) under `.. autoclass:: MultipleASE`
- [ ] Remove `/graspologic/docs/reference/pipeline.rst` file
- [ ] Remove the line `pipeline` from [`/graspologic/docs/reference/index.rst`](https://github.com/microsoft/graspologic/blob/dev/docs/reference/index.rst)

**Comment by AnshuTrivedi** [comment]
@j1c  Please help me to understand more what have to do in this issue?
I want to work on it.

**Comment by j1c** [comment]
Hey @AnshuTrivedi! I updated the original post the include all the steps. I realized that this is a bit more involved in that it requires touching multiple files, but each step is very simple (moving files or adding/deleting 1 line from a file). I would suggest you make a commit for each bullet point.

Let me know if you have any other questions.

**Comment by AnshuTrivedi** [comment]
@j1c It is failing test throwing error as below.
Please  help me.

>  File "/home/runner/work/graspologic/graspologic/graspologic/embed/__init__.py", line 10, in <module>
    from .mug2vec import mug2vec
  File "/home/runner/work/graspologic/graspologic/graspologic/embed/mug2vec.py", line 7, in <module>
    from .embed import ClassicalMDS, OmnibusEmbed
ModuleNotFoundError: No module named 'graspologic.embed.embed'

**Comment by jovo** [comment]
@AnshuTrivedi Thanks so much for engaging, we really appreciate the effort you have put in to this, and hope you can continue to be a part of our community!
