### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by daxpryce** [microsoft/graspologic#504]
Add type hinting to everything and ensure mypy passes all tests.

**Comment by bdpedigo** [comment]
Added the good first issue label - if any newcomers are reading this, adding type hints to any functions/classes (doesn't have to be all of them!) would be much appreciated.

**Comment by vmdhhh** [comment]
@bdpedigo I will start with this if it's fine.

**Comment by dwaynepryce** [comment]
We have a TON of type hinting we need to do. There's a branch and open draft PR for it currently in #543. Before you start on this @vmdhhh, let me put a bow on that one as-is and then we'll actually create an issue per module, that way we don't have to worry about an all-or-nothing PR.  I'll try to get that done later today and send you a message when the new issues are up and ready for your review.  Thanks for your interest!

**Comment by bdpedigo** [comment]
> @bdpedigo I will start with this if it's fine.

Would definitely appreciate any help with this one, thanks for your interest @vmdhhh! Agree with @dwaynepryce 's message above, but once that is taken care of I think this is a great place to start making contributions.

**Comment by vmdhhh** [comment]
> 
> 
> We have a TON of type hinting we need to do. There's a branch and open draft PR for it currently in #543. Before you start on this @vmdhhh, let me put a bow on that one as-is and then we'll actually create an issue per module, that way we don't have to worry about an all-or-nothing PR. I'll try to get that done later today and send you a message when the new issues are up and ready for your review. Thanks for your interest!

Ok great :)

**Comment by dwaynepryce** [comment]
@vmdhhh I didn't get to this yesterday; I once again hope to do it today but I'll just let you know when I have. If it isn't done by Thursday, feel free to @ me and remind me I'm forgetting something :)

**Comment by vmdhhh** [comment]
@dwaynepryce Just a suggestion
Rather than creating issues per module, we can also modify the description of this issue and add checkmarks for each module.
And whoever picks a module can comment with the name to avoid rework, and we will have multiple PRs rather than a single big PR and then we can check out the modules from the description list which are merged.

**Comment by vmdhhh** [comment]
@dwaynepryce Reminder :p

**Comment by dwaynepryce** [comment]
I'm currently working on #627 and my worktree is in a ... well, a chaotic state.  As _soon_ as I wrap it up and push the branch I'll swap to the old one and get it updated with dev (there are doubtless going to be like a jillion conflicts and I don't want to push that off onto anyone else 😆 )

**Comment by dwaynepryce** [comment]
@vmdhhh the really good news is I only had ONE (!!) conflict, so this should be pushed up VERY shortly!

**Comment by dwaynepryce** [comment]
Okay, we're up to date!

**Comment by loribeiro** [comment]
Hello, I'd be very glad if I could help with this one! How is it being organized?

**Comment by dwaynepryce** [comment]
@loribeiro - thanks for your interest in helping out!  helping us out with chores like these helps a lot and we're deeply appreciative of your interest!

I think what we're going to do is the following:
- Post in PR #543 what module(s) you're working on (keep them small, one module per PR)
- Create a branch off of the `type-hint` branch
- Create a PR back to the `type-hint` branch and I will check off what module is completed.  I'm going to go into that PR and create a checklist of all the modules.
- Once all of those are done we'll do a final type-hint validation and merge back into dev.

I'll try to make it a point to keep `type-hint` up to date with any pushes to `dev` just so you guys don't have to do that as well or worry about conflicts.  It's bound to be error prone but if we can get this done in the next week or two we'll be past this and never have to worry about it again.

**Comment by bdpedigo** [comment]
> Hello, I'd be very glad if I could help with this one! How is it being organized?

Awesome, welcome @loribeiro. Let us know if there's anything that is unclear or if we can help in any way, we appreciate your interest! Note also that @vmdhhh expressed some interest, so you two might want to coordinate (probably easiest to split up the modules).

**Comment by loribeiro** [comment]
> @loribeiro - thanks for your interest in helping out! helping us out with chores like these helps a lot and we're deeply appreciative of your interest!
> 
> I think what we're going to do is the following:
> 
> * Post in PR #543 what module(s) you're working on (keep them small, one module per PR)
> * Create a branch off of the `type-hint` branch
> * Create a PR back to the `type-hint` branch and I will check off what module is completed.  I'm going to go into that PR and create a checklist of all the modules.
> * Once all of those are done we'll do a final type-hint validation and merge back into dev.
> 
> I'll try to make it a point to keep `type-hint` up to date with any pushes to `dev` just so you guys don't have to do that as well or worry about conflicts. It's bound to be error prone but if we can get this done in the next week or two we'll be past this and never have to worry about it again.

Thank you! I will be look into it as soon as I can
