### ISSUE TITLE
Leave deprecation of GraSPy warning and push to PyPI one last time 

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#506]
Want to leave some breadcrumbs about the name change for old users

**Comment by alyakin314** [comment]
[😢  ](https://www.shitpostbot.com/img/templates/one-last-ride-57c3330ae4226.jpeg) (clickable)

**Comment by loftusa** [comment]
> [😢 ](https://www.shitpostbot.com/img/templates/one-last-ride-57c3330ae4226.jpeg) (clickable)

my heart
