### ISSUE TITLE
look into sklearn preprocessing functions

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#52]
See if any of these could be useful for graphs

http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.QuantileTransformer.html#sklearn.preprocessing.QuantileTransformer

**Comment by j1c** [comment]
As alternative to PTR?

**Comment by bdpedigo** [comment]
Yes, Jovo mentioned quantile transform linked above but there are many others that use the same interface, could have a generic transformations class if there are enough of these that could be useful. Definitely log transform at least
