### ISSUE TITLE
can import sbm from two different places

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#524]
`from graspologic.models import sbm`
`from graspologic.simulations import sbm`

Both of these work. when we get sbm from simulations, it's (correctly) the function, but when we get it from models, it's the sbm module. This is confusing to a new user I think

**Comment by alyakin314** [comment]
#368

**Comment by bdpedigo** [comment]
the former is a file, just fyi.

**Comment by bdpedigo** [comment]
are you proposing changing the name of the file?

**Comment by loftusa** [comment]
maybe that'll cause more trouble than it's worth? I'm guessing this will just be fixed with #368

**Comment by bdpedigo** [comment]
one temporary measure could just be renaming the file in `.models` to something like "sbm_estimators.py" (adding good first issue label)

**Comment by rajpratyush** [comment]
@bdpedigo can i work on this??

**Comment by bdpedigo** [comment]
can ask @loftusa if he has a solution in mind

**Comment by rajpratyush** [comment]
@loftusa tell me your views on this

**Comment by loftusa** [comment]
@rajpratyush I agree with @bdpedigo 's idea about renaming the file in `.models`. Will have to be careful about making sure that everything else gets refactored properly, since I'm assuming a lot of files import it.

**Comment by rajpratyush** [comment]
@bdpedigo @loftusa  shall I work on it?

**Comment by loftusa** [comment]
> @bdpedigo @loftusa shall I work on it?

sure!

**Comment by rajpratyush** [comment]
I want to files that requires modification

**Comment by rajpratyush** [comment]
@loftusa need your guidance ?

**Comment by loftusa** [comment]
> @loftusa need your guidance ?

Sorry, I'm a little confused on what you mean by "I want to files that requires modification" - could you clarify?

**Comment by rajpratyush** [comment]
@loftusa no actually I forgot actually you told me some to clear off the branch after it gets merged due to my exams can you tell me that again?  I want to clear off the branch after pushing a PR.
