### ISSUE TITLE
email these people: https://jmlr.org/papers/v21/20-412.html

### ISSUE THREAD

**Issue by jovo** [microsoft/graspologic#528]
let's discuss possible synergies and merging opportunities so that we can work together to build a better open source community. 

maybe @bdpedigo can draft an email here, and cc all the relevant stake-holders?

**Comment by bdpedigo** [comment]
HI {developer names}, 

We saw your paper in JMLR-MLOSS on scikit-network, and we think it's great! By way of introduction, we are developers of [graspologic](https://github.com/microsoft/graspologic), which is a Python package with some similar goals (network data science, basically). Our package started as two packages: Graspy (developed at Johns Hopkins University/NeuroData lab) and topologic (developed at Microsoft Research). We recently merged the two because we felt like there was a lot of overlap in goals and we could work more efficiently together. 

If you're interested, we would love to set up a time to talk along these same lines - it would be awesome to figure out how to work together to create the best Python network data analysis ecosystem! 

Best, 
{us}

**Comment by jovo** [comment]
If you are interested, we'd love to set up a time to talk and see how we
can be more efficient and productive together.  For example, it seems that
you have already implemented some interesting sparse matrix factorization
algorithms that might be of interest to us, and we have implemented Leiden
which seems to be of interest to you.  It would be awesome...

On Wed, Oct 14, 2020 at 7:39 PM Benjamin Pedigo <notifications@github.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
> HI {developer names},
>
> We saw your paper in JMLR-MLOSS on scikit-network, and we think it's
> great! By way of introduction, we are developers of graspologic
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fgraspologic&data=04%7C01%7Cjovo%40jhu.edu%7Ce12b0516c2eb4f110bc708d8709a74d6%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637383155973412102%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Jfs%2FTI5oJWmgjDy1tnNqpQOZobQNMPyH8oaoFmaV11Y%3D&reserved=0>,
> which is a Python package with some similar goals (network data science,
> basically). Our package started as two packages: Graspy (developed at Johns
> Hopkins University/NeuroData lab) and topologic (developed at Microsoft
> Research). We recently merged the two because we felt like there was a lot
> of overlap in goals and we could work more efficiently together.
>
> If you're interested, we would love to set up a time to talk along these
> same lines - it would be awesome to figure out how to work together to
> create the best Python network data analysis ecosystem!
>
> Best,
> {us}
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fgraspologic%2Fissues%2F528%23issuecomment-708716505&data=04%7C01%7Cjovo%40jhu.edu%7Ce12b0516c2eb4f110bc708d8709a74d6%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637383155973412102%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ko%2BfK1mAFlrx52rpp1lZsevUEpPZ4%2Fdc4Kjv5%2Bll0XQ%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4VKVL4FCALTAFZCNXDSKYZETANCNFSM4SNBDXZA&data=04%7C01%7Cjovo%40jhu.edu%7Ce12b0516c2eb4f110bc708d8709a74d6%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637383155973412102%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2eZYFsOcGBpCeU6ukaS0jl4mwrNZtOm2%2BjpvthQIcVU%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time.
How can I do better? <https://forms.gle/iEad8byD89eTPdYx6>

**Comment by bdpedigo** [comment]
updated the above

**Comment by bdpedigo** [comment]
done
