### ISSUE TITLE
compare CASC to GraphSAGE on the experiments they performed in their papers

### ISSUE THREAD

**Issue by jovo** [microsoft/graspologic#536]
https://arxiv.org/pdf/1706.02216.pdf

**Comment by bdpedigo** [comment]
@jovo ndd appropriate?

**Comment by jovo** [comment]
Seems like it to me?
JL has graphsage working I understand.

On Wed, Oct 14, 2020 at 11:54 AM Benjamin Pedigo <notifications@github.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
> @jovo
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjovo&data=02%7C01%7Cjovo%40jhu.edu%7C2bfa7ba357ac4a67836708d870596638%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637382876548704559&sdata=4HXiXJ0uYXzuJervXDmdrKOn6r0znVZ2jMw7U3dAO7A%3D&reserved=0>
> ndd appropriate?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fgraspologic%2Fissues%2F536%23issuecomment-708495261&data=02%7C01%7Cjovo%40jhu.edu%7C2bfa7ba357ac4a67836708d870596638%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637382876548704559&sdata=dmwkuHglae6eS5zYndthL3MhI8SypBtb3FXfqHl%2Bwzw%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4RS2PL3FC2RMUUAUKLSKXCSFANCNFSM4SQYCUCQ&data=02%7C01%7Cjovo%40jhu.edu%7C2bfa7ba357ac4a67836708d870596638%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637382876548714549&sdata=fd9jU68w1cmLGMkEocb2wfKxLtragR1FRszmIYDcuD8%3D&reserved=0>
> .
>
-- 
Typed with thumbs

**Comment by spencer-loggia** [comment]
Possibly interested in this issue for sprint 2

**Comment by loftusa** [comment]
also interested in this for sprint 2

**Comment by bdpedigo** [comment]
@JonathanLarson do you have an implementation of GraphSage you like/use?

**Comment by zeou1** [comment]
I tried running the PPI dataset with the GraphSAGE [GitHub code](https://github.com/williamleif/GraphSAGE) by first running the unsupervised model and then the PPI logistic classificer, but it just outputs the F1 scores for each node in the test graph. The GitHub code does not seem immediately ready to be used to run the experiments as detailed in their paper, but I believe I can write a new Jupyter Notebook to run their model and then classify with my own code instead of theirs.

**Comment by zeou1** [comment]
Definition of Done (First Draft):

1. Write a Jupyter Notebook for the experiment to replicate the PPI dataset result in Table 1 of the paper
2. Do the same thing as step 1 but with CASC

I feel like the two steps above should be achievable within the time constraint of the NDD class, but I do welcome any feedback on this part.

**Comment by zeou1** [comment]
Are there other ways to compare the results of the experiments other than F1 scores? Or is the F1 score what we are looking for?
