### ISSUE TITLE
Add out-of-sample LSE

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#544]
see #161

**Comment by PerifanosPrometheus** [comment]
I may be interested in this one

**Comment by dtborders** [comment]
I am interested in this one as well

**Comment by loftusa** [comment]
@PerifanosPrometheus @dtborders let me know if either of you decide to do this, I have a pretty good idea of how it should happen at this point I think, just wanted to move on from oos stuff

**Comment by PerifanosPrometheus** [comment]
@dtborders It is all yours, have fun!

**Comment by dtborders** [comment]
@bdpedigo Could I be assigned to this one?

**Comment by dtborders** [comment]
Dod:

- Recreate Figure 1 from [this paper](https://arxiv.org/pdf/1802.06307.pdf) for this [code](https://github.com/neurodata/primitives-interfaces/tree/master/jhu_primitives/ooslse)
- Recreate the same figure with graspy with the OOS LSE I will add. If the figures have the same distributions, then the models are identical so we are good to go. 
- Modify Alex's relevant tests for OOS ASE to also test OOS LSE. Add any additional tests needed. 
- Create a tutorial notebook.
