### ISSUE TITLE
singular_values_ attribute needed for MultipleASE class

### ISSUE THREAD

**Issue by pauladkisson** [microsoft/graspologic#548]
## Expected Behavior
MultipleASE should have an attribute that stores singular values for ease of generating scree plots, consistent with the other embedding classes.  Specifically, it should output the singular values of the concatenated adjacency spectral embeddings, consistent with Figure 10 of the [paper](https://arxiv.org/pdf/1906.10026.pdf) where it is introduced.

## Actual Behavior
MultipleASE has no attribute for singular values.

## Template Code
N/A

## Full Traceback
N/A

## Your Environment
* Python version: 3.7.6
* graspologic version: 0.1.0

## Proposed Labels
 * Question

**Comment by bdpedigo** [comment]
@pauladkisson welcome to work on this if you run out of stuff to do this week before I get back to you, just FYI
