### ISSUE TITLE
Add LSE-OMNI

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#550]
Should be able to run OMNI where each individual matrix that is input is the Laplacian of each.

Theory/papers on it have not been published (to my knowledge) but has definitely been used successfully in the wild.

Maybe we want to include R-LSE as an option?

**Comment by bdpedigo** [comment]
@nyecarr fair to say this is desired, right?

**Comment by dwaynepryce** [comment]
Yeah, this is desired - we do use it semi-frequently.

**Comment by Nyecarr** [comment]
Yes, we use both LSE/ASE omni in several of our projects. After digging in and comparing topologic vs graspy, we reached out to Carey and it was confirmed that he agrees with our experience that it _is_ useful but it hasn't been published yet. 

It brings up some questions of LSE normalization and how to effectively do it as well as how to perform graph augmentations (ptr/cvec) in a reasonable way.

**Comment by zeou1** [comment]
I am interested in working on this issue for sprint 2

**Comment by zeou1** [comment]
Definition of Done:

1. Implement OMNI with Laplacian matrices as the input
2. Run experiments to visualize the difference between ASE and LSE OMNI?
3. Add LSE-OMNI to the current OMNI tutorial
