### ISSUE TITLE
Fix versioning file being committed with changes

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#554]
Many people are committing the modified `version.txt`

Would be nice to have this not happen

**Comment by dwaynepryce** [comment]
We shouldn't even have a version.txt file added to source, and should have a smarter version.py that knows how to deal with a non-existant file (it means the same as an empty file, so the logic to update isn't particularly hard)

**Comment by dwaynepryce** [comment]
https://setuptools.readthedocs.io/en/latest/pkg_resources.html#basic-resource-access

`resource_exists` should be checked first
