### ISSUE TITLE
Add tests from statistical connectomics / bilateral symmetry

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#570]
- homotypic tests
- different SBM block probability testing

**Comment by caseypw** [comment]
I think this issue is interesting, I would like to work on this

**Comment by dfrancisco1998** [comment]
I am also interested!

**Comment by CaseyWeiner** [comment]
# Sprint 2 D.o.D. (Definition of Done)
## Casey Weiner
DoDs are included below in **bold**.

### Preliminaries:
 - Read and take notes on [Statistical Connectomics Paper](https://osf.io/ek4n3/)
 - Fork [Connectocross](https://github.com/neurodata/connectocross)
 - **Commit notes to personal Connectocross fork**
 - Work with Spencer, Paul, and TAs to figure out procedure for working on Connectocross: ex push to someone's fork, make graspologic branch with help from admin, etc

### Main Goal
1. Work with Spencer and Paul on munging Connectocross data and writing functions to import the graphs.
    - Ideally be done with this before the start of next semester: **PR addressing issue**. Will talk to TAs this Wednesday about this.
    - Current workload breakdown: 
      - Spencer: [Issue 1](https://github.com/neurodata/connectocross/issues/1)
      - Paul: [Issue 2](https://github.com/neurodata/connectocross/issues/2)
      - Myself: [Issue 3](https://github.com/neurodata/connectocross/issues/3)

2. Implement Homotypic Tests and Different SBM Block Probability Testing into Graspologic
    - Core Code
    - Tutorials Notebooks
    - Unit Tests
    - Proof Notebook: Recreate figure from Statistical Connectomics Paper (discuss which figure with TAs in office hours this Wednesday)
    - Miscellaneous Docs Files
    - **Have this all PR'd to Graspologic with passing checks, ready to merge**

3. Use implemented code to test on Connectocross Data, write manuscript
    - Tests:
      - [Left/Right](https://github.com/neurodata/connectocross#leftright-sbmdcsbm)
      - [Left/Right + Metadata](https://github.com/neurodata/connectocross#leftright--any-known-metadata-sbmdcsbm)
      - [Homotypic Affinity](https://github.com/neurodata/connectocross#homotypic-affinity)
      - [Estimating SBM](https://github.com/neurodata/connectocross#spectral-clustering-and-estimating-an-sbm-dcsbm-ddsbm)
    - **Write about experiments above, submit to arxiv**
