### ISSUE TITLE
Adding different model selection criteria for GMM

### ISSUE THREAD

**Issue by hhelm10** [microsoft/graspologic#581]
## Is your feature request related to a problem? Please describe.
Currently, GMM returns the model that maximizes BIC. Sometimes it is desirable to have more expensive (i.e. more parameters) models. In these cases, less harsh parameter penalties should be used (i.e. AIC where the penalty is not a function of the number of parameters in the model).

## Describe the solution you'd like
Adding an keyword argument `penalty` (or something) to GMM fit function with BIC, AIC, etc as options and BIC as the default.

## Describe alternatives you've considered
None.

## Provide references (if applicable)
https://en.wikipedia.org/wiki/Akaike_information_criterion

## Additional context
None.

**Comment by bdpedigo** [comment]
https://graspy.neurodata.io/reference/cluster.html#graspologic.cluster.AutoGMMCluster `AutoGMM` has AIC (see `selection_criteria`. Is that enough or looking for something else? Or are you talking about `GaussianCluster`? If so, `GaussianCluster` will eventually be absorbed by `AutoGMM` (may change the names but that's the idea).

**Comment by hhelm10** [comment]
oh, thanks for pointing that out. not looking for anything else, just had forgotten about `AutoGMM`!

**Comment by bdpedigo** [comment]
yeah is somewhat confusing with the two classes as is. ideally someone will address in #306
