### ISSUE TITLE
Automate PRs being added to project board, maybe some of the other functions

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#584]
## Is your feature request related to a problem? Please describe.
No automation for PR organization system we have going now 

## Describe the solution you'd like
Automation 

## Provide references (if applicable)
Let's try this? https://github.com/philschatz/project-bot
At a bare minimum, can have PRs added to the project (and the needs triage column) as soon as they are opened
Can also define actions based on people being assigned review, accepting review, etc. that I think could help.

**Comment by rajpratyush** [comment]
@bdpedigo can I work on this??

**Comment by bdpedigo** [comment]
im not sure, may need some admin access to be able to set this stuff up.

**Comment by rajpratyush** [comment]
I think @dwaynepryce can clarify on this
