### ISSUE TITLE
Common functions in top-level namespace?

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#585]
It occurs to me that we might want to select some functions that we use all the time in analysis to move to the top-level namespace, similar the top-level objects in `numpy` and `pandas`.

This popped up when I wanted to make a Laplacian, and I felt like it would have been more convenient to write something like `graspologic.to_laplacian(A)` rather than importing from `utils`.

Many of the other functions in `utils` would be good candidates for this.

thoughts?

**Comment by bdpedigo** [comment]
last part sounds like a second issue IMO

**Comment by loftusa** [comment]
> last part sounds like a second issue IMO

good point, I'll refactor

**Comment by bdpedigo** [comment]
i havent seen any backing for this idea recently so im going to close for now, happy to revisit if there's momentum.
