### ISSUE TITLE
Look into spherical clustering more for DCSBM estimation

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#602]
See for example https://arxiv.org/pdf/2011.04558.pdf
Another approach is spherical k-means https://github.com/jasonlaska/spherecluster which I have played with a bit.

I think these make more sense than what we currently do.

**Comment by PerifanosPrometheus** [comment]
@bdpedigo  I may be interested in working on this one. Alternatively, I am also interested in #372. I would totally understand that given the limited time of the course and the nature of these experimental issues you would prefer if I worked on different issues. In which case I could take on #456

**Comment by bdpedigo** [comment]
closed as part of the PR referenced above
