### ISSUE TITLE
[BUG] Deprecation warning in AutoGMM

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#609]
## Expected Behavior
No warning

## Actual Behavior
Deprecation warning in `AutoGMM`

## Example Code
```
from graspologic.cluster import AutoGMM
```

## Full Traceback
```pytb
FutureWarning: The sklearn.utils.testing module is deprecated in version 0.22 and will be removed in version 0.24. 
The corresponding classes / functions should instead be imported from sklearn.utils. 
Anything that cannot be imported from sklearn.utils is now part of the private API.
```

## Solution 
Caused by https://github.com/microsoft/graspologic/blob/8d7d29f0e569de4b1969d3b1aed8d47168aa6a96/graspologic/cluster/autogmm.py#L14

Just need to replace that decorator with a simple 
```
with warnings.simplefilter('ignore', ConvergenceWarning):
```
(I think)

**Comment by darkyed** [comment]
Hi @bdpedigo ! I'm new to open source and I would like to work on this issue.

**Comment by bdpedigo** [comment]
🎉 Hi @darkyed, that is great to hear! Does the issue make sense? Is there anything you need from us to get started? We are happy to help you get going on this however we can.

The goal is basically to use Python's `warnings` package to suppress `ConvergenceWarnings` in the method `fit` of the class `AutoGMM`. Currently this was done by using some code from sklearn that was private and is no longer available to us, but we should just be using `warnings` to do this anyway.

Note: I am somewhat on vacation till Jan. 4th so may be slow to reply until then.

**Comment by bdpedigo** [comment]
> Hi @bdpedigo ! I'm new to open source and I would like to work on this issue.

@darkyed I am also curious how you found our project - we have recently been trying to encourage more open source contributions by adding ourselves to a few lists of "good first issues," just curious if you found the package that way or some other way. Thanks!

**Comment by jovo** [comment]
welcome @darkyed, happy to be working together!

**Comment by darkyed** [comment]
> 🎉 Hi @darkyed, that is great to hear! Does the issue make sense? Is there anything you need from us to get started? We are happy to help you get going on this however we can.
> 
> The goal is basically to use Python's `warnings` package to suppress `ConvergenceWarnings` in the method `fit` of the class `AutoGMM`. Currently this was done by using some code from sklearn that was private and is no longer available to us, but we should just be using `warnings` to do this anyway.
> 
> Note: I am somewhat on vacation till Jan. 4th so may be slow to reply until then.

Yes, I just wanted to ask a couple of things -

1. I did not find any context manager that goes like `with warnings.simplefilter():`. Instead, I used 
```python
with warnings.catch_warnings():
    warnings.simplefilter(action="ignore", category="ConvergenceWarning")
```

https://github.com/microsoft/graspologic/blob/8d7d29f0e569de4b1969d3b1aed8d47168aa6a96/graspologic/cluster/autogmm.py#L380-L381

2. I removed the above decorator as you said, and I have wrapped the code inside the method `_fit_cluster` with the code I mentioned in point 1, like so:

```python
def _fit_cluster(self, X, y, params):
    # ignoring warning here because if convergence is not reached, the regularization
    # is automatically increased
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", ConvergenceWarning)
            # code in the method . . .
```

I ran the tests using `pytest .\tests\cluster\test_autogmm.py` and it's working fine. 

Is it all good or do I need to change anything?

P.S. Also, how do I verify whether the deprecation warning is fixed now?

**Comment by darkyed** [comment]
> > Hi @bdpedigo ! I'm new to open source and I would like to work on this issue.
> 
> @darkyed I am also curious how you found our project - we have recently been trying to encourage more open source contributions by adding ourselves to a few lists of "good first issues," just curious if you found the package that way or some other way. Thanks!

Yes, I found it while looking for good-first issues.

**Comment by bdpedigo** [comment]
1. I think you are probably right!
2. Looks right at first glance

To verify that your fix works (at least for the deprecation warning part), you can just try importing the class and verify that the deprecation warning does not occur. If you don't mind, it would be good to test with both sklearn 0.24 and 0.23.

For testing the convergence warning suppression this is a bit trickier. I will have to find a good example where convergence does not occur.

**Comment by darkyed** [comment]
I verified by importing, there are no deprecation warnings raised during:
```python
>>> from graspologic.cluster import AutoGMMCluster
>>> cluster = AutoGMMCluster()
```
I checked this for both sklearn `0.24` and `0.23`.

Should I create a pull request now?

**Comment by bdpedigo** [comment]
That would be great!

**Comment by bdpedigo** [comment]
Let me know if you have any questions about the build checks and everything once you make the pull request

**Comment by darkyed** [comment]
I have created a PR at #620. Apparently, one test is failing. How should I proceed with this?
