### ISSUE TITLE
Seed automatic layout generation

### ISSUE THREAD

**Issue by dwaynepryce** [microsoft/graspologic#615]
So many parts of the layout generation process use random number generators behind the scenes. We should update our current algorithm to use a user provided seed so we can get deterministic output.

**Comment by vmdhhh** [comment]
I would like to contribute if it's ok.
Will you please direct me towards something @dwaynepryce ?

**Comment by bdpedigo** [comment]
@vmdhhh thanks for your interest! I can't speak to this particular issue, and the requisite code is not yet merged for this (see #611). I'll let @dwaynepryce weigh in if there are tasks for that that can be done already. 

In the meantime, we do have a label for [good first issue](https://github.com/microsoft/graspologic/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) if you just want to get started with any contribution. Welcome to look at those for ones which people aren't already doing.

**Comment by vmdhhh** [comment]
@bdpedigo Thanks for letting me know. 
I will look into good first issues :)

**Comment by dwaynepryce** [comment]
@vmdhhh we merged #611 in - if you want to pull latest from `dev` and take a look at where we'd need to pipe the seed down through the process, you can at any time! @bryantower and I are here if you have any questions for us about it, so let us know!

**Comment by bryantower** [comment]
As a place to start, random is used in a few places within the layout, I would start with the code in
graspologic/layouts/auto.py
specifically looking at layout_umap (line 97 currently) and layout_tsne (line 28 currently).  Then follow all of the methods through there to see where we may have used a random number and how we can seed the rng once before we start.

**Comment by vmdhhh** [comment]
@bryantower @dwaynepryce Thanks a lot for the input.
I will start looking into this :)

**Comment by vmdhhh** [comment]
Just to see If I am on the right track
I found that 
- `layout_tsne`  uses `TSNE` for dimensionality reduction where we can give `random_state`
- `layout_umap` uses UMAP, where there are two possibilities, one is `random_state` and another is `transform_seed`
Am I correct going down this path? @bryantower @dwaynepryce

**Comment by dwaynepryce** [comment]
I can't speak for TSNE/UMAP - @bryantower, I'm going to defer to you. 
 But in addition to those, we also have:

- node2vec at https://github.com/microsoft/graspologic/blob/dev/graspologic/layouts/auto.py#L209
- leiden at https://github.com/microsoft/graspologic/blob/dev/graspologic/layouts/auto.py#L226, where we can pass in a random state https://github.com/microsoft/graspologic/blob/dev/graspologic/partition/leiden.py#L101 as well.

I **think** those are all the places

**Comment by bryantower** [comment]
@vmdhhh, yes TSNE has the random_state, UMAP has two random seeds, the random_state, and the transform_seed.  There are also the the places that @dwaynepryce mentioned. To be complete all of those should be settable.

**Comment by vmdhhh** [comment]
@dwaynepryce @bryantower @bdpedigo 
Will you please have a look if the implementation is fine?
