### ISSUE TITLE
Audit docs for accessibility

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#617]
Related to #531

We've been discussing making the package more accessible, including the documentation. 

@rflperry took some notes on this process with regard to sphinx docs: https://github.com/microsoft/graspologic/issues/531#issuecomment-716203236

some possible concerns I thought we should look into (in reference to Ronan's points in the above): 
- we may have issues with colors and lack of color + non-color signaling in many figures in the docs. i suspect we could be far more consistent/color blind friendly with regard to color palettes across the tutorials.
- the issue with contrast in sphinx, im guessing there is a simple css setting somewhere that controls it but would take a while to find. also there is something to be said for using a default sphinx theme. 
- not sure how alt text works for figures generated in a jupyter notebook
   - https://github.com/jupyter/accessibility makes me think the tooling is not there at the moment. I read through a few github issues about this and did not see anything about alt text for figures specifically, but I could easily have missed it.

**Comment by rflperry** [comment]
Yeah I struggled to find settings for sphinx but I'd love to be proven otherwise. I know that we use a non-default scheme so that may not help.

**Comment by bdpedigo** [comment]
dont you use sphinx_rtd_theme? or you've made modifications to it?

**Comment by rflperry** [comment]
Yeah I use sphinx_rtd_theme but wasn't able to find settings options. The closest was an installable [https://github.com/AaltoSciComp/sphinx_rtd_theme_ext_color_contrast](https://github.com/AaltoSciComp/sphinx_rtd_theme_ext_color_contrast) which makes some changes to the base sphinx which is a valid option.

**Comment by dwaynepryce** [comment]
Adding further complications is that we need to look at how any color changes may impact read the docs building.  I am confident we can solve this and make it accessible, but from what I've read RTD has a few nuances to it that we'll have to overcome. 

I'm doing a bunch of documentation overhauling now, and I'm the primary RTD account person I'll probably be the best to work through the RTD issues after we identify generally how we want to fix things.  So... please keep me in the loop! :)

**Comment by rajpratyush** [comment]
@bdpedigo actually me and one of my friend are willing to join hands together and would resolve the issue if you want and tell us what kind of changes are you looking for

**Comment by bdpedigo** [comment]
hi @rajpratyush, that's great - as far as "tell us what kind of changes are you looking for", it would help me in general going forward if you could clarify what it is that you don't understand about these issues after reading all of the descriptions/comments/links associated with each issue. That would help me guide you in the right direction better. 

In this case there are a few specific things mentioned, especially in the link to #531 above. If there's specific stuff in there that doesn't make sense, let us know. Note that this particular issue is pretty open ended, we are just looking for ways to make our documentation more accessible (e.g. easy to read for people with color-blindness, or who have other visual impairments, etc.)

**Comment by rajpratyush** [comment]
Yess sure @bdpedigo btw can one of my friend work on this as well

**Comment by bdpedigo** [comment]
sure

**Comment by rajpratyush** [comment]
Like jointly me and my friend together  as i feel improving the visualization will be done in a better way when more than one brains work over it @bdpedigo
