### ISSUE TITLE
Configure read the docs to build PR previews

### ISSUE THREAD

**Issue by dwaynepryce** [microsoft/graspologic#627]
## Expected Behavior
RTD should have our latest documentation.

## Actual Behavior
It does not

I have to login and check out what is going on. A few weeks ago it was a memory issue and I'm sure that hasn't changed, but I forgot about it until today and I don't want to forget again - thus, a bug report.

**Comment by dwaynepryce** [comment]
@bdpedigo @j1c

So what we're finding out now is that our docs build process takes too long. ReadTheDocs has limitations of:
- 15 mins cumulative
- 3gb of ram used
- 2 concurrent builds

What happens for sure is that we run out of memory.  

```
Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
[autosummary] generating autosummary for: cli.rst, contributing.rst, index.rst, install.rst, license.rst, reference/align.rst, reference/cluster.rst, reference/datasets.rst, reference/embed.rst, reference/index.rst, ..., tutorials/plotting/pairplot.ipynb, tutorials/plotting/pairplot_with_gmm.ipynb, tutorials/simulations/corr.ipynb, tutorials/simulations/erdos_renyi.ipynb, tutorials/simulations/mmsbm.ipynb, tutorials/simulations/rdpg.ipynb, tutorials/simulations/rdpg_corr.ipynb, tutorials/simulations/sbm.ipynb, tutorials/subgraph/subgraph.ipynb, tutorials/vertex_nomination/SpectralVertexNomination.ipynb
loading intersphinx inventory from https://anytree.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://hyppo.neurodata.io/objects.inv...
loading intersphinx inventory from https://matplotlib.org/objects.inv...
loading intersphinx inventory from https://networkx.org/documentation/stable/objects.inv...
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/scipy/reference/objects.inv...
loading intersphinx inventory from https://seaborn.pydata.org/objects.inv...
loading intersphinx inventory from https://scikit-learn.org/dev/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 57 source files that are out of date
updating environment: 57 added, 0 changed, 0 removed
reading sources... [  1%] cli
reading sources... [  3%] contributing
reading sources... [  5%] index
reading sources... [  7%] install
reading sources... [  8%] license
reading sources... [ 10%] reference/align
reading sources... [ 12%] reference/cluster
reading sources... [ 14%] reference/datasets
reading sources... [ 15%] reference/embed
reading sources... [ 17%] reference/index
reading sources... [ 19%] reference/inference
reading sources... [ 21%] reference/layouts
reading sources... [ 22%] reference/match
reading sources... [ 24%] reference/models
reading sources... [ 26%] reference/nominate
reading sources... [ 28%] reference/partition
reading sources... [ 29%] reference/plotting
reading sources... [ 31%] reference/preprocessing
reading sources... [ 33%] reference/simulations
reading sources... [ 35%] reference/subgraph
reading sources... [ 36%] reference/utils
reading sources... [ 38%] release
reading sources... [ 40%] release/release_0.0.1
reading sources... [ 42%] release/release_0.0.2
reading sources... [ 43%] release/release_0.0.3
reading sources... [ 45%] release/release_0.1
reading sources... [ 47%] release/release_0.2
reading sources... [ 49%] release/release_0.3
reading sources... [ 50%] release/release_template
reading sources... [ 52%] tutorial
reading sources... [ 54%] tutorials/aligning/aligning
reading sources... [ 56%] tutorials/clustering/autogmm
reading sources... [ 57%] tutorials/clustering/kclust
reading sources... [ 59%] tutorials/connectomics/mcc
reading sources... [ 61%] tutorials/embedding/AdjacencySpectralEmbed
reading sources... [ 63%] tutorials/embedding/MASE
reading sources... [ 64%] tutorials/embedding/Omnibus
reading sources... [ 66%] tutorials/embedding/OutOfSampleEmbed
reading sources... [ 68%] tutorials/inference/latent_distribution_test
reading sources... [ 70%] tutorials/inference/latent_position_test
reading sources... [ 71%] tutorials/matching/faq
reading sources... [ 73%] tutorials/matching/padded_gm
reading sources... [ 75%] tutorials/matching/sgm
reading sources... [ 77%] tutorials/models/models
reading sources... [ 78%] tutorials/nominate/vertex_nomination_via_SGM
reading sources... [ 80%] tutorials/plotting/gridplot
reading sources... [ 82%] tutorials/plotting/heatmaps
reading sources... [ 84%] tutorials/plotting/pairplot

Command killed due to excessive memory consumption
```

One of the options we have is to split our document generation into two phases; separate tutorials out into a subproject vs. a single doc generation task and link it together with: https://docs.readthedocs.io/en/stable/subprojects.html

This has another added benefit of making our doc generation process significantly faster.  What do you all think?

**Comment by bdpedigo** [comment]
i have no probs with that!

**Comment by dwaynepryce** [comment]
I'm going to fix that stupid version file nonsense while I'm at it.

https://tenor.com/view/ingeniero-fixing-gif-7986123

**Comment by j1c** [comment]
Separating sounds good!

**Comment by dwaynepryce** [comment]
Well, I have some information for us, but it isn't that great.

ReadTheDocs will run precisely one documentation build per repository. I'm sure I could set up another project in RTD, but the problem is I can't actually tell it (in RTD) which config file to use.  So it will just build the same documentation again.

**IF** we were to pull our tutorials into an entirely separate github repository, we could include them in the main `graspologic` RTD project via the subprojects. That somewhat helps us, but it also means we'd have to split our repository and keep track of both things. I can do this, and I think I can do it reasonably quickly, but I wanted to see if you guys were okay with it.  It adds a cognitive hurdle for people to keep track of two repositories at a time, but it also means we're not cutting a new release just in case we update our tutorial documentation, and there's value in keeping them somewhat separate too.

What do you think @j1c @bdpedigo?

**Comment by dwaynepryce** [comment]
Another alternative is to leave everything as it is and everyone does `del memory_intensive_handle_here` for every output that uses up all our available memory :)

**Comment by dwaynepryce** [comment]
Watching `top` while I run this now and connectomics/mcc shot up over 3gb of usage

**Comment by bdpedigo** [comment]
that does not surprise me. that tutorial is much larger/extensive than most.

regarding your proposal:

**cons:** 
   - people adding functionality to the repo will have to make a separate PR for the tutorial, meaning reviews and issues will also be separate
   - (question) does updating graspologic (main repo) also trigger a rebuild for the tutorial docs also? 

**pros:** 
   - docs would build
   - (question) does this change anything about how builds happen locally? Like could i build most docs without building tutorial docs locally? that'd be cool
   - for a while, I've been wanting to really expand the scale/scope of tutorials. More things that either explain the more advanced concepts or apply to data. to do that would probably eventually require the change you suggest anyway.

just another thought while i'm here - i like having the connectomics/mcc tutorial, dont like that it doesnt correspond do a module like the other tutorial sections. again, i think this is mostly because it is of a slightly different flavor than most tutorials which i would like to have more of. thoughts on having separations between "tutorial" and other categories like "examples" or "advanced tutorials" or whatever we wanna call it?

**Comment by bdpedigo** [comment]
i've come back to this model a few times as something to at least aspire to https://documentation.divio.com/introduction/

**Comment by j1c** [comment]
My only concern is if RTD cant build the current docs due to limitations of the build environment, then i dont think separating into different repos will change the fact that RTD will still run out of memory when building the notebooks. FYI, I dont mind separate repos.

Thinking about the doc generation process a bit more, I realized we are building the docs 3 different times: 1) github actions, 2) netlify, 3) RTD. Currently, netlify is really just used for viewing the documentation builds on PRs, and I think RTD is for pushes to dev and main (?). Github actions, which does a build for every commit, seems to be able to build the docs relatively quickly (< 11 mins in current dev branch), suggesting machines provided for github actions is more than sufficient for graspologic at its current state. One potential solution is to use github actions to build and serve via github pages, rather than just build. We could have one action build docs without notebooks and another action build with notebooks, and push the outputs to the same branch (e.g. `gh-pages`). 

If we want to continue using RTD, i think its better to have problematic notebooks precomputed.

**Comment by dwaynepryce** [comment]
I had typed up a big comment, but after typing it all out I think I'm just making this too difficult. It's probably better to just publish a redirect to our `gh-pages` and handle our own documentation needs that way.

To capture my thoughts:
1: We should still split the documentation into reference generation and tutorial generation. This can lead to faster API development because we can get far faster feedback on when we horked something up in our apidocs than the 13 minutes or so it takes to build everything, but we still can run everything on PR.
2: I'm concerned about any circular dependencies between our notebooks and our tutorials. Right now our reference docs reference the tutorials but not the other way around. If we're splitting these up we may run into problems if we do ever go both directions, because the process will have to be "use intersphinx and the published objects.inv for each documentation artifact, but both require the other to have a reference to different things that haven't been built yet".  So we should mandate a specific direction and stick with it at all times.
3: Regarding the slow running tutorials - Github workflow actions have a time restriction of **6 hours**. This isn't a goal, because that would mean every PR will take 6 hours before checks even succeed, but it still means we aren't just buying ourselves a little time. That said, I still think we need to identify and address any of the long running tutorials if we can. I'm not sure what that looks like, though - I don't want to go around precomputing things because those inevitably get out of sync, which will be confusing. Maybe we select different data instead, if we can.  I wonder if we can get metrics on how long each individual notebook or better, every cell in every notebook, takes to run. I'm sure there are good reasons for some things to take too long so I don't want to enforce any broad rules, but it will at least give us something to look at and use to raise attention for the slow running tasks and see if there are better ways to do them. 

One of the things I need to look into is if RTD will allow us to post a redirect to our `gh-pages` or not. We are also going to have problems with linking specific versions of the documentation - `dev` and `main` are easy enough, but each release will need to be captured and maintained, and if we ever get into a "bugfixes on 0.1.x but also publishing 0.2.x" scenario, we're going to have to account for that.

**Comment by dwaynepryce** [comment]
https://github.com/sphinx-contrib/sphinxcontrib-versioning

**Comment by dwaynepryce** [comment]
https://holzhaus.github.io/sphinx-multiversion/master/index.html

**Comment by dwaynepryce** [comment]
This actually is working now, and more importantly, the callback is working.  I need to enable RTD to show PR builds to us as well so that we can view those documents ahead of time.

I don't know what the right call is for building the tutorial documentation. We could probably zip it up in the tutorial task and register it as an artifact and that might allow us to download it, then we could finally turn netlify off.  What do you think @bdpedigo?

**Comment by bdpedigo** [comment]
if theres anything here not covered in #720 please reopen, I'm just trying to declutter cause I think we had like 5 open issues along the lines of "fix docs"
