### ISSUE TITLE
[BUG] giant series of runtime warnings in MCC tutorial

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#631]
https://graspy.neurodata.io/tutorials/connectomics/mcc.html
see [11]

**Comment by v715** [comment]
`pd.options.mode.chained_assignment = None` was supposed to suppress those warnings!

I'll add the blanket "suppress all warnings" method at the beginning

**Comment by v715** [comment]
Nevermind, these are `hyppo` warnings, but same strategy applies

**Comment by rajpratyush** [comment]
@loftusa is this still open??

**Comment by loftusa** [comment]
> @loftusa is this still open??

[this](https://github.com/microsoft/graspologic/pull/633) pr will close it, just needs to get merged

**Comment by bdpedigo** [comment]
@v715 do you plan on wrapping this up or should @rajpratyush modify your PR? I just had one small bit of feedback on #633

**Comment by v715** [comment]
sorry this fell by my radar

@rajpratyush if you want to fix up the small thing @bdpedigo requested, i'd be grateful for your help!

**Comment by rajpratyush** [comment]
@bdpedigo @loftusa  solved your issue and will create a new PR for this
