### ISSUE TITLE
Add all-contributors integration

### ISSUE THREAD

**Issue by dwaynepryce** [microsoft/graspologic#640]
Also add a contributors.md file.  I want to make sure we keep a historical record of all the contributors to graspologic - both developers/committers as well as the people directly supporting this effort without any coding contributions.

For instance, @carolyncb and @bryantower have done a lot, and I know JHU has people too.  I don't want to rely on what is in the commit history because we have been foolishly squashing things and things get lost.  So I want to make sure we have an opportunity to register all of the contributors to this project, not just the ones who finalized the PR or contributed code.

**Comment by rajpratyush** [comment]
@dwaynepryce Can I work on this??

**Comment by dwaynepryce** [comment]
I think it's something you will need project admin over to do, so I think it'll have to be me.  Thanks though!

**Comment by loftusa** [comment]
I nominate @rajpratyush to be on the file, he's been contributing a lot recently! :)

**Comment by dwaynepryce** [comment]
Oh that goes without saying!

**Comment by dwaynepryce** [comment]
This is done
