### ISSUE TITLE
[BUG] Seedless Procrustes reference 1 is just a TODO in the docs

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#645]
see here: https://github.com/microsoft/graspologic/blob/dev/graspologic/align/seedless_procrustes.py#L108

**Comment by bdpedigo** [comment]
@loftusa would be helpful if you could provide a link to this in the code for any newcomers

**Comment by loftusa** [comment]
> @loftusa would be helpful if you could provide a link to this in the code for any newcomers

edited original post!

**Comment by rajpratyush** [comment]
@bdpedigo I could not understand the issue properly. Can you explain ?

**Comment by bdpedigo** [comment]
@loftusa can explain?

**Comment by loftusa** [comment]
@rajpratyush[ line 108 in the documentation for seedless procrustes](https://github.com/microsoft/graspologic/blob/dev/graspologic/align/seedless_procrustes.py#L108) has a #TODO instead of an actual reference. That should be fixed, since we shouldn't have  #TODO in the main documentation.

**Comment by bdpedigo** [comment]
but do you know the reference @loftusa ? Agterberg's latest paper I think?

**Comment by rajpratyush** [comment]
lemme go though it overnight and will push a PR in a day or two. @bdpedigo this time I wont forget to run the black code formatting tool before pushing

**Comment by rajpratyush** [comment]
@loftusa @bdpedigo First of all, sorry for the delay I wanted to know what is the reference to be added here?

**Comment by rajpratyush** [comment]
@loftusa please address to my query

**Comment by alyakin314** [comment]
https://arxiv.org/abs/2012.09828
