### ISSUE TITLE
[BUG] Possible issue with direct import

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#653]
```
import graspologic
dir(graspologic)
```
returns 

```
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version',
 '__version__',
 'graspologic',
 'layouts',
 'models',
 'partition',
 'plot',
 'preprocessing',
 'subgraph',
 'version']
```

and is missing lots of modules (align, cluster, datasets, embed, inference, match, nominate, pipeline, utils).
Is this intentional?

**Comment by bdpedigo** [comment]
not intentional AFAIK

**Comment by rajpratyush** [comment]
Lemme try and check if I am able to reproduce the same error

**Comment by rajpratyush** [comment]
@loftusa When I tried your code into google Colaboratory I didn't faced any such error here is the screen shot attached for reference.
![Screenshot (660)](https://user-images.githubusercontent.com/53184883/107137812-1d8f1980-6936-11eb-9d82-7fd8a5fcb835.png)

but when I try the same thing in jupyter notebook I am getting an error in installing the graspologic but when I installed it via command prompt it was successfully installed without any warning or errors.
![Screenshot (661)](https://user-images.githubusercontent.com/53184883/107137818-297adb80-6936-11eb-945f-c5aea96252ce.png)
![Screenshot (662)](https://user-images.githubusercontent.com/53184883/107137823-2e3f8f80-6936-11eb-9712-e95c08a62323.png)

**Comment by rajpratyush** [comment]
I don't know if it just in my system or not @bdpedigo @loftusa

**Comment by loftusa** [comment]
hmm @rajpratyush I just pip uninstalled and then reinstalled, and now I'm getting the same list you are.
I do notice that `nominate` is still missing in both of our installations.

Not sure why my `dir` was messed up before -- @bdpedigo could you try?

**Comment by bdpedigo** [comment]
does look like nominate was never added here https://github.com/microsoft/graspologic/blob/dev/graspologic/__init__.py

**Comment by rajpratyush** [comment]
well I installed with pip install graspologic lemme see again if I get nominate this time or not. but why is I am not able to install graspologic in jupyter notebook

**Comment by loftusa** [comment]
> well I installed with pip install graspologic lemme see again if I get nominate this time or not. but why is I am not able to install graspologic in jupyter notebook

Looks like some `llvmlite` conflict? Try `pip uninstall llvmlite`
I also recommend installing graspologic by going to its root directory (so that `setup.py` is in your working directory) and using `pip install -e .`. That'll install the current working version, and auto-implement any changes you make to it, so that you can test stuff you change without reinstalling the package.

**Comment by rajpratyush** [comment]
Sureee lemme just test again

**Comment by loftusa** [comment]
Reopening

**Comment by bdpedigo** [comment]
I vote close unless we have a simple reproducible example of the bug

**Comment by rajpratyush** [comment]
Well lemme try it today if it happens againor not

**Comment by rajpratyush** [comment]
got the nominate this time in google colab and in jupyter notebook as well. Hence I propose this issue can be closed.

![Screenshot (663)](https://user-images.githubusercontent.com/53184883/107198842-a2079800-6a1b-11eb-908b-dfdee85c23ad.png)
![Screenshot (664)](https://user-images.githubusercontent.com/53184883/107198850-a59b1f00-6a1b-11eb-8a4b-00772060fd4e.png)

Moreover I successfully installed graspologic in conda and its working well though the use of virtual environment.

![Screenshot (665)](https://user-images.githubusercontent.com/53184883/107199823-e182b400-6a1c-11eb-9d6d-9ca425cfa605.png)

**Comment by loftusa** [comment]
Great!
