### ISSUE TITLE
[BUG]  graspy.neurodata.io no longer exists

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#664]
graspologic.neurodata.io doesn't work either

**Comment by bdpedigo** [comment]
i cant tell if this is actually a bug, as the URL is just different now... if you still think there's something wrong please reopen and we can discuss what other URLs should work?

**Comment by loftusa** [comment]
I mainly think we should have the two links redirect to the new docs. For instance, [this](https://stackoverflow.com/questions/62013230/model-for-generating-and-detecting-communities-in-dense-network) stackoverflow question includes one of the old links, and who knows how many other places on the internet the old link was put in and we're losing people who would have discovered the package because they click and get a 404

**Comment by bdpedigo** [comment]
fair. do you know how to set that up?

**Comment by ngcd04-fa07** [comment]
Hey
This would be my first open-source contribution, and I'd love to work on this. Would you please assign this to me and guide me a bit as to what needs to be done?
Thank you

**Comment by loftusa** [comment]
> Hey
> This would be my first open-source contribution, and I'd love to work on this. Would you please assign this to me and guide me a bit as to what needs to be done?
> Thank you

Hey, awesome!
@lawreros do you know? You've been working a lot on website stuff recently
