### ISSUE TITLE
Speed up tests

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#711]
## Is your feature request related to a problem? Please describe.
Tests take >30 mins to build

## Describe the solution you'd like
Tests to take <15 or <10 mins?

## Additional context
Not sure if this is a difference caused by switching over to use github to build everything, or if we have just added so many new features that we have way more tests, but I feel like we could cut back on some of the computational rigor for some of our tests (i.e. several early tests we wrote were pretty strict about looping over many random samples of data or something like that).

**Comment by loftusa** [comment]
incorporate more `joblib`

**Comment by bdpedigo** [comment]
sure to fixtures or any other computationally smart stuff

what i meant was lets literally make them less computationally burdensome (fewer samples, smaller data, etc.)

**Comment by bdpedigo** [comment]
just as an example https://github.com/microsoft/graspologic/blob/bfcfde4bbb9b4ac251596eb9ebcb3b9496f3446e/tests/test_sims.py#L906

**Comment by bdpedigo** [comment]
done in https://github.com/microsoft/graspologic/pull/1010
