### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by daxpryce** [microsoft/graspologic#721]
# Problem

We need to capture release notes in our process.  We're not doing that right now.  What's should we do?  Are there any tools that can help us?  We have a bespoke CICD process - what will we need to change to incorporate new tooling?

## More Details

Taking the PR titles doesn't seem to be a useful thing.  I don't really want to rely on those as our change notes.  Some other teams I know have used tooling like https://github.com/microsoft/beachball but I'm not sure if that would be appropriate for us or not?

We need someone who can do some digging and checking things out for how this would work, which means they should get a good handle on exactly how our CICD-style publication process works in Graspologic first.  We will likely have to change a lot of stuff, no matter what we choose, so we need someone to really own this process.  I built it, so I can explain it all, but I'm afraid I'm not going to have the time to give this the attention it needs, so I'm looking for someone I can hand this off to and own the CICD process for us.

**Comment by rajpratyush** [comment]
@dwynepryce

Generally this sort of thing is done by issue tracking software. You track every new feature, every bugfix and every enhancement, assign them to a release and then generate release notes from the descriptions.


If you are using maven, there is a the maven changes plugin(http://maven.apache.org/plugins/maven-changes-plugin/index.html) for this purpose and producing this report could thus be easily automated in an continuous integration process.


If you use JIRA (which I'd suggest any way), it can auto-generate the release notes(https://confluence.atlassian.com/adminjiraserver073/creating-release-notes-861253367.html) for you. The built-in format is rather simplistic, but works well in many cases. The content is customizable to a point, albeit this is not the ultimate word in terms of flexibility.


If you look for better release notes from JIRA, try the PDF View Plugin(https://marketplace.atlassian.com/apps/5167/better-pdf-exporter-for-jira). It:


- more than just a raw "completed issues" list (ex: installation and upgrade instructions, legal details, executed tests, changed files)

- more control over what is included (excluding certain statuses, resolutions, issue types, etc.)

- allows distributing your Release Notes document in email (PDF format) or printed on paper

**Comment by rajpratyush** [comment]
@dwaynepryce One good article to refer to for auto generation of the release notes.

https://willys-cave.ghost.io/auto-generating-release-notes-in-azure-devops-pipelines/
