### ISSUE TITLE
Binary SBM colorbar?

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#725]
I have code that makes heatmaps look like this.
<img width="557" alt="Screen Shot 2021-03-08 at 9 20 16 PM" src="https://user-images.githubusercontent.com/12386450/110408815-32a1ba00-8054-11eb-9f46-7724de93125d.png">
Pretty straightforward, but the colorbar might be convenient. Do we want it in graspologic? it'd be something like a `binary_cbar` parameter on `heatmap`.

**Comment by bdpedigo** [comment]
is this the same as https://github.com/microsoft/graspologic/issues/592? 

in any case im fine with it, lets just close this issue or the other. still not sure about whether it should be automatic, tho

**Comment by loftusa** [comment]
oh yeah, woops, forgot I made that, I'll just post that in there
