### ISSUE TITLE
Make matplotlib version spec more specific

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#726]
## Is your feature request related to a problem? Please describe.
- A while ago we specified specific matplotlib versions (see https://github.com/microsoft/graspologic/pull/402)
- this was due to an error with a specific matplotlib version and I think something with seaborn 
- this has since been fixed in subsequent versions of matplotlib

## Describe the solution you'd like
- we should figure out which specific versions of matplotlib are incompatible, and only specify those in the setup.cfg

## Additional context
See where we do this in setup here https://github.com/microsoft/graspologic/blob/35085fa4c40b37b809b6627bfa6d8310348035be/setup.cfg#L33

**Comment by bdpedigo** [comment]
just make sure it passes all of our tests with that version of matplotlib installed. i think the answer will be that 3.3.1 is the only bad one. 

also, im not sure, but you might have to look at whether seaborn version matters too. you can look at the original issue in seaborn that i linked in that PR.

**Comment by rajpratyush** [comment]
@bdpedigo do I have to run all the tests locally ?

> just make sure it passes all of our tests with that version of matplotlib installed
 how to run these tests?

**Comment by bdpedigo** [comment]
https://github.com/microsoft/graspologic/blob/dev/CONTRIBUTING.md#pull-request-checklist

please see contributing guidelines about running tests. 

https://docs.pytest.org/en/stable/

**Comment by bdpedigo** [comment]
@rajpratyush just checking if you still plan on doing this one or not, if not no worries but I'd just like to know so we can get it taken care of. Thanks!

**Comment by rajpratyush** [comment]
Indeed i am just busy in exams starting the work from 27th

**Comment by Farhan-jafri** [comment]
Hi, I would like to work on this issue. Please guide me further on what needs to be done. Thanks😄

**Comment by bdpedigo** [comment]
we just need someone to go through each version of matplotlib since 3.3.0, install that version of the package, run our tests, and document whether or not all tests pass with that version of matplotlib installed

**Comment by loftusa** [comment]
bump, would like to prioritize this, we should allow `matplotlib 3.4.3`, there are some good new features and it's making incompatibility bugs pop up
