### ISSUE TITLE
[Question] Is graspologic incompatible with matplotlib==3.3.4?

### ISSUE THREAD

**Issue by rajpratyush** [microsoft/graspologic#731]
This is our forum for asking whatever network question you'd like!  No need to feel shy - we're happy to talk about graphs!
![Screenshot (703)](https://user-images.githubusercontent.com/53184883/111104189-159a4900-8576-11eb-975c-89f4233d9a5c.png)

**Comment by bdpedigo** [comment]
as far as I know that is only because of #726. the point of that issue is to remove the version spec that is causing that issue, since i am guessing everything with that version of matplotlib works fine.

**Comment by bdpedigo** [comment]
closing as this is the issue in #726
