### ISSUE TITLE
Adding a copy button to code snippets

### ISSUE THREAD

**Issue by rajpratyush** [microsoft/graspologic#732]
## Is your feature request related to a problem? Please describe.
well i was browsing through the tutorial section of the documentation website. I felt that a copy button was necessary in every code snippet. 

## Describe the solution you'd like
adding sphinx copy button extension to the documentation website.

## Provide references (if applicable)
If your feature request is related to a published algorithm/idea, please provide links to 
any relevant articles or webpages.

**Comment by dwaynepryce** [comment]
@rajpratyush do you know if there's anything in the sphinx ecosystem that will do this by default?  It does seem useful, and it would be useful next to every \`\`\` block, I'd think?  I don't want to do it if we have to do it manually, but if it exists as part of documentation creation it seems like an easy enough thing to add

**Comment by rajpratyush** [comment]
Sphinx copy button allows us to do it

**Comment by rajpratyush** [comment]
just we need to add it to our extensions in conf.py and some minor tweaks in JavaScript  and it has been able to get us a copy button in each code snippet a own  copy button. though would have to figure out how to make it work with ipynb files. I have tried that out yet. @dwaynepryce

**Comment by Dhavin** [comment]
Hello @rajpratyush, I would like to contribute to this project by solving this issue. Can I?
