### ISSUE TITLE
Permute initial position when given and shuffle_input is True for graph matching

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#735]
## Is your feature request related to a problem? Please describe.
https://github.com/microsoft/graspologic/blob/e465fa39ceb65156e3dea1d256fb566eb14aa215/graspologic/match/qap.py#L428
When using a user-definited initial position, we dont account for `shuffle_input`

I think we should since otherwise the initial position is meaningless

## Describe the solution you'd like
Permute `P0` when it is given (see line above)

cc: @asaadeldin11 agrees

**Comment by rajpratyush** [comment]
does this permutation should occur before the `atleast_2d` function? @bdpedigo

**Comment by bdpedigo** [comment]
hi @rajpratyush, i think myself or @asaadeldin11 will take care of this one shortly
