### ISSUE TITLE
Search Engine Optimization

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#748]
When you search `python network analysis library` or `python graph analysis library` on google, `graspologic` isn't in the first page of the results. Is there anything we can do to rectify that? @dwaynepryce maybe microsoft people know some stuff about SEO?

**Comment by jovo** [comment]
related, somebody could make a PR to this: https://github.com/briatte/awesome-network-analysis#python

**Comment by loftusa** [comment]
> https://github.com/briatte/awesome-network-analysis#python

[I made a PR about an hour ago to that ](https://github.com/briatte/awesome-network-analysis/pull/97) 😛
