### ISSUE TITLE
Add `verbose` parameter to GraphMatch

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#760]
## Is your feature request related to a problem? Please describe.
Would like the option to print progress over: 
- initializations
- iterations of Franke-Wolfe

## Describe the solution you'd like
`verbose` parameter to be added to the class (see sklearn for examples)

**Comment by ngcd04-fa07** [comment]
Hey
This would be my first open-source contribution, and I'd love to work on this. Would you please assign this to me and guide me a bit as to which class the verbose parameter needs to be added to?
Thank you

**Comment by loftusa** [comment]
> Hey
> This would be my first open-source contribution, and I'd love to work on this. Would you please assign this to me and guide me a bit as to which class the verbose parameter needs to be added to?
> Thank you

I think [this](https://github.com/microsoft/graspologic/blob/dev/graspologic/match/gmp.py#L12) one, right @bdpedigo?

**Comment by ngcd04-fa07** [comment]
> > Hey
> > This would be my first open-source contribution, and I'd love to work on this. Would you please assign this to me and guide me a bit as to which class the verbose parameter needs to be added to?
> > Thank you
> 
> I think [this](https://github.com/microsoft/graspologic/blob/dev/graspologic/match/gmp.py#L12) one, right @bdpedigo?

Okay cool I'll start working on it!

**Comment by ngcd04-fa07** [comment]
Hi again
I'm not familiar with how this project works, so I'll need some help from you guys. I have added the verbose parameter (default value=0) to the class, and I have added the code [here](https://github.com/microsoft/graspologic/blob/29e18926bb14a0b98befa0557596384c7a149290/graspologic/match/gmp.py#L245) to print if verbose>1. But, what text does it need to display exactly?

**Comment by ngcd04-fa07** [comment]
Hey
I've added the verbose parameter to the class and the Franke-Wolfe iterations, but I'm kinda lost as to which initialisations need the verbose parameter. Please help me with the same.
Thank you

**Comment by bdpedigo** [comment]
subsuming as part of #792
