### ISSUE TITLE
pairplot_with_gmm shouldn't take `gmm` as a parameter

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#769]
I think the GMM should be made internally, and the function should accept `n_components` and `covariance_type` as parameters. This would make it cleaner -- I think pretty much every time you use it in the wild, you're going to instantiate a GMM in the line above it?

Thoughts? @dfrancisco1998 @bdpedigo 
if we want the function to work like this, I have code, I can just make a PR

**Comment by bdpedigo** [comment]
I wanted this to be able to assess how reasonable a GMM looks on data, meaning I have already fit a GMM and have the data. I think it's rare that you just want to look at a clustering and do nothing with it (except for explanation purposes).

**Comment by bdpedigo** [comment]
If you really want to be able to pass in a dictionary of GMM kwargs, have it fit the model and plot, thats fine with me, but I want this to be able to accept a `GaussianMixture` object for sure

**Comment by loftusa** [comment]
ok, probably unnecessary then. Closing issue
