### ISSUE TITLE
Make LDT reproducible

### ISSUE THREAD

**Issue by kareef928** [microsoft/graspologic#775]
## Is your feature request related to a problem? Please describe.
Latent distribution test currently does not give reproducible results

## Describe the solution you'd like
Modification of LDT code to ensure that it gives reproducible results

## Provide references (if applicable)
See #744

**Comment by bdpedigo** [comment]
thanks @kareef928 

does this also apply to LPT?

**Comment by kareef928** [comment]
I get reproducibility with the second element in the namedtuple return for LPT (sample_T_statistic), but that's it.

**Comment by bdpedigo** [comment]
Makes sense to me. Do you mind opening another issue for making LPT reproducible? The source of randomness there is distinct from that in LDT, and we have more control over it, so we'd be able to fix it.
