### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by fidelle** [microsoft/graspologic#776]
Hi, I am having an error while trying to import certain packages. The error is 
ModuleNotFoundError: No module named 'hyppo._utils'

This is an example of a package I am importing that gives this error 
from graspologic.models import DCSBMEstimator 

Please how can I resolve this issue. I just downloaded graspologic so I should have the most up to date version.

**Comment by j1c** [comment]
Hi @fidelle!

This is a bug thats been fixed in the `main` branch, but not yet incorporated into latest release. In the meantime, you can run `pip install hyppo==0.1.3` to fix the issue.
