### ISSUE TITLE
Speeding up Pandas Workflow with Pypolars library

### ISSUE THREAD

**Issue by rajpratyush** [microsoft/graspologic#781]
## Is your feature request related to a problem? Please describe.

Pandas is one of the most important Python packages among data scientist’s to play around with the data. Pandas library is used mostly for data explorations and visualizations as it comes with tons of inbuilt functions. Pandas fail to handle large size datasets as it does not scale or distributes its process across all the cores of the CPU.
Modin accelerates Pandas queries by distributed computing. It utilizes all the cores of the system
To speed up the computations, one can utilize all the cores of the CPU and speed up the workflow. 

## Describe the solution you'd like

 Implementation and usage of the PyPolars library or Modin library and comparing its performance with Pandas library.
## Describe alternatives you've considered

 PyPolars has an API very similar to that of Pandas, but still, it does not cover all the functions of Pandas. For example, we don’t have .describe() function in PyPolars, instead, we can use df_pypolars.to_pandas().describe()
Modin does not support all the Pandas functions, but it supports the most famous ones.
## Provide references (if applicable)

https://gist.github.com/krsatyam1996/2a8e7cb74305c9005f0091d88e6a04e3#file-pypolar-ipynb
## Additional context
for PyPolars
For demonstrations, Here, a large size dataset is used (~6.4Gb) having 25 million instances.
![1_DJ28uvzxWUcF7FViFS0wJA](https://user-images.githubusercontent.com/53184883/116960184-487ed480-acbd-11eb-9c17-ffbc86bcb233.png)

For modin:
![1_V82tUDMjuHCXO8U56iT8wg](https://user-images.githubusercontent.com/53184883/116997504-80583d00-acfa-11eb-8c3f-1465928314a6.png)

![1_mrskOKj7p5MXVMBGalGMCA](https://user-images.githubusercontent.com/53184883/116997510-82ba9700-acfa-11eb-83ae-1a6e72952871.png)

**Comment by bdpedigo** [comment]
@rajpratyush there is very little that we actually use pandas for other than plotting, so I don't think that this would speed much up in our library

**Comment by rajpratyush** [comment]
Okay @bdpedigo

**Comment by bdpedigo** [comment]
thanks for the head up though! if we end up using it for more we'll keep it in mind
