### ISSUE TITLE
sparse matrix support

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#79]
Should be easy, most functions should already work on sparse matrices but we will need to update our typechecking in several places and write tests to make sure. 

Also J1c says that one of the SVDs does not work on sparse 

Possibly could include support for rank 1 + sparse matrices where rather than many 0s they have many of some constant

**Comment by bdpedigo** [comment]
https://scikit-learn.org/stable/modules/generated/sklearn.utils.extmath.safe_sparse_dot.html#sklearn.utils.extmath.safe_sparse_dot

**Comment by j1c** [comment]
Never really understood the point of that function.

```
def safe_sparse_dot(a, b, dense_output=False):
    """Dot product that handle the sparse matrix case correctly
    Uses BLAS GEMM as replacement for numpy.dot where possible
    to avoid unnecessary copies.
    Parameters
    ----------
    a : array or sparse matrix
    b : array or sparse matrix
    dense_output : boolean, default False
        When False, either ``a`` or ``b`` being sparse will yield sparse
        output. When True, output will always be an array.
    Returns
    -------
    dot_product : array or sparse matrix
        sparse if ``a`` or ``b`` is sparse and ``dense_output=False``.
    """
    if sparse.issparse(a) or sparse.issparse(b):
        ret = a * b
        if dense_output and hasattr(ret, "toarray"):
            ret = ret.toarray()
        return ret
    else:
        return np.dot(a, b)
```

Just does `*` instead of `@`, which I think is equivalent in later versions of python. 

```
import numpy as np
from scipy.sparse import csr_matrix

X = csr_matrix(np.random.normal(size=(100, 4)))
U = X * X.T
V = X @ X.T

(U != V).nnz == 0
>>> True
```

**Comment by j1c** [comment]
TODO:
- [ ] ASE should require no changes
- [ ] LSE might require changes to `to_laplace`
- [ ] Omni requires change in omnibus matrix creation
- [ ] cmds requires change for matrix pairwise distance computation, but no change for vector pairwise distance computation

**Comment by j1c** [comment]
More TODO:
- [ ] Change PTR to output sparse matrix if input is sparse
- [ ] Changes to simulations to output sparse matrix similar to [link](https://pygsp.readthedocs.io/en/stable/_modules/pygsp/graphs/stochasticblockmodel.html#StochasticBlockModel)
  - This is lots of work
- Need to check the following if output is sparse if input is sparse
  - [ ] LCC functions
  - [ ] `symmetrize`
  - [ ] `augment_diagonal`
  - [ ] `remove_loops`
