### ISSUE TITLE
[BUG] mug2vec assumes undirected graphs but doesn't check for this

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#793]
## Expected Behavior
Should run on a set of directed graphs

## Actual Behavior
Breaks on this line 
https://github.com/microsoft/graspologic/blob/2125f27bc3f2739f4f2c784d5b700417df63c5d7/graspologic/embed/mug2vec.py#L141
since `omni_embedding` is a tuple

**Comment by vmdhhh** [comment]
Hey @bdpedigo , The `omni.fit_transform` returns a tuple of two ndarrays. In that case, what should be taken as self.omnibus_n_components_ ?

I think it would make sense to check if `omnibus_embedding` is an instance of `ndarray` or `tuple` and then assign proper components. What do you think?

**Comment by bdpedigo** [comment]
hi @vmdhhh - I like your idea but I think it may actually be simpler to pass `concat=True` to `OmnibusEmbed` - this will ensure that the output is always an ndarray. I think it would also make sense to make  `self.omnibus_n_components_ = len(omni.singular_values_)`

I haven't tested this fix but I think it would work. If you are interested in trying it I can assign you this issue and would be happy to review your PR if you make one.

**Comment by vmdhhh** [comment]
Hey @bdpedigo, I will be happy to try it out. But I am not sure how to test it, and I also don't see any tests written for mug2vec.
Please let me know If you know any easy way to test this.

**Comment by bdpedigo** [comment]
the tests are here https://github.com/microsoft/graspologic/blob/dev/tests/test_mug2vec.py

there's also some info about contributing code and testing here https://github.com/microsoft/graspologic/blob/dev/CONTRIBUTING.md

please let me know if that helps or if you have further questions

**Comment by devil-cyber** [comment]
Is this issue still open? Can I work on this ?

**Comment by bdpedigo** [comment]
> Is this issue still open? Can I work on this ?

Sure! some info on how to solve it is provided in the comments above

**Comment by devil-cyber** [comment]
Ok thanks
