### ISSUE TITLE
Clarify expected behavior for Leiden on a disconnected graph

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#803]
## Is your feature request related to a problem? Please describe.
Several times I have been confused by output of Leiden only to realize it is because some nodes are disconnected. These nodes then will not show up in the partition dictionary. 

## Describe the solution you'd like
Just some clarification and/or a warning for what to expect

## Provide references (if applicable)
in this example node 0 is disconnected from the graph and thus key 0 is not present in the output dictionary
```python
g = nx.complete_graph(10)
nodelist = sorted(g.nodes)
for node in nodelist[1:]: 
  g.remove_edge(0, node)
leiden(g)
```
```
 {3: 0, 4: 0, 7: 0, 2: 0, 9: 0, 6: 0, 5: 0, 1: 0, 8: 0}
```

cc: @daxpryce

**Comment by daxpryce** [comment]
Would it be short sighted to just make these isolate nodes be in their own, isolate communities?

My big worry is what happens if you pass in this result dictionary referencing nodes that won't exist to the native code (because they aren't in the edge list) if you wanted to use that dictionary as the starting partitioning.  I think right now I throw an exception (https://github.com/microsoft/graspologic-native/blob/dev/packages/pyo3/src/mediator.rs#L204) if you pass in a node in the starting communities dictionary that isn't in the network edges you pass in. 

Maybe we just document it, we can detect and warn about it, and let people know that if they are doing a node level lookup and the node is an isolate they should probably do `partitions.get(node, None)` vs. `partitions[node]` or something?

**Comment by bdpedigo** [comment]
> Would it be short sighted to just make these isolate nodes be in their own, isolate communities?

Probably. This is perfectly valid but I'm guessing is almost never what the user wants. Thoughts?

> Maybe we just document it, we can detect and warn about it

Yeah I think this sounds reasonable, personally I think a warning would be nice so when I go to use that dictionary as a map I know what to expect. 

In other places in the library if we are feeding nx graph and expecting a dictionary, and we internally remove isolates/non LCC nodes, I think we should probably throw this kind of warning

**Comment by daxpryce** [comment]
I could also change the return type to also return a `set` of unpartitioned nodes.  That might make a lot more sense anyway

**Comment by bdpedigo** [comment]
im in favor of just a warning/explanation in the docs, just keeps the return type slightly simpler and still tells someone that some nodes are dropped and they cant blindly map using that partition. 

is there some reason you prefer specifying which nodes were dropped? 

don't feel too strongly though

**Comment by pbourke** [comment]
Is there an established pattern for emitting warnings? Or do we just want to add a warning to the doc string?

**Comment by daxpryce** [comment]
`warnings` module, `warnings.warn(msg)` specifically

**Comment by daxpryce** [comment]
the `unittest.TestCase.assertWarns()` check is useful in unit tests too

**Comment by pbourke** [comment]
Is it fair to say that we only care about isolates when the input is an nx Graph? Would not apply to edgelist as input. I guess for the matrix input forms we could detect if any rows are all zeros, but that seems like overkill

**Comment by daxpryce** [comment]
I think we need to do it for nx and for matrices.  I have no idea how involved that is in the sparse case :(

**Comment by bdpedigo** [comment]
i'd recommend just using https://github.com/microsoft/graspologic/blob/29e18926bb14a0b98befa0557596384c7a149290/graspologic/utils/utils.py#L425 and throwing a warning if not. 

this check can be potentially expensive, but we could provide the option to turn it off a la `check_directed` in Leiden https://github.com/microsoft/graspologic/blob/29e18926bb14a0b98befa0557596384c7a149290/graspologic/partition/leiden.py#L212 or `check_lcc` in embed https://github.com/microsoft/graspologic/blob/29e18926bb14a0b98befa0557596384c7a149290/graspologic/embed/base.py#L84

**Comment by daxpryce** [comment]
Might I suggest a different approach?

```
if isinstance(graph, nx.Graph):
  # check if graph.number_of_nodes() == len(partitions), if not, we can presume isolates are removed
else if <is matrix form>:
  # check if graph.shape[0] == len(partitions), if not, we can presume isolates are removed
```
 Doing it this way means fewer check flags, which are an evil (though sometimes necessary), and also somewhat keeps the divergent-paths-depending-on-graph-representation-type stuff to a minimum

**Comment by bdpedigo** [comment]
> Might I suggest a different approach?
> 
> ```
> if isinstance(graph, nx.Graph):
>   # check if graph.number_of_nodes() == len(partitions), if not, we can presume isolates are removed
> else if <is matrix form>:
>   # check if graph.shape[0] == len(partitions), if not, we can presume isolates are removed
> ```
> 
> Doing it this way means fewer check flags, which are an evil (though sometimes necessary), and also somewhat keeps the divergent-paths-depending-on-graph-representation-type stuff to a minimum

love it! way simpler

i wonder though, what is happening internally in Leiden, such that the partition is always the same length as the LCC?

**Comment by pbourke** [comment]
I don't think it's to do with Leiden. When we build the edgelist to pass to Leiden we only iterate edges, which will drop any isolate nodes:

https://github.com/microsoft/graspologic/blob/29e18926bb14a0b98befa0557596384c7a149290/graspologic/partition/leiden.py#L80

If you pass a disconnected graph with components, then you'll get those nodes back in the output

**Comment by daxpryce** [comment]
well, partitions is the dictionary - we're just checking the size of it, or number of elements.

in other words, you know that leiden thinks there were, say, 15 nodes in the graph, but if your source graph says there are 20 then you know there's a mismatch

**Comment by bdpedigo** [comment]
oh so this is less to do with connected components, and more just isolated (no edge) nodes that are ignored in the partition output?

**Comment by pbourke** [comment]
I'm working on a variant of Dax's suggestion, but I'm doing it in the `_validate_and_build_edge_list` function, so that it returns all nodes

**Comment by bdpedigo** [comment]
if I have a graph with 4 nodes, 2 edges:
A <-> B
C <-> D

Leiden should still work and return a partition of length 4?

**Comment by pbourke** [comment]
yep, that's what I was seeing in my testing

**Comment by daxpryce** [comment]
> if I have a graph with 4 nodes, 2 edges which is not fully connected:
> A <-> B
> C <-> D
> 
> Leiden should still work and return a partition of length 4?

Precisely!

It should even work if you have:

A <-> B
C <-> C

The node list is a superset of all nodes in the edge list, which is not necessarily the nodelist.

I wonder if we can emulate this in the algorithm by giving self loops in all disconnected edges with weight = 0?  Then everything would always get a partition, even if our graph we pass in is always defined by an edge list?

**Comment by daxpryce** [comment]
If you're super curious, the reason why this is a problem is that the leiden impl we have is **excessively** linked to  the in-memory representation of a graph.  It's ... non trivial to accommodate isolates - or at least, not off the top of my head!

**Comment by bdpedigo** [comment]
for isolated nodes, if you wanted to include them like that, would you just envision having them each become their own "cluster"?

what about for a graph that is say, 2 connected components, each with 1000 nodes. what does Leiden do on that? is it effectively the same as running leiden twice, once on each component?

**Comment by daxpryce** [comment]
an isolated node should only ever be in it's own partition - it doesn't really have a community, yanno?

I would say that 2 connected components would probably give you roughly similar results to running leiden on each LCC.  the difference is all going to fall down to PRNG giving you slightly different results.  I bet if you ran some tests where you did a graph of 2 CCs vs. 2 separate CCs and did an ARI over the partitions it would come out pretty favorably.  I don't have any data to support that, but that would be my expectation and intuition

**Comment by daxpryce** [comment]
> an isolated node should only ever be in it's own partition - it doesn't really have a community, yanno?

in fact, this is one of the enhancements leiden offers over louvain, which conceptually could randomly place isolate nodes in any community at all, whereas leiden restricts community membership to nodes that have a path into that community via their neighborhood

**Comment by bdpedigo** [comment]
makes sense - i was just wondering whether we would be doing the user a favor by actually doing this LCC check for them. but in this case sense I think the notion of community/partition is well defined enough in the example above, seems like we should just let Leiden rip on the disconnected graph?

**Comment by daxpryce** [comment]
I don't know that the LCC should matter - it makes sense that your embeddings lose coherency/utility, but > 1 CC is perfectly fine in the leiden case.  I don't think we should lcc check, but we *should* make sure we warn if we're returning a partitions dictionary that doesn't contain a partition for every node :)

**Comment by daxpryce** [comment]
Aside, I wonder if I should be requiring an adjacency/neighbor list instead of edge list in rust, that way if we ever DO get wasm bindings or direct rust crate usage, it would support everyone, not just our own special case in python.  I am just not sure when I can get to it
