### ISSUE TITLE
Fix matplotlib version requirement

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#809]
currently we have `matplotlib>=3.0.0,<=3.3.0`.
Matplotlib >= 3.4.0 has some nice features, like `supxtitle`.

Is there a reason we still clip the version?
If not, see #810

**Comment by bdpedigo** [comment]
closing cause duplicate of https://github.com/microsoft/graspologic/issues/726 (but would love to have this fixed, thanks for the PR)
