### ISSUE TITLE
Fit Models should be able to produce the parameters of the model

### ISSUE THREAD

**Issue by ebridge2** [microsoft/graspologic#826]
## Is your feature request related to a problem? Please describe.

It seems odd to me that the parameters returned by some of the fit models are not necessarily the parameters that the model would typically be specified with. For instance, consider an SBM:

```
from graspologic.simulations import sbm
from graspologic.models import SBMEstimator

n = [20, 20]
B = [[.8, .2],
     [.2, .8]]

A = sbm(n=n, p=B)

y = [0 for i in range(0,n[0])] + [1 for i in range(0, n[1])]

model = SBMEstimator(directed=True, loops=False)
model.fit(A, y=y)
```

The only parameter produced by the model appears to be a `n x n` probability matrix, `model.p_mat_`, and I cannot seem to get back an estimate of the original `p` I had specified without coding that myself manually.

## Describe the solution you'd like

Produce the parameters which the simulations accept asa leading arguments, in addition to the probability matrix.

## Additional context

**Comment by bdpedigo** [comment]
https://graspologic.readthedocs.io/en/latest/reference/models.html#graspologic.models.SBMEstimator is `block_p_` what you want?

**Comment by bdpedigo** [comment]
any thoughts on the above @ebridge2? If that is not what you want, lmk. If documentation is unclear somehow, would welcome a PR

**Comment by ebridge2** [comment]
oh; yeah, it is, good call I'm dumb lol
