### ISSUE TITLE
[BUG] Inaccurracy in how to use autokmeans

### ISSUE THREAD

**Issue by ebridge2** [microsoft/graspologic#828]
## Expected Behavior

https://github.com/microsoft/graspologic/blob/10de2bf17b972decbab318568154af226dcd71fa/graspologic/cluster/kclust.py#L16

This line is false; higher silhouette score is better, to my knowledge? https://scikit-learn.org/stable/modules/generated/sklearn.metrics.silhouette_score.html

## Actual Behavior

Documentation correctly reports how to use the package.

**Comment by j1c** [comment]
Yea highest is best. Code is correct though.

**Comment by pbourke** [comment]
Also the docstring and default value for `max_clusters` are out of agreement:

https://github.com/microsoft/graspologic/blob/10de2bf17b972decbab318568154af226dcd71fa/graspologic/cluster/kclust.py#L20

https://github.com/microsoft/graspologic/blob/10de2bf17b972decbab318568154af226dcd71fa/graspologic/cluster/kclust.py#L47
