### ISSUE TITLE
[BUG] graspologic-native installation issue

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#839]
My old laptop broke temporarily so I'm on a new (windows) machine for the time being.

In trying to reinstall graspologic, I'm encountering a few issues (this is on a fresh windows install, with a fresh python3 install (using `sudo apt-get python3`), on `wsl`).

1. call `git clone <graspologic link>`
2. navigate to folder and `pip install -e .`

I get 

```
ERROR: Could not find a version that satisfies the requirement graspologic-native>=1.0.0 (from graspologic==0.3.0) (from versions: 0.1.0.dev20201102342057300, 0.1.0.dev20201102342315507, 0.1.0.dev20201102342384736, 0.1.0.dev20201104345884402, 0.1.0.dev20201104345947520, 0.1.0)
ERROR: No matching distribution found for graspologic-native>=1.0.0 (from graspologic==0.3.0)
```

I guess I have to install `graspologic-native` manually?
issue seems fixable locally, but it feels like it should auto-install when I do `pip install -e .`

**Comment by loftusa** [comment]
@daxpryce

**Comment by daxpryce** [comment]
has to be python 3.6 or up - check and see what `python3` is on wsl (it may be 3.5 by default and you may need to explicitly install python 3.6->3.8 and if they don't seem to exist, look into the deadsnakes PPA and get a more modern one)

`python3 --version` should tell you whatup

**Comment by daxpryce** [comment]
https://pypi.org/project/graspologic-native/#files

Please verify if this fixes it, and if so, close as fixed :)

**Comment by loftusa** [comment]
@daxpryce maybe? now I'm getting all sorts of other fun issues with `pip install -e .` on `3.10.0`...

I'm gonna do battle with it for a bit and see if I can figure out whether this is a my computer thing or a graspologic thing.
I also had to `pip install cython` and `pip install numpy` manually, I was getting 'version not found' errors for both of them when I tried to install graspologic directly.
<img width="1902" alt="Screen Shot 2021-10-29 at 3 47 27 PM" src="https://user-images.githubusercontent.com/12386450/139493697-fa269b2c-e06a-42da-8923-d66b3e31f0a9.png">

**Comment by loftusa** [comment]
picture above comes along with a whole fun mess of error:

<img width="1886" alt="Screen Shot 2021-10-29 at 3 49 21 PM" src="https://user-images.githubusercontent.com/12386450/139493788-08d7bdc5-eea3-4368-93d6-6ab7c3377a2b.png">

**Comment by daxpryce** [comment]
> @daxpryce maybe? now I'm getting all sorts of other fun issues with `pip install -e .` on `3.10.0`...
> 
> I'm gonna do battle with it for a bit and see if I can figure out whether this is a my computer thing or a graspologic thing. I also had to `pip install cython` and `pip install numpy` manually, I was getting 'version not found' errors for both of them when I tried to install graspologic directly. <img alt="Screen Shot 2021-10-29 at 3 47 27 PM" width="1902" src="https://user-images.githubusercontent.com/12386450/139493697-fa269b2c-e06a-42da-8923-d66b3e31f0a9.png">

So yes, this fixes the graspologic-native issues.  We should create another ticket for ensuring we have a clean path for 3.10 for graspologic though.  Can you create that ticket and add your screenshots there?  We can also enable 3.10 in our build matrix on a branch and see what our github runners are saying across all 3 OSes so we can collect all of our problems at once :)

**Comment by loftusa** [comment]
> > @daxpryce maybe? now I'm getting all sorts of other fun issues with `pip install -e .` on `3.10.0`...
> > I'm gonna do battle with it for a bit and see if I can figure out whether this is a my computer thing or a graspologic thing. I also had to `pip install cython` and `pip install numpy` manually, I was getting 'version not found' errors for both of them when I tried to install graspologic directly. <img alt="Screen Shot 2021-10-29 at 3 47 27 PM" width="1902" src="https://user-images.githubusercontent.com/12386450/139493697-fa269b2c-e06a-42da-8923-d66b3e31f0a9.png">
> 
> So yes, this fixes the graspologic-native issues. We should create another ticket for ensuring we have a clean path for 3.10 for graspologic though. Can you create that ticket and add your screenshots there? We can also enable 3.10 in our build matrix on a branch and see what our github runners are saying across all 3 OSes so we can collect all of our problems at once :)

will do!
