### ISSUE TITLE
Give screeplot an `ax` argument

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#840]
function[ here.](https://github.com/microsoft/graspologic/blob/dev/graspologic/plot/plot.py#L1129)

Currently no way to specify an `ax`, most other plotting functions have that unless there's a good reason not to. I don't see a good reason for this one not to have it. Should be pretty easy to add on.

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue, shall i take it?!🙂

**Comment by rookiexiong7** [comment]
Is this work still ongoing?I am a beginner and would like to give it a try.

**Comment by kidkoder432** [comment]
I think you can still PR, as it hasn't been closed. I'm going to try it as well :)

**Comment by MuLIAICHI** [comment]
Greeting, did anyone try to PR that issue ?

**Comment by kidkoder432** [comment]
My PR is awaiting review.

**Comment by MuLIAICHI** [comment]
They should really bay attention here !

**Comment by kidkoder432** [comment]
I'm sorry, who are you referring to?

**Comment by bdpedigo** [comment]
FYI this was closed automatically since the PR was merged https://github.com/microsoft/graspologic/pull/1048 :)

**Comment by MuLIAICHI** [comment]
Ok :)
