### ISSUE TITLE
Change returns of `inference` functions to better match stats APIs

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#856]
## Is your feature request related to a problem? Please describe.
Currently, `inference.latent_distribution_test` and `inference.latent_position_test` return (p_value, sample_T_statistic, dict_of_other_stuff). 

In scipy, everything does (stat, pvalue, sometimes a dictionary of other stuff). See https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_1samp.html#scipy.stats.ttest_1samp and https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.multiscale_graphcorr.html#scipy.stats.multiscale_graphcorr

In hyppo, they follow the same convention https://hyppo.neurodata.io/api/generated/hyppo.ksample.ksample#hyppo.ksample.KSample.test

I see no reason we should not follow this same convention.

## Describe the solution you'd like
Change order/name of output arguments for the aforementioned two functions.

**Comment by bdpedigo** [comment]
@kareef928 would you be at all interested in this? If not, I'll do it, just lmk

**Comment by bdpedigo** [comment]
@j1c @asaadeldin11 does anyone protest to this minor change?

**Comment by asaadeldin11** [comment]
nope, seems like a good change to me

**Comment by j1c** [comment]
Looks like a good change. Tho this really means scipy stats since the the other big stats package `statsmodels` does not follow this convention.

**Comment by bdpedigo** [comment]
thanks, @kareef928!

**Comment by bdpedigo** [comment]
> Looks like a good change. Tho this really means scipy stats since the the other big stats package `statsmodels` does not follow this convention.

Fair point - yeah, I guess scipy is mainly the one I think we should care about. Though I'm curious where in statsmodels they don't do this, I clicked on a couple things that looked like tests https://www.statsmodels.org/stable/generated/statsmodels.tsa.stattools.coint.html#statsmodels.tsa.stattools.coint https://www.statsmodels.org/stable/generated/statsmodels.tsa.stattools.adfuller.html#statsmodels.tsa.stattools.adfuller and they at least looked like (stat, pvalue, ... otherstuff)

**Comment by j1c** [comment]
> > Looks like a good change. Tho this really means scipy stats since the the other big stats package `statsmodels` does not follow this convention.
> 
> Fair point - yeah, I guess scipy is mainly the one I think we should care about. Though I'm curious where in statsmodels they don't do this, I clicked on a couple things that looked like tests https://www.statsmodels.org/stable/generated/statsmodels.tsa.stattools.coint.html#statsmodels.tsa.stattools.coint https://www.statsmodels.org/stable/generated/statsmodels.tsa.stattools.adfuller.html#statsmodels.tsa.stattools.adfuller and they at least looked like (stat, pvalue, ... otherstuff)

Hmm yea I guess I was thinking based on anova (https://www.statsmodels.org/stable/generated/statsmodels.stats.anova.anova_lm.html#statsmodels.stats.anova.anova_lm) and manova (https://www.statsmodels.org/stable/generated/statsmodels.multivariate.manova.MANOVA.mv_test.html#statsmodels.multivariate.manova.MANOVA.mv_test). But it seems like others do follow that (stat, pvalue, ...).

**Comment by pbourke** [comment]
Is the order of arguments important when the result value is a namedtuple? I think namedtuples are a great way to make order less relevant (in addition to other benefits like built-in documentation and (for `typing.NamedTuple`) type hinting.
