### ISSUE TITLE
Ensure clean python 3.10.0 build path

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#869]
I'm having issues installing graspologic on 3.10.0 right now (see fun screenshot). This may or may not be local to my computer.

In any case, we should ensure we have a viable build path for graspologic on 3.10.0. See @daxpryce's advice here:

> We can also enable 3.10 in our build matrix on a branch and see what our github runners are saying across all 3 OSes so we can collect all of our problems at once :)

<img width="1886" alt="Screen Shot 2021-10-29 at 3 49 21 PM" src="https://user-images.githubusercontent.com/12386450/139494942-fe7b26a5-1515-44ab-8004-414bec01b360.png">

**Comment by daxpryce** [comment]
A superset of issues related to #839

**Comment by daxpryce** [comment]
Now that we have hit 3.9 we should add 3.10 to the build matrix and see what errors we have to deal with
