### ISSUE TITLE
Create Readthedocs Stub Site to Redirect to GH hosted docs

### ISSUE THREAD

**Issue by daxpryce** [microsoft/graspologic#881]
We were using readthedocs for our documentation hosting, but have since moved to hosting it ourselves on our `gh-pages` branch so we don't run up against the documentation generation timeout limits.

However, we need to have some way of leaving a marker at https://graspologic.readhtedocs.io that tells users our new docs site is at https://microsoft.github.io/graspologic/ instead.  

So we should put a semi-temporary sphinx generated stub site in our docs folder and update the `.readthedocs.yml` file to direct RTD to build this new site and redirect any users that have the old URL.

**Comment by jonmclean** [comment]
* Created readTheDocs-redirect-stub branch
* Created /docs/readTheDocs with a basic template with a pointer to the new location.
* Updated "latest" version in ReadTheDocs to point at the readTheDocs-redirect-stub branch.
This **should not** be merged back.

**Comment by jonmclean** [comment]
Issue completed
