### ISSUE TITLE
`networkplot` shouldn't have x and y labels

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#886]
in networkplot, the x-axis and y-axis are labeled x and y by default.

I feel like in most situations that shouldn't be there? usually if you're making a networkplot and x and y coordinate axis don't make any sense, since you're in network space, not euclidean space
<img width="678" alt="Screen Shot 2021-11-14 at 6 44 50 PM" src="https://user-images.githubusercontent.com/12386450/141703620-ad4f9f9a-1e64-4b3b-94d8-b1e45c33a004.png">

**Comment by Laozey** [comment]
Hi, I would like to tackle this issue, is it possible?
I have checked the PR from @mtandon18 and it seems kind of straight forward.

Wouldn't it be a good idea to add x/y labels as parameters and put "" as default? 
Something like:
`
labels: Tuple[str, str] = ("", "")
`

**Comment by bdpedigo** [comment]
hi @Laozey 

even simpler - i think we can just omit the labels by default, and let the user add them back in matplotlib if they desire. you are welcome to work on this if you'd like

**Comment by burugaria7** [comment]
Hi, I would like to tackle this issue, is it possible?
Please let me know if you have already solved it.
