### ISSUE TITLE
`utils.to_laplacian` should be able to find $D - A$

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#900]
Seems weird that it can't at the moment, although I realize we don't use $D - A$ too often in practice

Thoughts?

**Comment by bdpedigo** [comment]
IMO this function mainly exists to support other things in the library, not to make every laplacian out there in the literature - for example, there's also the commonly used random walk laplacian $D^-1 A$ so we could really go crazy with it and have a bunch of options

my perspective is just that I don't see a reason for having it if we dont use it ourselves for anything - if you feel strongly or have some reason you really want we could discuss more.
