### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ebridge2** [microsoft/graspologic#905]
## Expected Behavior

Signal Subgraph should use the fisher's exact test statistic.

## Actual Behavior
Signal subgraph uses the fisher's exact test p-value, as-per https://arxiv.org/pdf/1108.1427.pdf.

Line https://github.com/microsoft/graspologic/blob/a8048f1631f2f0676555cc3f04796bf6053a6496/graspologic/subgraph/sg.py#L118

should read `fisher_exact(...)[0]`, as the first argument is the p-value of the test.

**Comment by bdpedigo** [comment]
in scipy most functions return pvalue as second argument (see https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fisher_exact.html#scipy.stats.fisher_exact)

is there something that makes you think otherwise here?

**Comment by bdpedigo** [comment]
@ebridge2 lmk if you think something is still amiss
