### ISSUE TITLE
Fix documentation to include docs for class methods

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#907]
Somehow recent changes (maybe https://github.com/microsoft/graspologic/commit/81f848d9e5f3c16ac4c7cbc7ecd2a600c8066b78 ?) removed documentation for class methods, would like to add that back in 

@daxpryce we possibly just need to add `:members:` to everything like https://raw.githubusercontent.com/microsoft/graspologic/dev/docs/reference/reference/partition.rst

I also suspect perhaps there is a setting in sphinx to do this globally by default

**Comment by bdpedigo** [comment]
I think this may be the sphinx config to to this by default https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_default_options

**Comment by bdpedigo** [comment]
@dlee0156 do you think you could work on this? right now many classes dont have documentation showing for their methods which is a big problem for many of them.

**Comment by daxpryce** [comment]
In theory, this is is now fixed?  Can you verify and close @bdpedigo ?

**Comment by bdpedigo** [comment]
Closed by #921
