### ISSUE TITLE
[BUG] MyPy test failures on main

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#909]
Looks like mypy is failing on the current main. I am not sure what changed / how this got into main unless it was just caused by a update to mypy itself.

Example: this PR which changed nothing about the code https://github.com/microsoft/graspologic/pull/908
Test output (unit-and-doc-test): 
```{pytb}
Run mypy ./graspologic
graspologic\match\qap.py:420: error: Argument "key" to "sorted" has incompatible type "Callable[[Union[Sequence[Sequence[Sequence[Sequence[Sequence[Any]]]]], _SupportsArray[dtype[Any]], Sequence[_SupportsArray[dtype[Any]]], Sequence[Sequence[_SupportsArray[dtype[Any]]]], Sequence[Sequence[Sequence[_SupportsArray[dtype[Any]]]]], Sequence[Sequence[Sequence[Sequence[_SupportsArray[dtype[Any]]]]]], complex, Sequence[Union[complex, str, bytes]], Sequence[Sequence[Union[complex, str, bytes]]], Sequence[Sequence[Sequence[Union[complex, str, bytes]]]], Sequence[Sequence[Sequence[Sequence[Union[complex, str, bytes]]]]]]], Union[Sequence[Sequence[Sequence[Sequence[Any]]]], Any, _SupportsArray[dtype[Any]], Sequence[_SupportsArray[dtype[Any]]], Sequence[Sequence[_SupportsArray[dtype[Any]]]], Sequence[Sequence[Sequence[_SupportsArray[dtype[Any]]]]], complex, Sequence[Union[complex, str, bytes]], Sequence[Sequence[Union[complex, str, bytes]]], Sequence[Sequence[Sequence[Union[complex, str, bytes]]]]]]"; expected "Callable[[Union[Sequence[Sequence[Sequence[Sequence[Sequence[Any]]]]], _SupportsArray[dtype[Any]], Sequence[_SupportsArray[dtype[Any]]], Sequence[Sequence[_SupportsArray[dtype[Any]]]], Sequence[Sequence[Sequence[_SupportsArray[dtype[Any]]]]], Sequence[Sequence[Sequence[Sequence[_SupportsArray[dtype[Any]]]]]], complex, Sequence[Union[complex, str, bytes]], Sequence[Sequence[Union[complex, str, bytes]]], Sequence[Sequence[Sequence[Union[complex, str, bytes]]]], Sequence[Sequence[Sequence[Sequence[Union[complex, str, bytes]]]]]]], Union[SupportsDunderLT, SupportsDunderGT]]"
graspologic\match\qap.py:420: error: Value of type "Union[Sequence[Sequence[Sequence[Sequence[Sequence[Any]]]]], _SupportsArray[dtype[Any]], Sequence[_SupportsArray[dtype[Any]]], Sequence[Sequence[_SupportsArray[dtype[Any]]]], Sequence[Sequence[Sequence[_SupportsArray[dtype[Any]]]]], Sequence[Sequence[Sequence[Sequence[_SupportsArray[dtype[Any]]]]]], complex, Sequence[Union[complex, str, bytes]], Sequence[Sequence[Union[complex, str, bytes]]], Sequence[Sequence[Sequence[Union[complex, str, bytes]]]], Sequence[Sequence[Sequence[Sequence[Union[complex, str, bytes]]]]]]" is not indexable
graspologic\match\qap.py:420: error: Incompatible return value type (got "Union[Sequence[Sequence[Sequence[Sequence[Any]]]], Any, _SupportsArray[dtype[Any]], Sequence[_SupportsArray[dtype[Any]]], Sequence[Sequence[_SupportsArray[dtype[Any]]]], Sequence[Sequence[Sequence[_SupportsArray[dtype[Any]]]]], complex, Sequence[Union[complex, str, bytes]], Sequence[Sequence[Union[complex, str, bytes]]], Sequence[Sequence[Sequence[Union[complex, str, bytes]]]]]", expected "Union[SupportsDunderLT, SupportsDunderGT]")
graspologic\match\qap.py:433: error: Item "int" of "Union[int, RandomState, Generator, None]" has no attribute "permutation"
graspologic\match\qap.py:433: error: Item "None" of "Union[int, RandomState, Generator, None]" has no attribute "permutation"
graspologic\match\qap.py:457: error: Item "int" of "Union[int, RandomState, Generator, None]" has no attribute "uniform"
graspologic\match\qap.py:457: error: Item "None" of "Union[int, RandomState, Generator, None]" has no attribute "uniform"
graspologic\cluster\autogmm.py:559: error: Incompatible types in assignment (expression has type "List[Optional[RandomState]]", variable has type "ndarray[Any, dtype[signedinteger[Any]]]")
graspologic\embed\base.py:439: error: <nothing> has no attribute "ndim"
graspologic\embed\base.py:441: error: <nothing> has no attribute "ndim"
graspologic\embed\base.py:444: error: <nothing> has no attribute "shape"
graspologic\embed\base.py:446: error: <nothing> has no attribute "shape"
graspologic\embed\base.py:449: error: Incompatible types in assignment (expression has type "Union[ndarray[Any, Any], Any]", variable has type "List[Union[ndarray[Any, Any], Any]]")
graspologic\embed\case.py:205: error: Incompatible types in assignment (expression has type "floating[Any]", variable has type "float")
Found 14 errors in 4 files (checked 79 source files)
Error: Process completed with exit code 1.
```

Side note: when I get the latest version of mypy and run it locally on `main`, I actually get 
```
Found 393 errors in 55 files (checked 78 source files)
``` 

I wont post the whole traceback but these errors involve basically every module in the library. Many are private functions.

**A few larger points for discussion**: 
- Would anyone be opposed to taking mypy out of unit-and-doc-test and putting it as it's own check, much like black has its own code-format-check? It seems unnecessary to check on every os/version like we do for actual tests.
- Can someone explain to me what mypy gives us that beartype doesn't? I know it is static and beartype is dynamic, right? but in practice what is this doing for us? 
   - If nothing, can we remove? 
- What is our policy on mypy compatibility for legacy code that is private? 
- any tips on getting mypy to tell me what the function is that is actually causing the error? --verbose did not do it for me.

**Comment by bdpedigo** [comment]
tagging @daxpryce because I'm guessing you'll have thoughts

**Comment by daxpryce** [comment]
mypy tells us at build time that beartype is going to have an angry time at runtime.

You always want the static check to happen, otherwise you just have to hope that your unit test coverage fully encapsulates everything, and I don't know that that ever has happened in the history of ever?

Sounds to me like either a new version of mypy or changes to typeshed have exposed some holes in our type hinting, and so we need to fix those.  The fix is definitely NOT to just disable them, it's to make them say and do what they should :)

@pbourke has a lot of experience debugging this sort of stuff so he can probably get you pointed in the right direction.  I tend to just start at the first line it complains about (qap.py line 420) and see what might be fishy.

**Comment by daxpryce** [comment]
> Would anyone be opposed to taking mypy out of unit-and-doc-test and putting it as it's own check, much like black has its own code-format-check? It seems unnecessary to check on every os/version like we do for actual tests

Yes, because somewhere in our stack there's a python method that does one thing if it is windows and another if it is a unix variant re: types, and it wasn't found until later.  And it was annoying to uncover.  That's why we're doing it on all OSes (and versions, since apparently that's a common-enough-pattern in Python to return different things depending on the Python version you're on)

**Comment by daxpryce** [comment]
> What is our policy on mypy compatibility for legacy code that is private?

Make sure the private code is properly typed. At this point we shouldn't have too many untyped anythings, most of what we're uncovering in moments like this is where typeshed has been updated to have a new type hint signature when either a: it didn't before or b: it was different than what we have now.  Or at least, I think so.

**Comment by bdpedigo** [comment]
so for instance everything in match/qap.py looks untyped (long story short was a port of some scipy code which we also wrote but needed to have in our library for various reasons). 

couple reason i remain confused are that 
- when i run mypy locally I get **383** errors
- those errors (at least for qap.py) make sense, as they are referring to the line numbers of function definitions, whereas say the traceback i post above, those line numbers correspond to nothing i can make sense of

**Comment by bdpedigo** [comment]
update - this is only happening on 3.7 and 3.8. 3.9 has another issue (see #910)
