### ISSUE TITLE
[BUG] gensim-related test failures on dev

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#910]
## Full Traceback
```pytb
______________ ERROR collecting tests/preprocessing/graph_cuts.py ______________
tests/preprocessing/graph_cuts.py:10: in <module>
    from graspologic.preprocessing import graph_cuts
graspologic/__init__.py:7: in <module>
    import graspologic.embed
graspologic/embed/__init__.py:11: in <module>
    from .n2v import node2vec_embed
graspologic/embed/n2v.py:11: in <module>
    from gensim.models import Word2Vec
../../../hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/gensim/__init__.py:5: in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
../../../hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/gensim/corpora/__init__.py:6: in <module>
    from .indexedcorpus import IndexedCorpus  # noqa:F401 must appear before the other classes
../../../hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/gensim/corpora/indexedcorpus.py:15: in <module>
    from gensim import interfaces, utils
../../../hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/gensim/interfaces.py:21: in <module>
    from gensim import utils, matutils
../../../hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/gensim/matutils.py:1104: in <module>
    from gensim._matutils import logsumexp, mean_absolute_difference, dirichlet_expectation
stringsource:105: in init gensim._matutils
    ???
E   AttributeError: type object 'gensim._matutils.array' has no attribute '__reduce_cython__'
```

Getting the above error on `unit-and-doc-test (macos-latest, 3.9)` 
https://github.com/microsoft/graspologic/runs/4982698923?check_suite_focus=true
(note that I say "on dev" because this is a PR that only changed docs)

**Comment by bdpedigo** [comment]
tagging @Nyecarr since I think you've worked the most on n2v? my guess is this was caused by a dependency updating somewhere or something?

cc @daxpryce - just FYI this looks like a separate issue from #911 which is also preventing anything being merged into dev

**Comment by bdpedigo** [comment]
p.s. just a thought but i wonder whether could be related to https://github.com/microsoft/graspologic/blob/a8048f1631f2f0676555cc3f04796bf6053a6496/setup.cfg#L32 and so version 3.x.x of gensim probably wouldnt keep up with changes to things like numpy etc.

**Comment by daxpryce** [comment]
Just noting that it's python 3.9.10 macos

**Comment by daxpryce** [comment]
1. Installed Python 3.9.10 on MacOS
2. Created and enabled fresh venv
3. pip install -r requirements.txt
4. make fast-test 
5. Success
6. wait what

**Comment by daxpryce** [comment]
Telling CICD to rerun build too wtf

**Comment by daxpryce** [comment]
![Screen Shot 2022-01-31 at 1 39 27 PM](https://user-images.githubusercontent.com/899411/151877472-772bd198-b1ee-4c13-bd00-fc8cad103a55.png)

![thumbs-thumbs-up-kid](https://user-images.githubusercontent.com/899411/151877693-7fff25ce-1a4d-4ab1-a5ea-af7d6caa2860.gif)
