### ISSUE TITLE
It seems like a bad idea to expect that users know how to pad a graph based on the algorithm they pick

### ISSUE THREAD

**Issue by ebridge2** [microsoft/graspologic#936]
Padded graph matching is extraordinarily opaque as to how to use. It's really unclear how to work with the permuted seeds in the context of the original input graph given that padding occurs. This should really be extensively clarified and solidified. Suggestions would include returning permuted indices entirely in the space of the original networks, and not in the padded space.

**Comment by bdpedigo** [comment]
+1 

see related https://github.com/microsoft/graspologic/discussions/925
