### ISSUE TITLE
[BUG] SSG doesn't look like it properly handles ties?

### ISSUE THREAD

**Issue by ebridge2** [microsoft/graspologic#944]
## Expected Behavior

if there is a tie in the test statistic, the tie should be randomly broken

## Actual behavior

it does not appear that potential ties are randomly broken

https://github.com/microsoft/graspologic/blob/dev/graspologic/subgraph/sg.py

@jovo

**Comment by bdpedigo** [comment]
closing in favor of #977 which looks to have more detail
