### ISSUE TITLE
Numba JITing should happen on import instead of construction

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#946]
a consequence of this line https://github.com/microsoft/graspologic/blob/0d404caaa706f7bfbad694879c2e0d14bf3baaef/graspologic/models/edge_swaps.py#L76

is that i think numba tries to compile on each instantiation of the class, as opposed to just once for all instances. can slow things down a lot, i have found.

## description of work
- move the numba JITing to happen not in the constructor for EdgeSwapper, but rather just in the file. Renamed as a new function like `_edge_swap_numba`
- change the constructor to assign `self._edge_swap_function` to `_edge_swap_numba` when appropriate (using the same if/else logic that is already there. 

I think this should just be a 2-line change

**Comment by javajersko** [comment]
I'd like to take this issue.

**Comment by bdpedigo** [comment]
closed by #965
