### ISSUE TITLE
[BUG] Remove outdated Zenodo DOI from README.md

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#993]

**Comment by bdpedigo** [comment]
The goal is to simply remove this shield from the README

<img width="1146" alt="Screen Shot 2022-10-06 at 9 39 34 AM" src="https://user-images.githubusercontent.com/25714207/194328300-6a220574-172b-4d01-a3ee-9f813af15fb7.png">

**Comment by ktwillcode** [comment]
i would like to work on it.

**Comment by ktwillcode** [comment]
Should I remove my pull request?
Then you will assign it?
I am new to this contribution.... that's why I edited and submitted a pull request.
Kindly guide me :)

**Comment by bdpedigo** [comment]
no need to remove, thanks for the PR @ktwillcode

**Comment by bdpedigo** [comment]
closed by #994
