### ISSUE TITLE
[BUG] Reporting fails due to upstream issue (matplotlib)

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#995]
see https://github.com/mwaskom/seaborn/pull/3060
seaborn and mpl 3.6.1 dont like each other, but seaborn already knows about it. not sure if we shoudl push our own fix as well

**Comment by bdpedigo** [comment]
potential fix: specify matplotlib != 3.6.1 in setup.cfg https://github.com/microsoft/graspologic/blob/dev/setup.cfg

**Comment by bdpedigo** [comment]
planning on having Hope (not sure her github ID) work on this issue

**Comment by hugwuoke** [comment]
Looking at it now
