### ISSUE TITLE
[BUG] giant gensim error when trying to pip install on 3.10.6

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#998]
`pip install graspologic`

Results in a giant error having to do with the `gensim` requirement.
I'm using a fresh-ish ubuntu environment with python 3.10.6

I'd copy the whole error, but it's like 10 years long and all having to do with weird unicode stuff.
Is gensim a real requirement?

![gensim_error](https://user-images.githubusercontent.com/12386450/202335198-601afc6c-c167-40e0-94f9-00bfa9a45464.PNG)

**Comment by bdpedigo** [comment]
gensim is a real requirement of node2vec

have you tried just installing gensim? 

i have no idea how to debug from the above - i wonder whether something is being compiled rather than installed from a whl on your platform?

**Comment by hhelm10** [comment]
fyi - before graspologic's pypi version was 2.x.x i could get grapologic to install by first installing gensim==3.8.0.

i can similarly get graspologic 2.0.0 to install by first installing gensim==4.0.0 (not sure if any more recent versions work). the installation throws errors related to building the wheels for umap-learn and pynndescent

**Comment by bdpedigo** [comment]
here are (perhaps) some explanations of the error you're getting from a quick search in gensim (although this is about Python 3.11):

https://github.com/RaRe-Technologies/gensim/issues/3401

https://github.com/RaRe-Technologies/gensim/issues/3414

from what I can tell they think they've fixed it but haven't released. could you try seeing if setting gensim != 4.2.0 works? or the numpy/scipy stuff in the second issue?
